### ISSUE TITLE
مستوع عماد لا يعمل

### ISSUE THREAD

**Issue by Laithsudanii22** [emadmahdi/KODI#1]
السلام عليكم.
بعد ان قمت بتنزيل برنامج كودي اخر اصدار،حولت أن اكتب السورس الذي يحتوي علئ مكتبة المسلسلات والافلام"http://repo.husham.com"،لكن للاسف مستوع عماد فارغ. هل ممكن ان اجد حل للمشكلة .
شكرا.

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله
الرابط الذي انت كتبته ليس لي ولا علاقة لي به .. هذه الصورة فيها الروابط التي انت تحتاجها
استخدم 
repository.emad-2021.10.29.zip
.
.
![image](https://user-images.githubusercontent.com/7454511/225438651-a4a511d3-4130-48fe-a81f-152bc9cfb3db.png)

**Comment by Laithsudanii22** [comment]
شكرا جزيلا اخي. جزاكم الله خيرا.

**Comment by emadmahdi** [comment]
الشكر لله اهلا وسهلا بك
