### ISSUE TITLE
 القائمة الرئيسية لموقع اكوام لا تظهر نهائيا

### ISSUE THREAD

**Issue by hussapril7** [emadmahdi/KODI#1]
مرحبا اخ عماد كيف حالك، اللي اكلمك عاليوتيوب بخصوص الاضافه والمشكلة اللي تصير معاي بموقع اكوام، انا سويت نفس ماقلت ضغطت على موقع اكوام كذا مره عشان يبين الخطأ ويظهر على ملف كودي لوق ماهو الخطأ

عموما ملف كودي لوق ارفقته مع المسج 

[kodi.log.txt](https://github.com/emadmahdi/KODI/files/2506244/kodi.log.txt)

**Comment by emadmahdi** [comment]
احتاج منك ان تأخذ الملف الذي سوف ابعثه لك وتضعه بدل الملف القديم هذا ولا تنسى تغير الاسم الى
AKOAM.py

هذا هو الملف القديم
/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.arabicvideos/lib/AKOAM.py

وبعدها تجرب اكوام وترسل لي الملف kodi.log مرة اخرى

[AKOAM.py.txt](https://github.com/emadmahdi/KODI/files/2507633/AKOAM.py.txt)

**Comment by hussapril7** [comment]
اخ عماد عملت كل الخطوات التي ذكرتها وبدلت ملف اكوام وشلت كلمة تكست لكي يكون الملف مثل الملف القديم
وبعدها دخلت عالكودي ودخلت على اضافتك والى موقع اكوام ويظهر نفس الخطأ وكررت الدخول مرات اخرى لكي يتضح لك الخطأ عند الملف كودي لوق الذي سوف ارد ارسله لك مره اخرى

ولكن سؤال اخ عماد هل ممكن تشرح لي لماذا ارسل لك الملف مره اخرى ولماذا اعطتيني ملف اكوام ماهو الاختلاف بينه وبين الملف السابق ؟؟
ولماذا تريد ملف كودي لوق مرة اخرى ؟؟؟
اتمنى تفيدني بالاجابه لكي اتعلم واستفيد من معلوماتك

هذا ملف كودي لوق الذي طلبته مره اخرى 

[kodi.log](https://github.com/emadmahdi/KODI/files/2509547/kodi.log)

**Comment by emadmahdi** [comment]
للاسف الملف لم يتبدل ... قد يكون بسبب ان البرنامج قام بتحديث نفس مباشرة بعد ان قمت انت بتغير الملف ... حاول ان تعملها الان لانه لا يوجد عندي تحديث جديد

والان الشرح ... ملف اللوج الاول لم اجد فيه مشكلة سوى عدم وجود قائمة اكوام ... ولكي اعرف السبب فاني اضفت سطرين الى ملف برنامج اكوام حيث يقوم هذين السطرين بكتابة الصفحة التي سوف يجلبها البرنامج من الاننترنيت مباشرة الى ملف اللوج بدون تدخل البرنامج ولكي اقرأ هذه الصفحة الجديدة فانا بحاجة الى ملف اللوج مرة اخرى

**Comment by emadmahdi** [comment]
اذا كنت تريد ان تغير ملف اكوام بيدك بدون ان تعيد عملية النسخ مرة اخرى ... فاذن غير سطر 24 وسطر  25 وامسح منهما هذه العلامة
#

**Comment by emadmahdi** [comment]
حاول ان تحدث البرنامج الى الاصدار الجديد 2.7.0 ... وبعدها قم بتغير ملف اكوام بنسخه او بتعديل السطرين

**Comment by hussapril7** [comment]
صح كلامك امس من بدلت الملف لقيت تحديث للاضافه فا حدثت وبعدها رسلت لك، عموما انا سويت الحين نفس ماقلت لي سويت تحديث الاضافه بعدها غيرت ملف اكوام وبعدها رحت للكودي ودخلت موق اكوام وعطاني خطأ كالعاده وكررت الدخول لكي يتضح الخطأ عندك بالكودي لوق

المهم اخ عماد هذا الملف مره اخرى واتمنى تعطيني الحل النهائي لمشكلة اكوام او تقوم بتحديث جذري للاضافه ويكون كل شي شغال فيها

هذا الملف 

[kodi.log](https://github.com/emadmahdi/KODI/files/2515255/kodi.log)

**Comment by emadmahdi** [comment]
هذا هو الخطأ
Error 101: 'Network is unreachable'
ومعناه ان جهازك غير قادر على الوصول الى سيرفر اكوام ... يعني جهازك ممنوع من الوصول الى بسيرفر اكوام

 وهكذا خطأ اسبابه كثيرة ... مثلا شبكة بيتك تستخدم برامج مثل هذه وتحتاج الى تضبيط صحيح لكي تصل الى السيرفر الممنوع
proxy - firewall - antivirus - anti hacker - vpn - router - adblock

جرب الدخول الى موقع اكوام من نفس جهاز الاندرويد الذي بعثت لي اللوج له
https://akoam.net

**Comment by emadmahdi** [comment]
وممكن ايضا السبب من
dns - hosts file
وايضا ممكن ان يكون ممنوع من الحكومة او من شركة الانترنيت او ممكن ان يكون ممنوع من شركة اكوام على كل الناس في بلدك او في منطقتك الجغرافية

**Comment by hussapril7** [comment]
انا لدي راوتر ومن كنت ادخل موقع اكوام عن طريق المتصفح في الكمبيوتر كان يدخل ولكن في الاضافه لايدخل 

ولكن كلامك منطقي وصحيح يبدو هناك مشكله من الجهاز او شبكة الانترنت لدي

اخ عماد شكرا لك والله شرحك وافي وكفيت ووفيت
ماعليه تعبتك معاي هالفتره بالاخطاء والمشاكل اللي تحصل معاي

اتمنى لك التوفيق في حياتك المهنيه والعمليه

وانا راح افيدك بأي شي ينمي اضافتك سواء من مواقع او من افكار 

شكرا، شكرا، شكرا 👊😊

**Comment by emadmahdi** [comment]
جرب الدخول الى موقع اكوام هذا من نفس جهاز الاندرويد الذي بعثت لي اللوج له
https://akoam.net

**Comment by hussapril7** [comment]
حاولت ان ادخل على الموقع عن طريق المتصفح في الجهاز الاندرويد لقد ظهر لي رساله 
Error: Unknown host

ماذا يعني ؟؟؟

**Comment by emadmahdi** [comment]
نفس الخطأ على كودي ... معناه ان جهاز الاندرويد غير قادر على ايجاد سيرفر اكوام ... يعني السيرفر الذي اسمه اكوام هو غير موجود على شبكة الانترنيت

**Comment by hussapril7** [comment]
اوك يعطيك العافيه اخ عماد راح اسوي اللي قلته واشوف 👍

**Comment by emadmahdi** [comment]
سلام عليكم حسين ... التحديث الجديد فيه موقع جديد ومفاجأة جبارة ... المفروض انه سوف يعوضك عن اكوام ... ولكن ان شاء الله يشتغل معك
