### ISSUE TITLE
 موقع ايجي بست 

### ISSUE THREAD

**Issue by Aymahalawa** [emadmahdi/KODI#10]
السلام عليكم أخ عماد ، كل عام وانت بخير.
اولا شكراً علي الاضافه الممتازة بس كنت عايز ابلغ عن مشكلة في موقع ايجي بست مبيفتحش في 
http://egy.unblock.ws  الامارات بس انا 
لقيت الموقع عامل موقع تاني 

هل ممكن تضيف الموقع التاني؟ 
وشكرا مرة تانية

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله
رمضان كريم وكل عام وانتم بخير
لقد قمت بتجربة الموقع ولكن للاسف هذا الموقع لا يعمل بمفرده بدون الموقع القديم وخاصة عند اضافة اسم المستخدم وكلمة السر وهو دائما يحتاج الموقع القديم

جرب ان تستخدمه بالكامل وسوف تلاحظ انه دائما يرجعك الى الموقع القديم
