### ISSUE TITLE
السلام عليكم اخ عماد معاك حسين

### ISSUE THREAD

**Issue by hussapril7** [emadmahdi/KODI#11]
للاسف قبل يومين اغلق موقع ايجي بيست
وللاسف ايضا اغلب المواقع التي داخل مصر اصبحت بها مشاكل

المواقع في برنامجك اصبحت بها بعض الاخطاء 
واعلم ان الخلل من المواقع الرسميه 
ولكن لازال بعض سيرفرات تعمل لابأس بها

 لذلك قمت بالبحث على الانترنت لمدة يومين عن المواقع التي تقدم خدمة الافلام والمسلسلات المترجمه
وهذي هي لستة المواقع

المشفر منها
https://www.faselhd.co/
https://www.dardarkom.tv/
https://www.cimalight.tv/
https://www.movs4u.tv/
https://cimaflix.net/ 
https://filmey.tv/
https://cima4film.net/

والغير مشفر فقط موقع واحد
http://cima4up.co/

اتمنى هذي المواقع قد تفيدك في برنامجك
وانا اذكر في بدايات برنامجك قلت لي اذا كانت هناك مواقع تقدم الافلام والمسلسلات ابعثها لي 

وارجوا ان لاتمسح اي موقع من المواقع السابقه في برنامجك
لان هناك بعض السيرفرات تعمل في بعض المواقع
وربما مع الوقت ترجع المواقع للعمل من جديد

ملاحظه: اخ عماد طبعا تعرف اغلب المواقع تضع اعلانات مزعجه
فا انا استخدم
extensions
 (اضافة مانع اعلانات على (متصفح كروم
اكتب بالبحث 
اسم هذي الاضافة
Pop up blocker for Chrome
التابعه لموقع
https://poperblocker.com
افادتني جدا هذي الاضافه في تصفح مواقع الافلام دون ازعاج

انت مايحتاج ادري اعلم واخبر مني في هذي الامور ولكن قلت قد تفيدك في حال لم يكن لديك

عموما اخ عماد اعتذر عن الاطاله
وشكرا لك 
وبالتوفيق....

**Comment by hussapril7** [comment]
عفوا نسيت

موقع
https://www.movs4u.tv/
لديه موقع اخر للافلام والمسلسلات العربيه
https://www.movs4u-ar.com
لكن يبدوا لي انه جديد اتوقع مع الوقت سيزيد اكثر في وضع المسلسلات والافلام العربيه

انا عن نفسي اتمنى تضيف هذا الموقع بالتحديد الاول والثاني
وبالتحديد الاول 
لان لدية موسوعه كبيره من الافلام والمسلسلات الاجنبيه وأول بأول
والمميز فيه متعدد السيرفرات 
وجودة الفيديو ممتازه 
واحيانا اجد افلام في هذا الموقع ليست موجوده في المواقع الاخرى

وهو البديل بالنسبه لي بعد ايجي بيست

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله
سوف افحص هذه المواقع لاحقا

**Comment by assemhasanin** [comment]
اعتقد ان هذا الموقع يحتوي على مكتبة افلام ضخمة
https://www.cimalight.net/
افلام اجنبي
https://www.cimalight.net/category.php?cat=english-movies
افلام عربي
https://www.cimalight.net/category.php?cat=arabic-movies

**Comment by emadmahdi** [comment]
> اعتقد ان هذا الموقع يحتوي على مكتبة افلام ضخمة
> https://www.cimalight.net/
> افلام اجنبي
> https://www.cimalight.net/category.php?cat=english-movies
> افلام عربي
> https://www.cimalight.net/category.php?cat=arabic-movies

اسف قبل قليل استلمت رسالتك ... هذا الموقع جيد ولكنه يستخدم سيرفرات عامة فقط ... والبرنامج بحاجة الى مواقع تستخدم سيرفرات خاصة مثل موقع ايجي بيست وموقع موفيزلاند والاثنين للأسف توقفوا عن العمل
