### ISSUE TITLE
مشكلة في موقع موفيز لاند

### ISSUE THREAD

**Issue by hussapril7** [emadmahdi/KODI#12]
( هناك مشكلة في موقع المضاف مؤخراً ( موفيز لاند
عندما دخلت على فلم واخترت احد السيرفرات للمشاهده 
علق معي برنامج الكودي مما اضططرت ان الخروج من الكودي والدخول من جديد 

يبدو ان هناك مشاكل في هذا الموقع وبالاضافه انه ليس مشفر

**Comment by emadmahdi** [comment]
انا لا اعلم الغيب ... احتاج تفاصيل اكثر ... مثلا اسم الفيديو الذي طلبته وكيف وصلت اليه وما هو السيرفر الذي اخترته وهل هو عام ام خاص وما هي الدقة التي اخترتها ... احتاج انا بنفسي اشغل نفس الفيديو الذي انت شغلته وبنفس 
 الطريقة لكي احدد ما هي المشكلة بالضبط لان المشكلة قد تكون عندك فقط وليست متكررة مع جميع الناس او مع جميع الفيديوهات

**Comment by emadmahdi** [comment]
جرب الاصدار الاخير 5.0.0 لاني اضفت وظيفة جديدة وهي ارسال سجل الاخطاء ... فقط ادخل الى الفيديو الذي يعمل لك مشكلة ثم بعدها ارسل لي سجل الاخطاء

**Comment by hussapril7** [comment]
خوش فكره 👍
راح احدث ان شاءالله
بس اخ عماد شنو صار على المواقع اللي دزيتهم لك اخر مره ؟؟
متى تضيفهم ؟؟؟

**Comment by emadmahdi** [comment]
لماذا تحتاج مواقع اخرى

**Comment by hussapril7** [comment]
لان كان موقع ايجي بيست السيفرات سريعه وكنت ما اواجهه مشاكل بالبث يعني ماكان يوجد تقطيع بالسيرفرات  
اقصد يعني مشاكل ب
Buffring
ادري عوامل كثيره تسبب هالشي مثل سرعة النت عندي وقوة الجهاز 
بس عندي سرعة نت لابأس بها وجهاز ممتاز 
وكان موقع ايجي بيست السيرفرات قوية وكان يشتغل معي بشكل ممتاز حدا
والمواقع الاخرى في برنامجك ايضا لابأس بها ولكن بعض السيرفرات تكون ضعيفه
واعلم انه من مصادر المواقع تلك المشاكل وليس من برنامجك

لذلك بعد اغلاق موقع ايجي بيست بحثت عن مواقع كثيره وفحصتها بالمتصفح وجدت انها سريعه وجيده
وخصوصا موقع
Movs4u
و
Faselhd
وجدت سيرفرات هذي المواقع ثابته ومتعدده 
وايضا لان بعض الافلام لم اجدها في المواقع اخرى ووجدتها في هذا المواقع 

وايضا المواقع الاخرى التي ارسلتها لك جيده

ولكن هذا الموقعين اراهم بحجم موقع ايجي بيست

ولابأس ان كانت مواقع كثيره في برنامجك اعتقد بأن هذا الشي يتيح للمستخدمين امكانيه البحث اكثر 
وتكون الاضافة شامله كل مواقع الممتازه
 ولا احد يلجأ للمتصفح للبحث عن اي موقع

اعتذر عن الاطاله ولكن هذا ما اتمنى ان اراه في برنامجك
بالاخير القرار لك اخ عماد
وسلامتك

**Comment by emadmahdi** [comment]
بالنسبة لمشكلة ال
buffering
فحاول دائما ان تبتعد عن ملفات ال
m3u8
لان كودي فيه مشكلة وهي انه لا يجمع ولا يحتفظ بال
cache
عندما يتعامل مع ملفات ال
m3u8
حاول دائما ان تستخدم
mp4   او   mpd   او   mkv

 وحاول ايضا ان تبتعد عن ملفات التحميل لانها عادة ابطيء من ملفات المشاهدة لانهم يخططون للتحميل بدون مراعاة لطول وقت التنزيل وايضا عادة لا يسمحون بتنزيل عدة ملفات في وقت واحد او في اوقات متقاربة جدا

الموقعين التي انت ذكرتها هي فقط للفيديوهات الاجنبية ولا يوجد فيها عربي ... اما السيرفرات المستخدمة عندهم فهي عامة فقط عدا موقع فاصل فهم يستخدمون سيرفر خاص ولكنه وحيد وبدقة واحدة وهذا معناه انه يصعب الاعتماد عليهم في المستقبل لانه ممكن ان يصبح السيرفر بطيء بسهولة

اما موقع موفيزلاند فهو موقع جبار وظخم وانا اعتبره افضل موقع موجود في برنامجي لانه يستخدم اكثر من سيرفر خاص ومن شركات اخرى متخصصة في احتواء ملفات الفيديو وفي عدة دول والموقع سريع ومشاكله جدا قليلة وبالاضافة الى  هذا فقد اضفت له سيرفرات عامة رغم ان السيرفرات العامة اتعبتني كثيرا جدا ولكني والحمد لله نجحت باضافتها

اظن اني لن اضيف مواقع اخرى الى البرنامج الى تظهر مشكلة في المواقع الموجودة حاليا

**Comment by hussapril7** [comment]
نعم اخ عماد انا استخدم ملفات 
mp4
وليس
M3u8

وايضا استخدم دائما الجوده
720
لانني اعلم كلما زادت الجوده احتاج الا نت اسرع

بعض المواقع يظهر اسم السيرفرات فقط
 ولا يظهر لي الجودات 

فقط ايجي بيست سابقا كان يتيح لي خيارات الجودات ويوضح ان كانت بصيغة
mp4
او
m3u8

وبخصوص موقع
Movs4u
صحيح يوجد فيه المحتوى الاجنبي 
ولكن ايضا فتح موقع جديد من بداية رمضان في عرض مسلسلات وبرامج رمضان
واعتقد سيستمر في وضع المزيد مستقبلا بالمحتوى العربي
ورابط الموقع الجديد
Movs4u-ar.com
يمكنك ربط الموقعين في البرنامج اذ امكن

عموما اخ عماد لاتوجد مشكله 
واعلم انك تعمل جاهدا لجعل برنامجك مميز ورائع
انا فقط اقترحت عليك لانني رأيت المواقع ممتازه وحبيت ان تكون في برنامجك
ومهما يكون رأيك فأنا معك 
👊

**Comment by emadmahdi** [comment]
موقعهم العربي فارغ ويحتوي فقط على مسلسلات رمضان 2019

وايضا يستخدم فقط سيرفرات خارجية وهي نفس السيرفرات التي تستخدمها بقية المواقع

يعني لا يوجد عندهم شيء جديد في هذ الموقع لكي اضيفه الى برنامجي لا سيرفرات جديدة ولا فيديوهات جديدة

**Comment by hussapril7** [comment]
اوك 👍
