### ISSUE TITLE
بعض المواقع لا تعمل وايجي بيست القديم عاد للعمل

### ISSUE THREAD

**Issue by hussapril7** [emadmahdi/KODI#14]
كيف حالك اخ عماد

حبيب قلبي موقع ايجي بيست اللي حاطة بالبرنامج لايشتغل نهائيا 
وكل ما ادخل فلم يقول هذا الموقع الجديد لايجي بيست!!!

للعلم موقع ايجي بيست الاصلي رد اشتغل من بعد الانقطاع
وخاط رسالة تحذيرية بشأن المواقع الاخرى التي تأخذ نفس اسمة

لذلك اتمنى ان تضع الموقع القديم والاصلي لأيجي بيست 
ورجوا ان يكون شغال مثل السابق 

وملاحظه اخرى اغلب المواقع مثل اكوام، وموفيز لاند، وسيريس فوروتش
عند الدخول تظهر هذي الرساله
- الاسباب: قد تكون الانترنت مفصولة او الروابط المشفرة لاتعملاو الموقع الاصلي غيرنعروف او النوقع غير هذه الصفحة
جرب مسح الكاش او ارسل سجل الاخطاء للمبرمج او جرب الصفحة لاحقا.

هذا محتوى الرساله التي تظهر عند الدخول على المواقع المذكورة في الأعلى

رغم انه النت لدي ممتاز ومسحت الكاش وكل شي تمام

ولكن لا اعلم ماهي المشكلة

اتمنى حلها اخ عماد

واتمنى ايضا ان تعيد موقع ايجي بيست القديم لانه عاد

وبس تسلم 👊

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله
اهلا اخي حسين
بالنسبة لايجي بيست الموقع الذي في البرنامج وايضا الموقع القديم الاثنين لديهم مشكلة في ملفات الفيدو ... الاثنين فقط اسماء الافلام والمسلسلات بدون ملفات فيديو

اما بالنسبة لبقية المواقع فانا لاحظت نوع من المنع على هذه المواقع في مصر ولا اعرف اذا انت في الكويت لديك نفس المشكلة ... حيث انه على المتصفح تظهر لك صفحة تطلب منك قبل الدخول الى الموقع ان تضغط على 
recaptcha
لكي تؤكد انك انسان ولست برنامج كمبيوتر لانهم يمنعون البرامج مثل كودي ان تصل الى هذه المواقع وهذه الصورة هي مثال على الذي يحدث في مصر ولا اعرف اذا كانت لديك نفس المشكلة ام السبب عندك مختلف

![akoam_problem](https://user-images.githubusercontent.com/7454511/61501521-a71a7780-a99d-11e9-8f21-fcf9ab9f6da6.png)

**Comment by emadmahdi** [comment]
واما بالنسبة لايجي بيست فشكرا لاخباري عن الموقع القديم ... سوف اضيفه للبرنامج ... ولكن الموقع الذي في البرنامج وايضا الموقع القديم الاثنين لديهم مشكلة في ملفات الفيديو ... الاثنين يعرضون فقط اسماء الافلام والمسلسلات بدون ملفات فيديو ... هل تعرف ان المواقع في القائمة ادناه كلها هي ايجي بيست ... انا اظن ان الموقع القديم سوف يغلق مرة ثانية لان سيرفراتهم في امريكا وقوانينها متشددة اكثر من مصر وخاصة تجاه حقوق الطبع للافلام الاجنبية وحتى العربية ... الظاهر ان اصحاب الموقع اغبياء او جهلة

https://egy.best
https://egy4best.com
https://egy1.best
https://egybest1.com
https://egybest.vip

**Comment by hussapril7** [comment]
اخ عماد شكرا للتوضيح 

دخلت الى موقع اكوام وواجهتني نفس المشكلة ولكن بشكل اخر 
كأنه لايوجد انترنت لدي 
يعني الصفحة لاتعمل نهائياً ولايوجد اداة 
reCAPTCHA

وبخصوص مواقع ايجي بييست التي ذكرتهم صحيح هذي المواقع تحمل نفس اسم ولكن كلها تعتبر مزيفة فقط لكسب متابعين موقع ايجي بيست الاصلي
فقاموا بتغيير الدوميين لكسب المشاهدات على ما اعتقد

عموماً نتمنى موقع ايجي بيست يعود مثل السابق لانه فعلا كان موقع ممتاز في جودة الافلام وقوة السيرفرات

واخ عماد بخصوص موقع اكوام والمواقع الاخرى التي ذكرتهم في اول الرسالة 

هل يوجد حل لها ام لا ؟؟؟

**Comment by emadmahdi** [comment]
كيف احل مشكلة وانا لا اراها ولا اعرف عنها شيء ... انا عندي اكوام وجميع المواقع تعمل بدون مشاكل ... ولكن في مصر بعض الناس نجحةا عندما استخدموا
vpn
وانا اظن ايضا ممكن ان ينفع 
proxy
ولكن يجب ان تختار سيرفرات في بلد اخر غير بلدك

**Comment by hussapril7** [comment]
ماعليه اخ عماد على بالي تعرف حل المشكلة

بس خلاص راح استخدم 
Vpn

رغم انه يضعف من سرعة النت الاصلية 
ولكن بشوف


وان شاءالله تنحل المشكلة قريباً في جميع المواقع

شكرا لك يالحبيب 👊

**Comment by emadmahdi** [comment]
اخبرني ماذا سوف يحدث بعد ان تستخدم ال
vpn
لكي افهم ما هي المشكلة عسى ولعل استطيع ان اجد لها حل ... المشكلة الثانية هي اني لا اعرف هل يوجد عدد كبير من الناس لديهم نفس المشكلة ام العدد قليل

انا استطيع ان ارى ان الموقع كلها تستخدم بكثرة ولكن لا اعرف في اي بلاد لا تستخدم

**Comment by emadmahdi** [comment]
proxy
لا يقلل السرعة
هناك كثير مجانية على هذا الرابط
http://free-proxy.cz

**Comment by hussapril7** [comment]
اخ عماد جربت استخدم 
VPN
حطيت 
IP 
امريكي
ودخلت المواقع في برنامجك واشتغلت
ودخلت ايضا من المتصفح وفتحت المواقع واشتغلت

هذا يدل انه المواقع لاتشتغل في بلدي الكويت 
/:

لا اعلم اخ عماد
برأيك هل يوجد حل لهذه المشكلة ؟؟؟

**Comment by emadmahdi** [comment]
انا استطيع ان اضيف
proxy
في برنامجي بحيث يعمل اوتوماتيكيا اذا كان هناك منع مثل مصر والكويت ... ولكن اظن انه شيء اكثر بكثير من المطلوب في برنامج مثل برنامجي

**Comment by emadmahdi** [comment]
للعلم ال
proxy
سريع لانه لا يشفر المعلومات قبل الارسال وبعد الاستلام كما يفعل ال
vpn

**Comment by emadmahdi** [comment]
اريد منك ان تطفيء ال
vpn
ثم تحاول تشغيل جميع المواقع التي لا تعمل ثم ارسل لي سجل الأخطاء (موجود في ارسال مشكلة للمبرمج) لكي ادرس وافهم المشكلة التي عندك

**Comment by hussapril7** [comment]
اخ عماد انا سويت اللي قلت لي عليه طفيت 
Vpn

ودخلت الكودي عادي وقبل لا ادخل برنامجك قمت بتنظيف الكاش وتنظيف المعتاد

بعدها دخلت على المواقع التي واجهتي فيها المشاكل 
اللي هي
-موقع موفيز لاند اونلاين
-موقع اكوام
-موقع سيريس فوروتش

وقمت بعدها قائمة الخدمات في برنامجك وضغطت على (ارسال مشكلة للمبرمج) كما قلت لي
ثم ظهرت لي مسجات للموافقه على ارسالها لك 
للتتأكد اني مسحت الكاش والخ....

وايضا كتبت لك رساله اني انا من ارسلت لك 

اتمنى ان تظهر لك المشكلة بوضوح

**Comment by emadmahdi** [comment]
لم يصلني منك اي رسالة
هل انت متأكد انك تستخدم الاصدار الاخير للبرنامج
5.6.0
يجب ان ترى رسالة من البرنامج تقول "تم الارسال بنجاح" والا فان الرسالة لن تصل لي

**Comment by emadmahdi** [comment]
اذا كان لديك مشكلة في الارسال فاذن ابعث لي سجل الاخطاء مع هذه الرسائل ... احتمال كبير ان تجده في هذا المكان
%APPDATA%\Kodi
واسم الملف
kodi.log

**Comment by hussapril7** [comment]
نعم اخ عماد استخدم اخر اصدار 
5.6.0
وعندما رسلت الرساله قال لي تم الارسال على ما اعتقد 🤔

اخ عماد لاحظت شغله غريبة توها صارت
انا عندي برنامج 
Blokada
استخدمة في جهازي
TV Box
واشغل هالبرنامج عندما اريد ان ادخل مواقع الافلام عن طريق المتصفح
لانه يزيل الاعلانات ونادرة مايظهر اعلان
وهو ممتاز 

ولكن الغريب الذي حصل معي
كنت مشغل البرنامج ودخلت برنامج الكودي لكي ادخل المواقع في برنامج وارسل لك ملف كودي لوق
عندما دخلت موقع موفيز لاند دخل 
🤔
بعدها دخلتةموقع اكوام 
وموقع سيريس فوروتش
ايضا دخل معي 🤔
فا استغربت هل عاد الموقع واشتغل 

بعدها تذكرت انه برنامج 
Blokada
شغال عندي

فا رحت وطفيت البرنامج

بعدها خرجت من برنامج الكودي ودخلت مره اخرى 
ودخلت المواقع مره اخرى 
وظهر لي نفس المشكلة انه لاتعمل و و و كما اخبرتك امس 


وذهبت بعدها شغلت برنامج 
Blokada

ورجعت للكودي واشتغلت المواقع!!!
😊

لا اعلم اخ عماد ولكن وجدت برنامج 
Blokada 
مفيد بالمتصفح وايضا في برنامج كودي

وبخصوص ملف 
Kodi.log
سوف ارسله لك الان بمرفق الرساله

وايضا سأرسل لك صورتين من برنامج 
Blokada
يظهر فيها شكل البرنامج والاصدار الذي استخدمة

[kodi.log](https://github.com/emadmahdi/KODI/files/3413946/kodi.log)

![20190720_221139](https://user-images.githubusercontent.com/44403403/61583410-411a2580-ab40-11e9-9b99-0f5e69a4da12.jpg)

![20190720_221219](https://user-images.githubusercontent.com/44403403/61583420-5db65d80-ab40-11e9-9d08-b955fd466ce5.jpg)

**Comment by emadmahdi** [comment]
اخي حسين ... المشكلة عندك ليست مثل مشكلة مصر ... المشكلة عندك هي في الحصول على رقم
IP
للمواقع وهذه المشكلة اما من الرواتر او من شركة الانترنيت الخاصة بك او من برامج موجودة على جهازك ... والحل جدا بسيط وهو ان تستخدم
DNS
مختلف عن الذي موجود حاليا عندك ... والظاهر ان برنامج منع الاعلانات الذي تتكلم عنه يقوم بتغيير ال
DNS
وايضا يقوم بعمل فلتر للارقام التي تعجبه والارقام التي لا تعجبه


ال
DNS
هو مجرد سيرفر وظيفته ان يترجم اسم المواقع الى ارقام وهذا الرقم يسمى
IP address
وهذا السيرفر ضروري لان جميع الشبكات في العالم تتعامل بالارقام وليس بالاسماء

**Comment by emadmahdi** [comment]
جوجل لديها سيرفرات
DNS
مجانية ومتوفرة للعالم كله وهذه هي ارقامها
8.8.8.8
8.8.4.4
سوف افحصها واخبرك اذا كانت تعمل مع جميع مواقع برنامجي او لا

**Comment by hussapril7** [comment]
انزبن اخ عماد اشلون اغير  
DNS

انا عندي جهاز 
Tv box 

هل تعرف اين اذهب لتغيير 
DNS

**Comment by hussapril7** [comment]
حسنا اخ عماد بانتظارك

**Comment by emadmahdi** [comment]
اعطني كم دقيقة

**Comment by emadmahdi** [comment]
سيرفرات جوجل شغالة بدون مشاكل ... وبالمناسبة
vpn  و   proxy
ايضا يغيرون سيرفر الارقام

اما عن جهازك ال
tv box
فللاسف كل جهاز يختلف عن غيره ولكن بشكل عام يجب ان تدخل الى اعدادت الشبكة ثم تبحث عن الطريقة التي انت تسخدمها مثلا هل هي 
wifi    او    ethernet
ثم تغير الاعدادت حسب الذي موجود عندك

الطريقة الاسهل لهذا الموضوع هو ان تغير اعدادات الراوتر لان هذا سوف يغير سيرفر الارقام لجميع البيت عندك وليس فقط على جهاز واحد

**Comment by emadmahdi** [comment]
اذا كان جهازك اندرويد فاظن بسهولة تستطيع ان تبحث عن فيديوها تعلمك طريقة تغير سيرفر ال 
DNS
او ابحث في جوجل ... وايضا احتمال تجد برامج اندرويد تستطيع تغيير سيرفر الارقام لك بسهولة

**Comment by emadmahdi** [comment]
جرب مثلا هذا البرنامج
DNS Changer

**Comment by emadmahdi** [comment]
المنع عن طريق ال
DNS
هي طريقة قديمة وتافهة لانها تعمل بهذه الطريقة وهي ... عندما تطلب انت اسم الموقع يقوم سيرفر الارقام بارجاع جواب لك وهذا الجواب هو ... اما يجيبك برقم مختلف ولا علاقة له بالموقع الذي انت طلبته ... واما يقول لك انه لا يوجد هكذا اسم موقع في الانترنيت

**Comment by hussapril7** [comment]
شكرا اخ عماد اذا سوف ابحث عن تغيير 
DNS 
بالراوتر 

او 
Tv box

وكل شي سهل ان شاءالله ان كنت اريد ان اعرف اكثر سوف ابحث باليوتيوب 
👊😊

**Comment by emadmahdi** [comment]
المنع عن طريق ال
DNS
هي طريقة قديمة وتافهة لانها تعمل بهذه الطريقة وهي ... عندما تطلب انت اسم الموقع يقوم سيرفر الارقام بارجاع جواب لك وهذا الجواب هو ... اما يجيبك برقم مختلف ولا علاقة له بالموقع الذي انت طلبته ... واما يقول لك انه لا يوجد هكذا اسم موقع في الانترنيت

ولهذا عندما تغير سيرفر الارقام فان السيرفر الجديد هو المسؤول عن ترجمة اسماء المواقع وسيرفر شركتك لن يستطيع ان يعطيك اي خطا ... ولكن شركتك ممكن ان تمنعك عن طريق فلتر يضعوه في الشبكة بحيث لا يسمحون للناس باستخدام سيرفر ارقام غير السيرفر الذي هم يختاروه لك

**Comment by hussapril7** [comment]
امممم 🤔
معلومة ممتازة وواضحة 

سألت اخي قبل دقيقه عن موضوع 
DNS

قال انه مره من المرات قام بتحميل لعبة في جهاز 
PS4

ويواجهه خطأ بالتحميل 

بعدها قام بتغيير 
DNS
الي سيرفرات قوقل
اللي ذكرتهم فوق 

ويقول اشتغل التحميل


فا اعتقد سيرفرات قوقل قد تشتغل اذا وضعتها على جهازي او الراوتر

اذا اشتغلت سأخبرك لاحقا 👊👊

شكرا اخ عماد لجهدك ومعلوماتك التي افدتني بها
جد اشكرك 👊⚘

**Comment by emadmahdi** [comment]
اريد منك ان تجرب ارسال سجل الاخطاء مرة اخرى ... لاني لا افهم لماذا لم يستطيع جهازك ارسال السجل لي ؟

**Comment by emadmahdi** [comment]
شكرا ... استملت منك الرسالة

**Comment by hussapril7** [comment]
لا اخ عماد ليس لدي برنامج يمنع المواقع الاباحية او اي شي من هذا القبيل


وبخصوص الرساله التي طلبتها ان ارسلها لك عن طريق برنامجك 
لقد ارسلت الان رساله

**Comment by hussapril7** [comment]
حسنا شيء جيد انه وصلت 👊👊👊

**Comment by emadmahdi** [comment]
جرب الاصدار الجديد 5.7.0
اضفت وظيفة لفحص المواقع مع البروكسي وبدون بروكسي

**Comment by hussapril7** [comment]
اخ عماد اولا اشكرك من كل قلبي على برنامجك الخيالي، والله جد كل مره انبهر من ترتيبك وتنسيقك لبرنامجك والله جد جهد جبااااااار ومن كثر ما انت ابدعت بشغلك قعد تخليني احب لغة البرمجة 👊

عموما يالحبيب انا حدثت على اخر تحديث قلته
5.7.0

وسويت فحص المواقع اللي ماتشتغل وقال مسج ثاني اختار سيرفر بروكسي من الدول اللي انت حطيتهم 
وجربت كذا دولة مثل فرنسا وامريكا واليونان بس للاسف ما اشتغل موقع اكوام ولا موفيزلاند ولا سيريس فور وتش

مادري هل مواقع البروكسي اللي حطيتهم فيهم مشكلة او  هناك خطأ لا اعلم فيه

اخ عماد تقدر تضيف برنامج
Blokada 
داخل برنامجك؟؟

لان مثل ماقلت لك سابقا هالبرنامج من اشغلة تشتغل المواقع

فمادري هل بلغة البرمجة تقدر تضيف نظام البرنامج في برنامجك


بس والله بشكل عام بغض النظر اذا المواقع تشتغل ولا لا 
انا سعيد في برنامج وبالتطور الكبير فيها 
جد تسلم ايدك 

![20190727_000447](https://user-images.githubusercontent.com/44403403/61981873-a3bd6680-b003-11e9-9a02-00c37d655136.jpg)

**Comment by emadmahdi** [comment]
حدث الى اخر اصدار ... 5.7.1 ... وابعث لي صورة قائمة البروكسي (فقط السيرفرات التي فوق) ثم جرب استخدام البروكسي الاول في القائمة الذي هو اقل رقم بالوقت ... هذا الرقم هو الوقت الذي يحتاجه البروكسي لكي يجلب لك صفحة الانترنيت ... ولهذا من يكون الرقم اصغر معناه انه يجلب لك الصفحة اسرع ثم ارسل لي صورة نتيجة الفحص ... واذا وجدت مواقع لا تعمل فاذن جرب بروكسي غيره لان هناك بعض البروكسيات قد لا تعمل بصورة صحيحة والقائمة التي تظهر لك انا فحصت كل بروكسي وايضا البرنامج يقوم بفحص كل بروكسي على جهازك قبل ان يعرض قائمة البروكسي

**Comment by emadmahdi** [comment]
ولا تتفاجأ اذا تغير ترتيب البروكسي في القائمة لانه يعتمد على سرعة السيرفر وسرعة الانترنيت ومجموع عدد الناس الذين يستخدمون البروكسي في تلك اللحظة ... وحتى ممكن ان يختفي بروكسي من القائمة لانها مجانية وغير متوفرة دائما رغم اني اخترت افضل واسرع سيرفرات وجدتها في الانترنيت

**Comment by hussapril7** [comment]
حدثت لاخر اصدار 
5.7.1

وعملت نفس ما قلت لي واخترت البروكسي الاول
وحاولت ادخل موقع اكوام بعد ذلك ولكن نفس النتيجة لا يدخل
وسويت بحث مره اخرى عن بروكسي وجربت كذا مره ولم تنفع النتيجة 

وهذي الصور اختياري للبروكسي ونتيجة الفحص

![20190727_022321](https://user-images.githubusercontent.com/44403403/61986436-cb1e2e80-b017-11e9-802a-3073ceaaeec9.jpg)

![20190727_022107](https://user-images.githubusercontent.com/44403403/61986450-d709f080-b017-11e9-8982-d5b10a8663fa.jpg)

**Comment by emadmahdi** [comment]
الظاهر انك لم تقرأ الصفحة التي قبل الفحص

ارجوك ارجع واقرا كلشي مكتوب من البداية

**Comment by hussapril7** [comment]
اخ عماد قرأت كل شي وامشي على التعليمات التي تكتبها في الرسائل المنبثقه

وسأرسل لك الان صور لكل خطوه خطوه قمت بها 
من اول شي دخلت موقع اكوام الى النهاية

 وعند اخر صورة خرجت من الرساله ثم ضغطت على موقع اكوام تظهر لي مثل اول رساله 
يعني اعود من جديد على نفس الخطوات وهكذا

![20190727_030916](https://user-images.githubusercontent.com/44403403/61987113-952f7900-b01c-11e9-8a56-671064f29e08.jpg)

![20190727_030950](https://user-images.githubusercontent.com/44403403/61987125-a5dfef00-b01c-11e9-85ad-6fa643f70ef9.jpg)

![20190727_030958](https://user-images.githubusercontent.com/44403403/61987135-b4c6a180-b01c-11e9-82c2-12665af9a859.jpg)

![20190727_031013](https://user-images.githubusercontent.com/44403403/61987140-c27c2700-b01c-11e9-8acf-258f4ad8211f.jpg)

![20190727_031022](https://user-images.githubusercontent.com/44403403/61987155-d4f66080-b01c-11e9-9672-7335271f92f3.jpg)

![20190727_031038](https://user-images.githubusercontent.com/44403403/61987165-e5a6d680-b01c-11e9-99e4-49d8846bc9d2.jpg)

![20190727_031047](https://user-images.githubusercontent.com/44403403/61987169-f5261f80-b01c-11e9-9047-6314d0ba2578.jpg)

![20190727_031142](https://user-images.githubusercontent.com/44403403/61987173-01aa7800-b01d-11e9-80eb-5ae1aae67cd0.jpg)

**Comment by emadmahdi** [comment]
اخي حسين الغرض من الفحص ليس اصلاح جهازك واصلاح شبكتك واصلاح الكودي واصلاح الانترنيت عندك .... وانما الغرض منه هو فقط لكي تعرف هل المشكلة من طرفك ام من البرنامج ... والفحص ايضا يقول انك لو استخدمت بروكسي فان جميع المواقع عندك سوف تعمل بدون مشاكل

 والرسالة في البداية جدا واضحة وتقول انك تحتاج اما بروكسي او في بي ان او دي ان اس لكي تحل المشكلة

بالمناسبة كودي يسمح لك باضافة بروكسي بسهولة من الاعدادت ... فقط غير الاعدادت ثم  اطفي كودي وارجع شغله من جديد

**Comment by emadmahdi** [comment]
وايضا عندك حل ال
dns
لماذا لم تعمله ... الحل لجهازك جدا سهل ... فقط ابحث في الاعدادات (في الراوتر او في جهازك) وغير رقم سيرفر ال دي ان اس الى الارقام التي اعطيتك في الرسائل السابقة

**Comment by emadmahdi** [comment]
انا استطيع ان اضيف البروكسي الى برنامجي بسهولة ولكن هذا سوف يعمل كارثة حتى للمواقع التي تعمل لانها ببساطة سوف تصبح جميعها بطيئة ... والفحص عندك يقول ان كل طلب انت تطلبه بواسطة البروكسي سوف يكلفك تقريبا ثانيتن او اكثر لهذا انا لا اريد ان اتدخل في حل المشكلة وانما فقط اعطي الحل ... ولعلمك اذا اضفت انت البروكسي الى كودي فان جميع برامج كودي سوف تصبح بطيئة وليس فقط برنامجي الذي سوف يصبح بطيء

ولكن لو انت حليت مشكلتك باستخدام دي ان اس مختلف فهذا سوف يسرع من الانترنيت عندك على جميع برامج الكودي وجميع برامج الجهاز ... اما اذا غيرت ال دي ان اس على الراوتر فان جميع من في بيتك سوف تزداد سرعة الانترنيت عندهم بما فيهم جهاز الكودي عندك

**Comment by hussapril7** [comment]
مادري اخ عماد على بالي انه هذي الطريقة هي حل للمشكلة

ولكن خلاص سأعمل على موضوع تغيير 
Dns

وسوف اضع ارقام قوقل التي ارسلتها سابقا 

وان شاءالله خير

**Comment by emadmahdi** [comment]
انا لم اكتب في اي مكان اني سوف احل مشكلة الناس جميعها ... الرسائل في البرنامج كلها تتكلم عن فحص المشاكل وطرق حل المشاكل وليس عن القيام بحل المشاكل

**Comment by hussapril7** [comment]
صح كلامك، خلص اخ عماد انت كفييت ووفييت
وبرنامجك اراه من احسن مايكون عن السابق 
وفعلا يوم عن يوم تتطور اكثر وتبدع فيها


وبخصوص مشكلة المواقع هي مشكلتها في بلدي او من شبكة الاتصالات الخاصه بي
ولكن سوف احل المشكلة بتغيير 
DNS

وبس شكرا لك اخ عماد على وقتك وجهدك 
ماعليه تعبتك معاي هالفترة بهذي المشكلة 
بس يلا ماعليه الله يقويك ويعينك
تسلم يالحبيب وانتظار كل جديد في برنامجك
⚘👊

**Comment by emadmahdi** [comment]
الشكر لله اخي حسين

**Comment by emadmahdi** [comment]
السلام عليكم حسين لقد وضعت 
DNS
تجريبي في البرنامج وهو يعمل اوتوماتيكيا ... اريد منك ان تجرب المواقع التي كان فيها مشكلة وتخبرني اذا تغير شيء معك

**Comment by hussapril7** [comment]
اخ عماد انت بطل والله 
دخل على جميع المواقع اشتغلوا باستثناء موقع سيريس فور ووتش
ظهر لي هذا المسج
Error 1: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake faiure (_ssl.c:726)


وهناك خطأ اخر في موقع اكوام
من اختار الفلم واختار السيرفرات ولا سيرفر يشتغل وجربت على كذا فلم
مثال فلم 
Venom  2018
Avengers: Endgame 2019
ولم يشتغلوا

فمادري هل المشكلة بالموقع او من البرنامج

بس عالعمووم انا فرحت والله من اشتغلت المواقع 

وفعلا ابهرتني اخ عماد
ماشاءالله عليك

**Comment by emadmahdi** [comment]
هذه كانت فقط للتجربة لكي اتأكد ان هذا الحل سوف يحل مشكلتك ... وانا اعرف بعض الروابط قد لا تعمل لاني تقريبا انجزت ثلاثة ارباع الشغل وباقي الربع الاخير لم اعمله

المهم هل هناك فرق بالسرعة ... لاني عملته بطريقة انه اذا وجد البرنامج مشكلة في الاتصال بالموقع فالبرنامج اوتوماتيكيا يغير ال
DNS
ويحاول الربط مرة اخرى ... يعني كل طلب انت تعمله سوف يحاول البرنامج الربط مرتين

**Comment by hussapril7** [comment]
اهلا بالحبيب
 بخصوص الفرق بالسرعه لا لم اجد فرق 

اصلا برنامجك اصبح ذكي وسلس اكثر عن السابق بنظري

الصراحة ابدعت اخ عماد والله من قلب اقولها
يعني برنامجك صار مميزه وكل شي يوضحة عالشاشه اي خطأ او اي مشكلة يشرحها لنا
يعني احس برنامج صار ذكي 
كأني اتعامل مع شخص معاي يكلمني ويعلمني
يعني اذكر قبل اي خطأ يصير بس يطلع صوت ومانعرف شنو الخطأ
اما الان كا مثال اي فيلم لايشتغل يقول جرب سيرفر اخر 
واذا في خطأه يقول هل تريد ايصال المشكلة للمبرمج
وغيره من مميزات وخدمات مثل تنظيف الكاش وغيرهم
يعني في تنسيق وترتيب وتعليمات بشكل مبهر 

والله لمساتك واضحة عالبرنامج ومبين شغل متعوب عليه 
الصراحة اخ عماد برنامجك تطور بشكل كبير جدا ماشاءالله
وحبيت لغة البرمجة منك

انا قبل كنت اتمنى في مطورين عرب يهتمون باضافات عربيه على الكودي 
قبل كانت اضافة شاهد واضافة هشام وكانت قلة اضافات وبعدين وقفوا للاسف

بس انت ماشاءالله اضافتك صارت شامله بكل شي 
ومن زمان تشتغل عليها اكثر واكثر

عموما اخ عماد استمر يابطل وربي يوفقك 
وكل تعبك راح يثمر بيوم 

انا بانتظار كل تعديل تسوية 
وأي مشاكل او اخطاء تحصل في برنامجك سأبلغك
⚘👊

**Comment by emadmahdi** [comment]
شكرا لك اخي حسين ... والاصدار القادم ان شاء الله سيكون فيه بقية التغيير لل
DNS

**Comment by emadmahdi** [comment]
السلام عليكم
هل تعرف اني صارلي ثلاثة ايام اكتب بروكسي خاص لكودي لكي يحل مشكلتك لان كودي لا يسمح بتغيير ال
DNS
الخاص بملفات الفيديو وفقط يسمح لصفحات الانترنيت بهذا التغيير ... يعني انت ممكن بسهولة ان ترى جميع المواقع المحجوبة ولكن لا تستطيع نهائيا تشغيل اي فيديو من هذه المواقع ... هذا مع كودي ولكن مع البروكسي الجديد فان جميع طلباتك للانترنيت سوف تعمل بدون مشاكل بما فيها طلبات ملفات الفيديو

قبل قليل فقط انتهيت من هذا البروكسي ولم اجربه مع كودي ولا مع برنامجي لحد الان

**Comment by hussapril7** [comment]
جزاك الله خير اخ عماد 

ادري تعبت وايد عشان تحل مشكلتي

بس ربي يعوض تعبك بكل خير يارب 

انا عارف مشكلة 
DNS 
 معقده

ولكن اثق بقدراتك في هذا المجال 

عموما يالحبيب عافاك الله 
وبانتظار التحديث 
وان شاءالله يكون شغال وتنحل هذي المشكله
👊
