### ISSUE TITLE
ERROR: Playlist Player: skipping unplayable

### ISSUE THREAD

**Issue by khidr82** [emadmahdi/KODI#15]
السلام عليكم 
مجهود رائع فى هذا البرنامج اود اولا ان اشكرك عليه 
ثانيا 
لدى مشكلة ظهرت عند محاولة تشغيل اى فيديو من موقع 
EGB
و تظهر فى تقرير الاخطاء كالتالى 

`
            Label:[ ,EGB الاكثر مشاهدة هذا الاسبوع ]
                               Path:[ plugin://plugin.video.arabicvideos/?mode=122&page=1&url=https://www.egy.best/trending/week ]
2019-08-02 14:56:30.792 T:4940  NOTICE: [ plugin.video.arabicvideos ]
                               Version:[ 5.7.2 ]
                               Kodi:[ 18.2 Git:20190422-f2643566d0 ]
                               Label:[  EGB Avengers: Endgame (2019) ]
                               Path:[ plugin://plugin.video.arabicvideos/?mode=123&url=https://www.egy.best/movie/avengers-endgame-2019/?ref=trends-p1 ]
2019-08-02 14:56:35.887 T:4936   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.arabicvideos/?mode=123&url=https://www.egy.best/movie/avengers-endgame-2019/%3Fref%3Dtrends-p1]

`

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله
موقع
http://egy.best
وايضا موقع 
http://egy4best.com
غير جاهزة واذا دخلت عليهم بنفسك عن طريق المتصفح فسوف ترى انه لا توجد ملفات فيديو والموجود هو فقط اسماء وعناوين واما ملفات الفيديو فالموجود منها شيء جدا بسيط ولا استطيع اضافته الان لاني اعرف انه لا ينطبق على جميع الفيديوهات

 سؤال: لماذا لم ترسل سجل الاخطاء عن طريق البرنامج؟ هل هناك مشكلة من البرنامج في ارسال سجل الاخطاء؟

طريقة التواصل عن طريق ال
github
هي الافضل لي وانا اشكرك على الرسالة ولكني احتاج ان اعرف اذا كانت هناك مشكلة في ارسال سجل الاخطاء لكي اقوم باصلاح المشكلة

والسلام

**Comment by emadmahdi** [comment]
استلمت منك سجل الاخطاء ... انا اسف ... السبب هو اني قرأت ايميل ال
github
قبل ان اقرأ الايميل الذي فيه سجل الاخطاء

**Comment by khidr82** [comment]
عزيزى السيد / عماد
شكرا جزيلا لاهتمامكم 

الصورة التالية من الموقع و بها نفس الفيديو يعمل 
و تم تجربة اكثر من فيديو يعمل بالفعل على الموقع و لا يعمل فى البرنامج 

يرجى فحص المشكلة و ابلاغى فى حالة ان المشكلة من طرفى 
مع العلم اننى قمت بالتجرية مرة على جهاز حاسب الى بنظام تشغيل ويندوز 10 و جهاز اخر بنظام تشغيل ويدوز7 
و موبايل بنظام تشغيل اندرويد و نفس المشكلة 

![image](https://user-images.githubusercontent.com/36438188/62382562-1c657b00-b54e-11e9-9e38-13c34ad6c2db.png)

**Comment by emadmahdi** [comment]
غريب انا لا يظهر عندي اي شيء ... اريد ان اعرف كيف وصلت للفيديو وكيف شغلته ... هل ممكن ان تعمل لي فيديو تبدأ من الصفحة الرئيسية الى ان تشغل الفيديو

الصورة الملحقة هي التي يحدث عندي
![egybest](https://user-images.githubusercontent.com/7454511/62383858-d218d580-b51e-11e9-925d-e0e382f965a5.png)

**Comment by emadmahdi** [comment]
وايضا اريد اعرف في اي بلد انت وهل تستخدم 
vpn  او  proxy
لان احتمال يكون عندي حجب في بلدي

**Comment by emadmahdi** [comment]
شكرا ... لا احتاج منك فيديو ... اشتغل عندي بعد ان استخدمت بروكسي في جمهورية مصر

**Comment by khidr82** [comment]
انا من مصر 
لا استخدم VPN or Proxy
جارى تجهيز الفيديو

**Comment by emadmahdi** [comment]
شكرا ... لا احتاج منك فيديو ... اشتغل عندي بعد ان استخدمت بروكسي في جمهورية مصر

المشكلة الان كيف اضيف فيديوهات ايجي بيست وهو محجوب عندي ولا استطيع رؤية الفيديوهات

**Comment by khidr82** [comment]
تمام رأيت تعليقك الان 
و عرفت انكم لستم فى حاجة الى فيديو
اذا فى امكانى مساعدتكم او فى حاله احتجتم ان اقوم بارسال اى شىء يظهر لدى يرجى ابلاغى

**Comment by khidr82** [comment]
ملحوظة : 
اسم الموقع الذى يعمل فعليا 
http://www.egy.best
وليس 
http://egy.best

**Comment by emadmahdi** [comment]
احتاج ان افكر في حل ... لان البروكسي ليس حل مناسب في هكذا حالات ... والغريب ان موقع ايجي بيست الثاني ايضا اشتغل معي باستخدام بروكسي في مصر

**Comment by emadmahdi** [comment]
هل موقع اكوام يعمل معك في مصر ؟

**Comment by khidr82** [comment]
نعم موقع اكوام يعمل لدى فى مصر 
باستخدام الرابط التالى
https://we.akoam.net/

و موقع ايجى بست يعمل باستخدام الرابط التالى 
https://www.egy.best/

و لكن الرابط 
https://egy.best/
لا يعمل

![image](https://user-images.githubusercontent.com/36438188/62386657-cfd36d00-b558-11e9-862b-0ae2a7d3e361.png)

**Comment by emadmahdi** [comment]
المشكلة ليست في رابط ايجي بيست لانه اوتوماتيكيا يتحول من عنوان الى عنوان اخر وهذه ليست مشكلة عندي لاني استخدم العنوان الاصلي والسبب هو اني لاحظت ان بعض المواقع مثل اكوام تقوم دائما بتغيير عنوان موقعها

المشكلة في ايجي بيست هو موقع ملفات الفيديو وليس موقع ايجي بيست ... هذا الرابط في الاسفل هو موقع 
 ملفات الفيديو والذي للاسف لا يعمل في قارة اوربا ولا يعمل في قارة امريكا الشمالية ولكنه يعمل في قارة افريقيا
https://vidstream.top

**Comment by khidr82** [comment]
هل فى الامكان تعديل البرنامج ليتوافق مع

**Comment by emadmahdi** [comment]
كيف عرفت ان معظم المستخدمين في افريقيا ؟

**Comment by khidr82** [comment]
لان معظم الدول العربية متمركزة فى افريقيا و اسيا :)
و البرنامج موجه للمتحدثين باللغة العربية

**Comment by emadmahdi** [comment]
للاسف انت مخطيء ... لان العرب بشكل عام لديهم الستالايت ولهذا اكثر مستخدمي البرنامج هم من الدول الغير 
 ... عربية ... والصورة الملحقة هي حقيقة استخدام برنامجي ... واللون الغامق هو الاكثرية واللون الفاتح هو الاقلية والصورة تقول بوضوح ان الاكثرية هم من امريكا وكندا واستراليا والمانيا والسعودية


![world usage](https://user-images.githubusercontent.com/7454511/62387710-64be7200-b529-11e9-904e-f69c046d54b5.png)

**Comment by khidr82** [comment]
تمام وصلتنى هذه المعلومة شكرا للتوضيح 
القصد هو ان يتوافق كود البرنامج مع فيديوهات هذا الموقع 
و بالتالى يكون البرنامج مكتمل 
و بعدها يتم التفكير فى حل مشكلة الحجب 

اتمنى لك التوفيق

**Comment by emadmahdi** [comment]
المشكلة كيف اضيف فيديوهات ايجي بيست وهو محجوب عندي ولا استطيع حتى الدخول الى موقع الفيديوهات

احتاج ان افكر في حل ... لان البروكسي ليس حل مناسب في هكذا حالات وخاصة ان البروكسيات في مصر بطيئة

**Comment by khidr82** [comment]
بالتوفيق ان شاء الله
و اذا احتجت مساعده فى ارسال اى صفحات او نسخ اكواد من الموقع  لك انا مستعد

**Comment by emadmahdi** [comment]
شكرا لك ... ولكني احتاج بعض الوقت لكي افكر في المشكلة

**Comment by khidr82** [comment]
اتمنى لكم التوفيق

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله وبركاته
يرجى الدخول الى الرابط الاول في قائمة برنامجي

1.  لماذا لا تعمل جميع المواقع

**Comment by khidr82** [comment]
بالفعل دخلت عليها ووجدت انك تطلب اسم البلد و المواقع

مصر
موقع ايجى بست

مع العلم ان الرسالة التى تظهر فى ال 
Log
هى
'
plugin.video.arabicvideos ]:   Resolving Failed   URL:[ https://vidstream.top/embed/XJAKxdk5FB/?vclid=953efe3c0849c89b31e0114643f2858dd4c5ad034464e2ecdece8bedzlllsxWdlslElsmmmlRPMMslnfpaqlsEslsWQUlslElsqWQRGxlMwOzslh ]
2019-08-05 03:59:14.319 T:19256  NOTICE:

'
بالرغم من ان هذا المسار يعمل لدى على المتصفح العادى

**Comment by khidr82** [comment]
![image](https://user-images.githubusercontent.com/36438188/62433862-7aed4d80-b736-11e9-9a8f-b3d02acccb21.png)

**Comment by emadmahdi** [comment]
انا لا استطيع الدخول لهذا الموقع فكيف تتوقع مني ان اجد الرابط لملف الفيديو لكي اضيفه الى برنامجي
https://vidstream.top

  اذا تقدر ترسل لي صفحة ال 
html
 التي فيها رابط ملف الفيديو لكي استطيع ان اضيفه للبرنامج وقبل ان ترسله تأكد ان فيه بداخله رابط ملف الفيديو ويجب ان يكون الرابط واحد او اكثر من هذه الانواع
mp4    m3u8    flv    mpd

**Comment by emadmahdi** [comment]
هذا الذي يظهر عندي
![vidstream](https://user-images.githubusercontent.com/7454511/62434185-98ee8a00-b705-11e9-9a77-afc9e42c07a0.png)

**Comment by khidr82** [comment]
عند الدخول الى الموقع 
![image](https://user-images.githubusercontent.com/36438188/62434465-ae30dc00-b738-11e9-9422-ccc7364a8c16.png)

و الضغط على مشاهدة 
يظهر الصفحة التالية : 



و بها كود الفيديو التالى 

![image](https://user-images.githubusercontent.com/36438188/62434529-ec2e0000-b738-11e9-8ee9-37482500fa91.png)


`
<source src="https://a4-mv5-s-n1vb.vidstream.top/watch/cbd84c854db663a1nhe8131Rsiulr-Miv.uri717d-7JhfAQkBguoxmA__.Ritpd2JPb0tlV1RBOXJza0UycVZUNWhMYjlzY0dvM003aEpJeUNTRm5QVmRPK1ROVjdOSEpFeXFZWVUwNVJPRXNTSUhWQlovcTlEeHFyQUtraFc0RmFtdGRtN2IwN1UrVEgvQS8xaENjQm5GOHZOSEhDUDB3c3hsRG1OSksxdEd1M3U1MDNOdWVRYTA0WWNVNSt4Znd4ckdKOXh6SHozb1A5ZTdMeUhtdzhlUlRZdk9EdlA2NkJjQmZjbHBKUUovZ1BTYkRpM3VmV3FNbkMrdjJta3lFbEtjSE9GTFU5M0dxaWZXVmJNWTV3QnBxaDN4NnFtZHhZelFBVVNyN2hmaGh4TzJqMXJmR2NXK0xDRDdINVZGVnpJa2RRaUJSdjVVWDNKZ1R5MFhvTlVSZG5XQ3N1NlFCdE8zUlpoNUpxZ1JFQ09FR016SmxCTkNWcndpUi9vYWlOS0pSS0xDdzRMTHVod1ZkRnRY/[EgyBest].Avengers.Endgame.2019.BluRay.720p.x264.mp4" type="video/mp4">

`

**Comment by khidr82** [comment]
`<source` src="https://a4-mv5-s-n1vb.vidstream.top/watch/cbd84c854db663a1nhe8131Rsiulr-Miv.uri717d-7JhfAQkBguoxmA__.Ritpd2JPb0tlV1RBOXJza0UycVZUNWhMYjlzY0dvM003aEpJeUNTRm5QVmRPK1ROVjdOSEpFeXFZWVUwNVJPRXNTSUhWQlovcTlEeHFyQUtraFc0RmFtdGRtN2IwN1UrVEgvQS8xaENjQm5GOHZOSEhDUDB3c3hsRG1OSksxdEd1M3U1MDNOdWVRYTA0WWNVNSt4Znd4ckdKOXh6SHozb1A5ZTdMeUhtdzhlUlRZdk9EdlA2NkJjQmZjbHBKUUovZ1BTYkRpM3VmV3FNbkMrdjJta3lFbEtjSE9GTFU5M0dxaWZXVmJNWTV3QnBxaDN4NnFtZHhZelFBVVNyN2hmaGh4TzJqMXJmR2NXK0xDRDdINVZGVnpJa2RRaUJSdjVVWDNKZ1R5MFhvTlVSZG5XQ3N1NlFCdE8zUlpoNUpxZ1JFQ09FR016SmxCTkNWcndpUi9vYWlOS0pSS0xDdzRMTHVod1ZkRnRY/[EgyBest].Avengers.Endgame.2019.BluRay.720p.x264.mp4" type="video/mp4">``

**Comment by emadmahdi** [comment]
انا وجدت حل لجميع المواقع الا هذا الموقع لانهم لا يستخدمون العائق وانما يغيرون صفحاتهم حسب بلد الزائر لموقعهم

الكود الذي انت بعثته غير كافي ... انا احتاج ان اعرف كيف اضاف السيرفر هذا الرابط الى الصفحة (اقصد ماذا تم ارساله من المتصفح الى السيرفر لكي يقوم السيرفر بانتاج هذه الصفحة) وايضا احتاج الصفحة كاملة وليس جزء الرابط فقط وايضا احتاج عنوان هذه الصفحة واين ظهرت بالضبط

**Comment by emadmahdi** [comment]
اذا تريد تساعدني ... ابحث لي عن بروكسي في دولة مسموح لها ان تزور هذا الموقع
https://vidstream.top
انا جربت بروكسي في مصر اسوان البارحة ولكنه اليوم توقف عن العمل
انا جربت بروكسي في الهند واروبا وامريكا واليابان واستراليا وغيرهم ولم اجد حل لهذا الموقع

**Comment by khidr82** [comment]
هذه نسخ لكود الصفحات 
و سوف احاول العثور على بروكسى من مصر و ان شاء الله اجد المطلوب
[egy-best.txt](https://github.com/emadmahdi/KODI/files/3465743/egy-best.txt)
[Vidstream.txt](https://github.com/emadmahdi/KODI/files/3465751/Vidstream.txt)

**Comment by khidr82** [comment]
عزيزى السيد عماد 

بعد التجربة باستخدام 
Epic proxy 
او 
Epic browser 
https://www.epicbrowser.com/



و استخدام البروكس من 
Netherlands
الموقع يعمل 
لذلك يرجى التجربة باستخدامه 

![image](https://user-images.githubusercontent.com/36438188/62435983-657c2180-b73e-11e9-9154-3bb7b2ebc4d3.png)

**Comment by emadmahdi** [comment]
لم اجد 
epic proxy
ولا اريد استخدام متصفح جديد

**Comment by khidr82** [comment]
سوف ابحث لك عن بروكسى يعمل من
Netherlands
و سارسله لك عند ايجاده ان شاء الله

شكرا جزيلا لاهتمامكم و سرعة الرد

**Comment by emadmahdi** [comment]
احتاج بروكسي ارقام وليس برنامج ... واحتاج بروكسي لا يتأثر بعائق جوجل

**Comment by khidr82** [comment]
تمام
جارى البحث و ان شاء الله اجد المطلوب قريبا

**Comment by emadmahdi** [comment]
وجدت 
epic proxy
وجربت جميع الدول ولم يعمل

**Comment by khidr82** [comment]
يرجى تجربة البروكس التالى
188.166.59.17:8118

**Comment by emadmahdi** [comment]
للاسف نفس المشكلة

**Comment by emadmahdi** [comment]
اذا تريد تساعدني هناك حل بسيط نوعا ما ... هناك برنامج بسيط وصغير يسجل جميع الاشياء التي سوف تقوم بها بواسطة المتصفح ... نزل هذا البرنامج وفعل جميع الاختيارات وبعدها اضغط على زر بداية التسجيل ثم اذهب الى المتصفح وادخل على ايجي بيست وافتح فيلم وشغله ثم حاول ان تفتح مسلسل ايضا وحاول ان تحمل فيلم ليس كامل فقط بداية التحميل واقطع التحميل ثم اغلق الفيلم واذهب الى موقع الفيديو الذي لا يعمل عندي ثم حاول من هناك تشغيل عدة فيديوهات من التي تجدها عندهم ثم ارجع لبرنامج التسجيل واوقف التسجيل ثم خزن الملف وابعثه لي
https://www.telerik.com/fiddler/fiddlercap

**Comment by emadmahdi** [comment]
هذا البرنامج ايضا فيه امكانية ان تاخذ صورة لجميع الذي على شاشة الكمبيوتر وهو اوتوماتيكيا يضيفها مع التسجيل

**Comment by khidr82** [comment]
عزيزى السيد عماد 
الان فقط وجدت رسالتك 
سيتم عمل المطلوب و ارساله فى اسرع وقت 

شكرا

**Comment by khidr82** [comment]
عزيزى السيد عماد 

شكرا جزيلا لاهتمامكم و دعمكم الدائم 
الملفات المطلوبة فى المرفقات 
يرجى ابلاغى فى حالة اردت ملفات اخرى

[session-Output.zip](https://github.com/emadmahdi/KODI/files/3482725/session-Output.zip)

**Comment by khidr82** [comment]
عزيزى السيد عماد 

شكرا جزيلا لاهتمامكم و دعمكم 
تم تجهيز الملفات التالية 
يرجى ابلاغى فى حالة وجود مشكلة 

[1- streaming alladin movie with different qualities.zip](https://github.com/emadmahdi/KODI/files/3482800/1-.streaming.alladin.movie.with.different.qualities.zip)
[Uploading 2 - Download Alladin movie with different qualities.zip…]()
[Uploading 3 - Streaming suits -s09-e03 with different qualities.zip…]()
[Uploading 4 - Download suits -s09-e03 with different qualities.zip…]()

**Comment by khidr82** [comment]
[2 - Download Alladin movie with different qualities.zip](https://github.com/emadmahdi/KODI/files/3482849/2.-.Download.Alladin.movie.with.different.qualities.zip)

**Comment by khidr82** [comment]
[03 - Streaming suits -s09-e03 with different qualities.zip](https://github.com/emadmahdi/KODI/files/3482907/03.-.Streaming.suits.-s09-e03.with.different.qualities.zip)

**Comment by khidr82** [comment]
[4 - Download suits -s09-e03 with different qualities.zip](https://github.com/emadmahdi/KODI/files/3482927/4.-.Download.suits.-s09-e03.with.different.qualities.zip)

**Comment by emadmahdi** [comment]
سوف افحص الملفات لاحقا انا مشغول بحل مشكلة اخرى ... شكرا لك على المساعدة

مبدئيا انا فتحت الملف الاول واظن ان فيه الشيء الذي احتاجه

**Comment by emadmahdi** [comment]
السلام عليكم
وصلتني رسائلك الاثنتين ولكن اظن ان لديك مشكلة مع موقع الفيديو الروسي واظن انك عندما تطلب موقع الفيديو من المتصفح تظهر لك علامة الجوجل ال
reCAPTCHA
 وانت تتجاوزها بسهولة ولكن للاسف كودي لا يستطيع تجاوزها ولهذا ايجي بيست لا يعمل عندك
 
اترك موقع الايجي بيست وموقع الفيديو الروسي لمدة يومين ولا تستخدم المتصفح للدخول اليهما وبعد اليومين جرب الدخول الى ايجي بيست او الى موقع الفيديو لان عندك في المتصفح هناك كوكي يستمر بالعمل لعدة 
 ساعات ولا اعرف بالضبط كم الوقت ... المفروض المدة ليست يومين وانما هي ساعة ونصف فقط ولكني غير متأكد

اذا كنت تعرف كيف تمسح الكوكي الخاص بهذين الموقعين فممكن ان تمسحها وتغلق المتصفح تماما وبعد ذلك تشغل المتصفح وتجرب الدخول للموقعين بدون ان تنتظر اليومين

**Comment by emadmahdi** [comment]
السبب الثاني قد يكون تسجيل الدخول الى موقع ايجي بيست ولكن حسب الذي انا اعرفه فان ملفات ال
m3u8
لا تحتاج تسجيل الدخول الى موقع ايجي بيست

جرب واخبرني اذا كانت هذه المسألة تؤثر على تشغيل فيديوهات ايجي بيست باستخدام المتصفح

**Comment by emadmahdi** [comment]
لكي تمسح الكوكيز من متصفح كروم ادخل على هذا الرابط
chrome://settings/siteData
وابحث عن هذه الاثنين واسمح الكوكيز الخاصة بها
vidstream
egy.best

ثم حاول الدخول مرة ثانية واخبرني اذا كنت سوف تصادف ال
recaptcha
او اي شيء اخر

اذا مسحت الكوكيز فلن تحتاج يومين ولا حتى دقيقتين تستطيع مباشرة الدخول على الموقعين والتجربة فورا

**Comment by emadmahdi** [comment]
اقرأ الرسائل السابقة وجرب الاصدار الاخير 
5.8.1

**Comment by emadmahdi** [comment]
استلمت منك سجل الاخطاء ولكن انت اخترت فلمين لا تعمل على موقعها الاصلي فكيف تعمل على برنامجي ؟

**Comment by emadmahdi** [comment]
السلام عليكم اخ خضر احتاج مساعدتك

وجدت طريقة لكي ادخل على موقع فيديوهات ايجي بيست ولكني لاحظت ان المشاهدة وايضا التحميل لا تعمل مباشرة الا بعد عدة مرات ضغط على عدة روابط في موقع الفيديوهات واريد ان اعرف بالضبط ما هو التسلسل الصحيح للوصول الى ملفات الفيديو للمشاهدة وايضا للتحميل وهذا التسلسل يجب ان يبدأ بعد مسح جميع الكوكي الخاصة بهذه المواقع الاربعة

egy.best
www.egy.best
vidstream.top
vidstream.online

**Comment by khidr82** [comment]
السلام عليكم اخ عماد

قمت بتجربة متصفح جديد لضمان عدم وجود كوكيز مخزنة فى الجهاز
و عند الضغط مباشرة على كلمة مشاهدة من موقع ايجى بيست يظهر التالى 

![image](https://user-images.githubusercontent.com/36438188/63158844-694f5400-c01a-11e9-8879-4cbcabe4953b.png)

و بعدها قمت بالضغط على الفيديو نفسه فتغير الشكل الى التالى 

![image](https://user-images.githubusercontent.com/36438188/63159197-335e9f80-c01b-11e9-9809-b4e8022a28b4.png)

يرجى ابلاغى فى حالة اردت تجربة اى شىء اخر 
انا على استعداد للمساعدة

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله
وماذا عن التحميل ؟

**Comment by emadmahdi** [comment]
هذه طريقة مسح الكوكيز في متصفح كروم
.
![cookies in chrome](https://user-images.githubusercontent.com/7454511/63198205-f65cd200-c047-11e9-8682-5dffbdcaaeed.png)

**Comment by emadmahdi** [comment]
هذه طريقة مسح الكوكيز في متصفح كروم
.
![cookies in chrome](https://user-images.githubusercontent.com/7454511/63198694-7b94b680-c049-11e9-8046-c79d7fca82ff.png)

**Comment by emadmahdi** [comment]
احتاج ان اعرف منك من اين جلبت البروكسي الهولندي وكيف استطيع ان ان اجد مثله ؟

**Comment by khidr82** [comment]
قمت بالبحث على الانترنت على
Netherlands proxy
و قمت بتجربة النتائج الى ان وجدت احدهم يعمل و ارسلته لكم

**Comment by emadmahdi** [comment]
احتاج ايضا
VPN
يكون مجاني وفيه سيرفرات كثيرة وبعدة دول وفيه كمية تكفي لفحص ملفات فيديو هل تعرف موقع او برنامج فيه هذه المواصفات

**Comment by khidr82** [comment]
البرنامج التالى يحتوى على عدة دول 


Epic proxy
او
Epic browser
https://www.epicbrowser.com/

**Comment by emadmahdi** [comment]
هذا ليس
VPN
هذا متصفح ... وفيه اضافة للمتصفح ... هذا لا يعمل مع كودي ... اريد شيء استطيع ان استخدمه لفحص ايجي بيست في كودي وليس في المتصفح

**Comment by m7mdcc** [comment]
كودي فيه خيار البروكسي اذا عاوز بروكسيات 
Take a look at spys.one (@spys_one): https://twitter.com/spys_one?s=09

**Comment by emadmahdi** [comment]
انا قررت الغاء ايجي بيست في الوقت الحالي ... لاني لم استطع حل مشكلة مانع الاعلانات المستخدم في موقع ملفات الفيديو

ولكن موقع ايحي فور بيست ان شاء الله سوف احاول ان اصلحه في الاصدار القادم لاني انتبهت انهم بدأوا تشغيل السيرفر ولكن ليس لجميع الافلام ... وطبعا للاسف سوف يبقى محجوب عن بعض الدول

**Comment by emadmahdi** [comment]
قائمة البروكسي هذه لا يمكن الاعتماد عليها ... هذه هي نتائج فحص قائمة البروكسي الخاصة بهذا اليوم الثلاثاء

Checked 300 proxy servers
Total working proxies: 208

**Comment by emadmahdi** [comment]
هذا برنامج جيد للبحث عن بروكسي ... وظيفته البحث عن بروكسيات من جميع مواقع الانترنيت ... وايضا يفحص البروكسيات ويحدد نوعها وسرعتها وبلدها

http://proxysearcher.sourceforge.net

**Comment by m7mdcc** [comment]
> هذا برنامج جيد للبحث عن بروكسي ... وظيفته البحث عن بروكسيات من جميع مواقع الانترنيت ... وايضا يفحص البروكسيات ويحدد نوعها وسرعتها وبلدها
> 
> http://proxysearcher.sourceforge.net

محجوب بالسعوديه بستخدم بروكسي و اردلك خبر
