### ISSUE TITLE
موقع ايجي بيست

### ISSUE THREAD

**Issue by m7mdcc** [emadmahdi/KODI#16]
السلام عليكم
يعطيك العافيه

حصلت لي مشكله بالموقع مع فلم 
Inception مثلا
https://www.egy.best/movie/inception-2010/

شغال عالموقع لكن مش شغال على الاضافه

اتوقع المشكله من الموقع اللي عليه الفلم ؟

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله

موقع ايجي بيست من المواقع التي عليها حجب في بعض الدول ... والسؤال هو من اي بلد انت؟
وايضا احتاج منك ان تبعث لي سجل الاخطاء من قائمة خدمات البرنامج ولكن قبل ان تبعث السجل حاول ان تشغل عدة افلام من ايجي بيست لكي يتم تسجيل الخطأ في سجل الاخطاء

**Comment by m7mdcc** [comment]
هل يتم ارسال الأخطاء بشكل آلي ولا لازم افعل خيار معين ؟

انا ساكن بالسعوديه

**Comment by m7mdcc** [comment]
تمام تم الارسال

**Comment by emadmahdi** [comment]
سوف ابحث في المشكلة واحاول حلها لان عندي حجب في موقع الفيديو الخاص بايجي بيست ولهذا لا اعرف هل الاصلاحات التي اعملها تحل المشكلة ام لا

**Comment by khidr82** [comment]
تم التجربة مره اخرى و ارسال سجل الاخطاء 
و تجربة نفس الفيديو من الموقع و هو يعمل فى الموقع بدون اى مشكلة 


ملحوظة لا اعلم اذا كانت ستفيد ام لا 
بمراجعه ملف الاخطاء وجدت ان الرابط الذى يظهر هو 
`
https://www.egy.best/api?call=thhhriNjhrhkhrqiNwQphRYDcrkrhreaAGRUiecrhkDHhDGDhkFHHHrkfrhrRUYhrhkhrDkDcqqHrhqHrkxqDhrkrhrfVhrhkhrDrDGDtFqGDUjhrkrhrRUQhrhkhrDHHkDihDhhrkrhrQUVrhkhraUVUQUcWwkqhrhG&auth=b7118a5684dc07ad9db3d314ff8fe905?name=vidstream__download__mp4__720p
`
و عند الدخول على هذا الرابط من المتصفح اجد التالى 

![image](https://user-images.githubusercontent.com/36438188/63130825-0dee7900-bfbc-11e9-905d-8f87c96566c2.png)

و ايضا لم اجد فى سجل الاخطاء ان البرنامج يجد اى رابط من موقع 
https://vidstream.top

مع العلم ان رابط الفيديو الذى يظهر لدى فى المتصفح هو 
`
https://a3-tu7-s-tw9w.vidstream.top/watch/f3ba8731228bf188PCADmlx5QlMQjZMff.glt9-vYzscQPgiWLUK-ymw__.VnVHbmw1dWxOYU9yYXpOTmZieWVPOGVySUQ1enlkZVFsLzM1WnpRZFE1dzlNL1BVMmNWeW1aWkg5Yng2dUpUUnNrQk9OamhleEVaUlZZQ0sxOFhLRE56bUJrWjRndXd1MENZQXJYUzFqWjZuR0h2VWtNQXJweEtHZFdvT1puaXlUSCt2Wi9BdHdybmlBRUpWQlFlTVRWZlVkNW02MmltWVBGaGFZb05HM0VrYXZuTW0yKzY4QWVQckxHdHVmYno0MlIrWnp2U1pXVFlRVEt3ZElUdVF0YnVvaUp0REk3TFBCUlBiVk8xRy9TU1BuL052Q3UrdWJ6aURaK1BoQWw3ZTZ2aGhjeG5WQ0d4bGZNWFQ3VTRMR1piK2UvY2lxcTlZNlhmb1FQc2hoK09UMG81ekVMZXVLVnlFSFppbXd0K1FCOW04MUpKM25ndHBKWGtSbENlWTZCcGNhdFdzM29xeXZNcW00ek42YUxqdGlrZnEzdEZ0RkR6cmZNdnVXNTduQng4SkEzUURVbEVwMUE9PQ__/[EgyBest].Aladdin.2019.HDRip.720p.x264.mp4
`

مع العلم ان الفيديو الاصلى يعمل
![image](https://user-images.githubusercontent.com/36438188/63130643-6f621800-bfbb-11e9-91c8-f3287b73a70d.png)

**Comment by m7mdcc** [comment]
> سوف ابحث في المشكلة واحاول حلها لان عندي حجب في موقع الفيديو الخاص بايجي بيست ولهذا لا اعرف هل الاصلاحات التي اعملها تحل المشكلة ام لا

اذا تحب ممكن نشوف بروكسي أو VPN
يشغل الموقع

**Comment by emadmahdi** [comment]
الروابط التي انت ارسلتها كلها صجيجة لان برنامجي يترجم هذه الروابط في النهاية الى روابط خاصة بموقع ملفات الفيديو 
vidstream.top

المشكلة التي في البرنامج هي بعد طلب الرابط الصحيح من موقع الفيديو فهو يجيب بملف انا لا اعرف بالضبط ماذا في داخله فكيف اجد ال
mp4    او   m3u8

والسبب ان موقع ملفات الفيديو هذا فيه حجب في الانترنيت الخاصة بي ولم اجد الى الان بروكسي او في بي ان يستطيع تجاوز هذه المشكلة

**Comment by emadmahdi** [comment]
اخ خضر ارجوك ارجع الى الموضوع الذي كنا نتكلم به على هذا الرابط واقرأ اجوبتي
https://github.com/emadmahdi/KODI/issues/15

**Comment by khidr82** [comment]
> اخ خضر ارجوك ارجع الى الموضوع الذي كنا نتكلم به على هذا الرابط واقرأ اجوبتي
> #15

تم الرجوع الى الموضوع الاصلى و تم الرد
شكرا لدعمكم و سرعة الاستجابة

**Comment by MrrRax884** [comment]
**_[]()_**
