### ISSUE TITLE
Akoam

### ISSUE THREAD

**Issue by Ramadananinho** [emadmahdi/KODI#17]
السلام عليكم اخى الكريم
الحقيقه انا فى غايه السعاده ان حضرتك بترد على المشاكل شيئ مفرح فعلا
فعلا انا باجد الخطاء 104 فى المواقع المذكوره واعتقد ده لان 
المواقع دى غيرت ال host الخاص بيها من فتره واعتقد ده اللى بيسبب المشكله على سبيل المثال موقع Akoam 
اصبح https://we.akoam.net/  وهو يعمل بشكل جيد جدا فى المتصفح دون اى مشاكل ، وعند فتح ال addon العظيم الخاص بحضرتك 
يعطى الخطاء 104  
شكرا لمجهودك
انا اللى حضرتك رديت عليا فى ايميل. Ramadaninho@gmail.com

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله

تغيير اسم الموقع لا علاقة له بخطأ 104 ... وفعلا في البداية كانت مشكلة لان اسم الموقع كان يتغير كل يومين او ثلاثة ولكني حليت هذا المشكلة اظن في بداية رمضان

خطأ 104 معناه ان كودي يربط بالسيرفر ولكن السيرفر يفصل الخط وبما ان المشكلة نفسها تكررت في اكثر من موقع فانها 90% معناها نوع من الحجب في الانترنيت الخاصة بك

ولكي اعرف نوع الحجب وهل ممكن تجاوزه فانا اريد ان اعرف  ماذا يحدث معك عندما تطلب هذه المواقع من المتصفح ... هل يظهر الموقع مباشرة ام ان هناك اشياء اخرى تظهر قبل الموقع

وايضا اريد ان اعرف هل ال
DNS
لهذه المواقع يترجم الاسماء الى الارقام الصحيحة ام لا

**Comment by Ramadananinho** [comment]
اخى الكريم
الموقع يعمل بشكل جيد واقوم بالمشاهده والتحميل منه من المتصفح بشكل ممتاذ جدا المشكله موجوده فى ال Addon 
![3129AF16-CF36-4DA0-90A3-50F04169A628](https://user-images.githubusercontent.com/54151015/63115138-d0c3c000-bf96-11e9-99ec-899511b72aed.png)
اليك صوره من الموقع عقر ال Ipad

**Comment by emadmahdi** [comment]
المشكلة ليست من برنامجي ... المشكلة من الانترنت الخاص بك

واذا كان يشتغل الموقع على المتصفح فاذن ليست لديك مشكلة 
DNS
اما مشكلة حجب فاكثرية الحجب يمنع فقط البرامج مثل كودي وقد لا تؤثر على المتصفح ولكن سؤالي هو ... هل في بعض الاوقات تظهر لك صفحة اخرى قبل الموقع مثل هذه او غيرها

![akoam_problem](https://user-images.githubusercontent.com/7454511/63115942-698e1780-bf66-11e9-8747-6f5c4917871d.png)

**Comment by Ramadananinho** [comment]
لا لاتظهر اى شيئ وهل لو تم استخدام VPN يمنع الحجب

**Comment by emadmahdi** [comment]
بما ان جميع الاضافات تعمل عندك على كودي وبرنامجي لا يعمل فانا اريد منك ان تجرب هذه المواقع باستخدام اي اضافة اخرى غير برنامجي وتخبرني بالنتيجة
shahid4u
akoam
egybest

انا لا يهمني ان جميع مواقع العالم تعمل على المتصفح او على كودي ... انا يهمني ان اعرف ما هي مشكلة هذه المواقع الثلاثة عندك باستخدام كودي لان هذه المواقع الثلاثة تعمل عند جميع الناس عدا عند بعض الاشخاص في الكويت وفي مصر وعندك  لم تخبرني بلدك فكيف استطيع ان ارى المشكلة بنفسي وانا لا اعرف  اين ابحث

وللعلم فقط البارحة هذه هي أعداد الفيديوهات التي شغلها العالم باستخدام برنامجي
AKOAM = 1,727
SHAHID4U = 307
EGYBEST = 0

مشكلة ايجي بيست سببها ان هناك حجب على الانترنيت الخاصة بي ولهذا انا اقوم بالاصلاحات ولكني لا اعرف اذا 
نجحت ام لا

ومشكلة ايجي بيست عندك مختلفة لان العالم كله يستطيع الدخول للموقع ولكن لا يستطيعون تشغيل فيديو بينما انت لا تستطيع الدخول للموقع

واذا كنت تصر على ان المشكلة هي من برنامجي فاذن انتهى الموضوع وانتهى النقاش ... وانا ارجوك ان تمسح برنامجي لانه ليس جيد كفاية بالنسبة لك ... وابحث عن اضافة غيرها

**Comment by emadmahdi** [comment]
انا تأكدت ان لديك نوع من الحجب ولا اعرف مصدره ولكن على الاغلب هناك برنامج يشتغل على جهازك ولا اقصد على المتصفح وانما على كودي او على الانترنيت او على جهازك

**Comment by emadmahdi** [comment]
اسف نسيت سؤالك عن ال
vpn

نعم جرب امريكا او كندا او اوربا جميعها تعمل مع برنامجي بدون مشاكل عدا موقعين
egybest
egy4best

**Comment by Ramadananinho** [comment]
اخى الكريم لما الحده بالكلام انى استخدم برنامج اهر غير الخاص بك انا من اول طلب المساعده اشكر مجهودك خصوصا على الرد ، انا لم اقل شيئ يحزنك كى تقول لى اذهب لبرنامج اخر، على العموم انا فعلا شاكر لمجهودك الوافر لضمان مشاهده وشكرى لانى استمتعت بالبرنامج لفتره طويله قبل ظهور المشكله ، لاكنى لم اقل شيئ يحزنك شكرا

**Comment by emadmahdi** [comment]
اخي لو كنت انت تقضي ساعات طويلة لايام كثيرة في عمل برنامج وتصليحه وحل جميع مشاكله عدا عن المشاك التي تأتيك بالرسائل من الناس في العالم كله وانت متأكد انه لا توجد في برنامجك اي مشكلة ... وياتيك شخص بكل بساطة وسهولة ويقول لك ان عملك كله لا يشتغل وان كل شيء يشتغل الا برنامجك فكيف سوف تشعر ؟

**Comment by Ramadananinho** [comment]
استقبل الامر بصدر رحب بما انه لم يقل شيئ مخزى قد يكون سوء اختيار تعبير مناسب وهذا يحدث كثيرا فى التواصل عبر الكتابه ، على العموم بعتذر لحضرتك ان كنت شعرت بتقليل من مجهودك انا كنت بس حابب اوصل لك ان البرامج الاخرى تعمل جيدا دون التقليل منك او حتى من البرنامج انا مازلت اشكر حضرتك لان البرنامجفى الاساس مجانى وليس لى اى حق انى اطلب مساعده منك الا اذا كنت موافق تطوعا وفضلا وليس امرا 
كل مافى الامر انىكنت معتمد على البرنامج واوصى به كثير كن الاصدقاء وجميعا لديه نفس المشكله شكرا مره اخرى

**Comment by emadmahdi** [comment]
انت ابسط شيء سالتك اربعة مرات من اي بلد انت ولم تخبرني فكيف احل مشكلتك وانا لا اعرف شيء عنك ... انا  لا اطلب منك شيء فقط لكي اتعرف عليك ... انا احتاج ان ارى المشكلة بنفسي يعني اغير بلدي باستخدام
vpn   او   proxy
وعسى ولعل تحدث عندي نفس مشكلتك فاقوم بالبحث عن حل لها

**Comment by Ramadananinho** [comment]
انا من مصر

**Comment by emadmahdi** [comment]
من اي مدينة في مصر ... في الجيزة اكوام لا تعمل  ... ولكن في اسوان اكوام تعمل بدون مشاكل

**Comment by Ramadananinho** [comment]
الجيزه فعلا

**Comment by emadmahdi** [comment]
هذه هي عدد الفيديوهات التي تم تشغيلها في شهر اغسطس 2019 باستخدام برنامجي لموقعي
shahid4u
akoam

![egypt_problem_august_2019](https://user-images.githubusercontent.com/7454511/63126108-1ffcf700-bf7d-11e9-90e5-d58db8f6e474.png)

**Comment by emadmahdi** [comment]
هذه الارقام والالوان تخص فقط جمهورية مصر في شهر اغسطس في 2019 .. اقصد انها ليس فيها اي شيء عن بقية الدول المحيطة بجمهورية مصر

**Comment by Ramadananinho** [comment]
هل من نصيحه اقوم بها كى استطيع المشاهده مره اخرى ؟

**Comment by emadmahdi** [comment]
بالمناسبة الحجب في الجيزة هو ليس من شركة واحدة وإنما اكثر من شركة انترنت لان رقم الخطأ يختلف ... عندك هو خطأ رقم 104 ... وعند غيرك هو رقم 0

اما كيفية حل المشكلة فحاليا برنامجي ليس فيه الحل ... ولكن بعض المصريين جربوا استخدام
VPN
واستطاعوا تجاوز المشكلة ... ولكن كما اخبرتك فان بعض المواقع سوف تعمل ولكن احتمال كبير ان المواقع التي كانت تعمل قد تتوقف عن العمل ... ولم اجد الى الان بلد تشتغل فيه جميع المواقع

اما عن برنامجي فانا لست متأكد ان مشكلة الحجب ضخمة وتستحق ايجاد حل خاص لها  ... لان الشكاوي التي اتلقاها عن الموضوع لا تستحق التعب

**Comment by emadmahdi** [comment]
هذه الخارطة هي فقط لجمهورية مصر لنفس الموقعين ولكن لكل سنة 2019 ... لاجظ الفرق ... جميع المدن المصرية كانت قادرة على تشغيل فيديوهات وفعلا قاموا بتشغيل  فيديوهات باستخدام برنامجي على هذين الموقعين ولكن بعد الحجب اصبح الاستخدام تقريبا منعدم في جمهورية مصر

![egypt_problem_2019](https://user-images.githubusercontent.com/7454511/63127370-2c368380-bf80-11e9-81b1-0ab53862d12e.png)

**Comment by Ramadananinho** [comment]
هجرب VPN وابلغك من اى بلد صحيح انت ؟

**Comment by emadmahdi** [comment]
هذا الرسم هو فقط لمدينة الجيزة في كل سنة 2019 ... لاحظ تاريخ بداية الحجب

![image](https://user-images.githubusercontent.com/7454511/63128320-a1a35380-bf82-11e9-83c2-df17f5ecb33f.png)
