### ISSUE TITLE
Akoam

### ISSUE THREAD

**Issue by Ramadananinho** [emadmahdi/KODI#18]
السلام عليكم
انا كنت بتكلم معاك بالامس بخصوص موقع اكوام من مصر فى الجيزه تحديدا ، انا قمت باستخدام. VPN والبرنامج يعمل بحاله ممتاذه ، كان عندك حق من الواضح الحجب من مصر فعلا

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله
انا لا اظن ان الحجب من مصر لان نفس الشيء حدث في دول اخرى وفي نفس التوقيت ... اظن ان الحجب من الشركات التي تتحكم بخطوط الشبكة الرئيسية للانترنيت في العالم وبالتحديد اظن شركة
cloudflare

**Comment by Ramadananinho** [comment]
على العموم الان يعمل بصوره ممتازه

**Comment by emadmahdi** [comment]
اذا وجدت بلد جميع مواقع برنامجي تعمل فيه فارجوك اخبرني قد استطيع اضافته لبرنامجي لكي لا تحتاج انت وباقي المستخدمين الى اي شيء اخر

**Comment by Ramadananinho** [comment]
انا جزبت معظم المواقع تعمل بحاله جيدا ب فرنسا و ايطاليا وبلجيكاً

**Comment by emadmahdi** [comment]
الدول التي انت ذكرتها فيها موقعين لا تعمل وهما
egy.best
egy4best.com

وانا احتاج بلد تعمل فيه جميع المواقع
