### ISSUE TITLE
مشكله ف موقع اكوام 

### ISSUE THREAD

**Issue by tarekrrr** [emadmahdi/KODI#19]
توقف موقع اكوام  عن العمل في السعوديه  لدي منذ يومين وتظهر لي رساله انه هناك حجب مصدره شركه الانترنت   وان هناك حل لدى مبرمج البرنامج  الموقع يعمل ع المتصفح بشكل طبيعي جدا والمشكله فقط في  الاضافه 
هل هناك حل للمشكله لان موقع اكوام هو الموقع الاهم لدي في الاضافه

**Comment by tarekrrr** [comment]
انا ف السعوديه وظهرت المشكله منذ يومين فقط قبلها كان الموقع يعمل بدون اي  مشكله

**Comment by emadmahdi** [comment]
المشكلة ليست من البرنامج ولكنها من الانترنت الخاص بك ... انا ايضا توقفت عندي اكوام قبل يومين ولكن هناك دول ما تزال تستطيع استخدام اكوام من برنامجي وحتى هناك دول مثل أمريكا ومصر التي فيها بعض المدن تعمل وبعضها لا يعمل ... على كل حال سوف افكر بحل للمشكلة.

**Comment by tarekrrr** [comment]
اتمنى يكون هناك حل للموقع لانه يعتبر الموقع الابرز ف الاضافه .
وبصراحه الاضافه رائعه والمجهود المبذول من حضرتك رهيب  ربنا يعينك ويوفقك
