### ISSUE TITLE
اقتراح بخصوص خدمة debrid

### ISSUE THREAD

**Issue by DemFaR** [emadmahdi/KODI#2]
السلام عليكم، 

انا كنت يأست اني اتفرج على حاجة عربي على كودي لكن بالصدفة لقيت الادون بتاعك وبصراحة انا منبهر ولأول مرة بتفرج على حاجات عربي على الكودي

هل في إمكانية تضيف خدمات debrid زي real-debrid و alldebrid للأدون؟ انا مشترك عليهم وبتفرج على الحاجات الاجنبي وبتخلي الكودي يعتمد على المواقع دي لتوفير رابط مباشر من تورنت او من مواقع الهوست للفيديو او التحميل فمش بيبقى في بفر خالص،

على اي حال الف شكر على مجهودك وبالتوفيق.

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله

أهلا وسهلا بك في برنامجي .. انا قبل فترة فكرت في اضافة سيرفرات ديبرد .. ولكن لم اتوصل الى قناعة كافية بخصوص هذا الموضوع .. يعني لا اظن ان لها فائدة في برنامج مثل برنامجي .. بسبب وجود مواقع بديلة كثيرة في برنامجي .. وايضا بسبب وجود جودات متنوعة في برنامجي

علما انك اول شخص يكلمني في هذا الموضوع منذ ان بدأت بنشر برنامجي سنة 2018 .. أنا أقصد انه لا يوجد اقبال على خدمة مثل هذه .. وخاصة ان سيرفرات ديبرد التي أنا أعرفها كلها ليست مجانية .. وفوق هذا لكي أضيفها الى برنامجي فانا أحتاج ان أشترك معهم وأدفع لهم فلوس أعتبرها ضائعة في هكذا سيرفرات
