### ISSUE TITLE
بعض المواقع والسيرفرات لا تعمل وخاصة افلام الكبار وافلام 2018

### ISSUE THREAD

**Issue by hussapril7** [emadmahdi/KODI#2]
شلونك اخ عماد اتمنى تكون بخير ، حبيب قلبي دخلت اضافتك ودخلت موقع هلال يوتيوب ودخلت على افلام اجنبيه، ولكن كل ما ادخل فلم يطلع لي خطأ مكتوب ( غير مسموح هنا،  هذا الفيديو للكبار فقط )!! غالبيه الافلام يطلع لي هالخطأ يعني افلام عاديه اكشن او رعب او اي  فلم بسيط يطلع هذي المشكله 

فا مادري هل تقدر تعمل شي بهذي المشكله ؟ 
لان حسيت الموقع ماله فايده اذا كل ما ادخل يعطيني هذا الخطأ

**Comment by hussapril7** [comment]
ما هذا اخ عماد!!! اغلب المواقع لاتشتغل ولا حتى الراوبط!!!

 دخلت هلا سينما يعطيني خطأ ايضا عندما دخلت على كذا فلم وكانه السيرفرات معطله!!!! كله يظهر لي خطأ

ذهبت الى موقع كل العرب نفس الطريقه!!!

فقط موقع شاهد فور يو يشتغل جيدا

ارجوا منك عندما تتاكد من تحديث الاضافه 
ان تدخل الاضافه وتفحص الاضافه مثلنا وتتاكد من انه كل موقع شغال 
يعني ادخل كل موقع وادخل على بعض الافلام والمسلسلات عالسريع فقط للتاكد انه كل شي شغال  دون مشاكل

يعني انا موقع اكوام قلت مايشتغل وفي خطأ خلاص طوفته قلت مابي ادخله وبكمل في باقي المواقع

ولكن بعد هم المواقع يصير فيها جذي !!!

لا اعلم صراحه ساعات الاضافه اشوفها روعه 
ولكن الان احس صارت فيها مشاكل كثيره!

اتمنى اخ عماد ان تغحص الاضافه جيدا قبل التحديث وتتاكد بشكل قطي وعن تجربه انه شغال كل شي 100 بالمئه
وكل المواقع وسيرفراتها شغاله

وارجوا ان تقرا الرساله الاولى بخصوص موقع هلال يوتيوب ايضا

**Comment by emadmahdi** [comment]
افلام للكبار فقط انا منعتها ... اما الافلام الاجنبية التي يظهر فيها مشاكل من السيرفر فهي من الموقع الاصلي وخاصة افلام 2018 لان فيها حقوق طبع ونشر ولهذا تقوم شركات الانتاج السينمائي بملاحقة هذه الافلام ومسحها من السيرفرات ... وارجوك قبل ان تشتكي وقبل ان تبدأ بتعليمي ماذا افعل وكيف افحص وكيف انشر ... عليك اولا ان تدخل الى الموقع الاصلي وتتأكد من مصدر الخطأ هل هو من الموقع الاصلي ام من برنامجي ... وايضا عندما تشتكي عليك 
 ان تحدد اسم الفيلم الذي فيه مشكلة لاني لا اعلم الغيب ولست مجنون لكي افحص كل الافلام وكل المسلسلات ... اما عن الفحص البسيط فانا دائما افحص الافلام العربية والاجنبية والمسلسلات ولكني لا افحص الافلام والمسلسلات الجديدة لانها سيئة من الموقع الاصلي

**Comment by hussapril7** [comment]
اولا اعتذر اذا كان كلامي حاد فا انا لم اقصد ان اقلل من فهمك وعلمك
ثانيا بخصوص الافلام التي تقول منعتها، لو كنت اعلم هذا الشي لما قلت لك
فا انا لا اعلم الغيب نفس ماتقول انت عن نفسك
اعتقدت انه هناك مشكله بالاضافه لذلك قلت لك
انفعلت نوعا ما لان كنت آملاً ان المواقع تشتغل بشكل ممتاز وخصوصا كانت تشتغل الافلام ف موقع هلا يوتيوب سابقاً
فا طبيعي اشعر بان الاضافه فيها مشكله
وبخصوص اقول لك الفلم الذي فيه الخطأ
عندما ظهر لي اول خطا دخلت كذا فلم عشوائيا لكي اتاكد كل الافلام بها اخطاء ام لا
فلا اذكر الافلام لاني دخلتها عشوائيا

وانا لم اقل لك افحص كل الافلام والمسلسلات
انا قلت افحص بعضها فقط بمعنى 2 او 3 بالكثير للتتاكد
واكيد لا اعلمك شغلك انت اخبر واعلم في مجالك ولم اقصد ان اقلل من احترامك او عملك

عموما انا اسف اذا ازعجتج او ضايقتك في كلامي 
وانت لم تقصر معي فا حاولت جاهدا مساعدتي في حل جميع المشاكل التي تحدث معي بالاضافه
لا انسى ذلك

اتمنى لك التوفيق اخ عماد...

**Comment by emadmahdi** [comment]
بالمناسبة اذا كنت تستخدم كودي اصدار 18 فهذا معناه ان بعض المواقع وكثير من الافلام لن تعمل معك لان اصدار 18 فيه مشكلة الاتصال المشفر لا يعمل

واذا عندك مشكلة فارجوك حدد لي اولا الموقع وثانيا الفيلم وثالثا السيرفر ... وبدون هذه الثلاثة مع بعض فانا لا استطيع فعل اي شيء لحل المشكلة ... لان برنامجي ضخم وليس شيء بسيط حيث اني اتعامل مع الاف الفيدوهات واتعامل ايضا مع مئات السيرفرات

**Comment by hussapril7** [comment]
استخدم اصدار 17.6 ولم احدث لآخر اصدار 18 لان اعلم انه بيتا ولا زال قيد التطوير

اعلم حجم التعب الذي تتعبه مع الاضافه ومع المستخدمين والمشاكل التي تحدث وتقوم باصلاحها 
اعانك الله

وحسنا في حال واجهت اخطاء بالاضافه ساذكر لك ال 3 نقاط التي قلتها.......

**Comment by emadmahdi** [comment]
نسيت ان اقول لك ... اني ايضا اتعامل مع برنامجي الذي اصبح حجمه الاف الاسطر وليس مجرد ملفات او برامج قصيرة ... يعني اي خلل او خطأ في سطر واحد قد يسبب مشكلة تؤثر على الاف الفيدوهات ... برنامجي اصبح كبير جدا حتى علي انا شخصيا لاني لم اكن اتوقع او اريد ان يصبح كبير الى هذه الدرجة

**Comment by hussapril7** [comment]
بالعكس كل ماكبرت الاضافه راح تصير شامله وضخمه ويصير فيها خيارات متاحه اكثر للمستخدمين
واعلم انه لغة البرمجه والاكواد التي تشتغل عليها كثيره واكيد تحدث اخطاء فليس آلي انت، انسان يخطيء ويصيب
فا اعلم ماتواجهه في العمل 
وفقك الله وتمنياتي لك بالتوفيق اخ عماد
وان شاءالله اشوف اضافتك مع مرور الوقت لها صيت واسع عند العرب
