### ISSUE TITLE
English version ?

### ISSUE THREAD

**Issue by SoniaMalki** [emadmahdi/KODI#2]
Salamaleikoum 

thank you for your work. Is it possible to provide English translation ? I am setting this up for my grandparents but I can’t read Arabic so it is difficult to set up for them 

thank you

**Comment by emadmahdi** [comment]
Wa Alekum Alsalam
I have a special KODI installation files that is already set to run on Android & Windows without any further setup .. You can download it from this link:
.
https://tiny.cc/kodiemad
.
FYI .. My special KODIEMAD installation files can easily set KODI to Arabic or English anytime you need it .. But my EMAD ARABIC VIDEOS addon will always run in Arabic .. Please let me know if you need any further help.
