### ISSUE TITLE
اكوام

### ISSUE THREAD

**Issue by laith565** [emadmahdi/KODI#20]
اكوام لا يفتح في السويد

**Comment by laith565** [comment]
Sent from Yahoo Mail on Android 
 
  On الأربعاء, تشرين الأول ٣٠, ٢٠١٩ at ٢٣:١١, emadmahdi<notifications@github.com> wrote:   
Closed #20.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.




رجع الموقع يعمل شكرا جدا.

**Comment by emadmahdi** [comment]
الشكر لله
