### ISSUE TITLE
السلام عليكم اخ عماد :)

### ISSUE THREAD

**Issue by hussapril7** [emadmahdi/KODI#23]
ياهلا ومرحبا وجد توو ما نوور القيت هوب والكودي بعد هههه

الحمدلله على سلامتك واتمنى تكون بخير وصحه يارب 

انا شفت تحديث برنامجك ووالله جدا جدا جدا فرحت 

وفحصت كل البرنامج بعد التحديث 

شفت بعض المواقع شغاله والبعض لا يشتغل ويظهر لي رساله بأنك مشغول وتعاني من وعكه صحيه

اقدر هذا الشي وربي يقومك بالسلامه يالحبيب وتكون احسن من اول

انا بانتظار تحديثاتك ان شاءالله

وولعلم موقع ايجي بيست رد يشتغل من جديد وتغيير الدوومين 
من 
https://Egy.best
الى 
https://Seen.egybest.biz

عموما اكيد تعرف هذا الشي

ادري تحتاج الوقت لتعديل جميع المواقع في برنامجك 
وانا بانتظار التحديثات ان شاءالله

اهم شي فرحتنا بعودتك 
وان شاءالله مع الوقت ترتب كل شي 👊

اتمنى لك الشفاء العاجل يالحبيب 💙

اخوك حسين 🌷

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله

مشكلة ايجي بيست هي انهم يستخدمون موقع روسي لخزن ملفات الفيديو ... وهذا الموقع الروسي يستخدم برنامج مكتوب بلغة جافا سكربت ... وللاسف كودي لا يفهم هذه اللغة ... ولهذا لم استطع تشغيل موقع ايجي بيست

**Comment by hussapril7** [comment]
حسافه عاد موقع ايجي بيست سريع في تشغيل الافلام وجودة الافلام ممتازه

يلا ماعليه البركه ان شاءالله في باقي المواقع

بس اخ عماد تبيني اعطيك اسامي مواقع مهتمه بالافلام ؟؟؟

ولا انت تشوف مكتفي بالموجود؟؟؟

**Comment by emadmahdi** [comment]
عندي مواقع ولكن ليس عندي وقت لها

**Comment by Allaeddine30** [comment]
أخ عماد واجت مشكلة عند تثبيت الإضافة، ويفشل في انهاء التثبيت بالضبط عند youtube-dl control وينقطع التثبيت
