### ISSUE TITLE
Akoam

### ISSUE THREAD

**Issue by ellyraf** [emadmahdi/KODI#24]
السلام عليكم
عندي موقع كودي وكنت استطيع متابعة كل البرامج والافلام والمسلسلات من موقع اكوام
الان وللأسف قبل يومين كل سيرڤرات اكوام لا تعمل
انا اسكن في استراليا

شكراً جزيلا

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله وبركاته

تم حل المشكلة في الاصدار الاخير
v6.0.3

تحتاج ان تقوم بتحديث الإضافة ... واذا بقت المشكلة فاكتب لي تعليق هنا على
GitHub

**Comment by ellyraf** [comment]
السلام عليكم
شلون اسوي تحديث الاضافة بلا زحمة؟
يعني احذف كلشي
واسوي add source من اول وجديد؟

**Comment by ellyraf** [comment]
مرحبا
عاشت ايدك رجعت عندي اكوام الف شكر الك
بس ماادري اذا ممكن اسألك عن اضافة افلام للموقع لو لا؟
وسؤال ثاني الله يخليك بالنسبة لـ بانيت و شوف ماكس وغيرها من المواقع
رح ترجع تشتغل لو لا؟
وشكراً على احلى موقع👍🏼🌸

**Comment by emadmahdi** [comment]
بالنسبة لتحديث البرنامج فهناك طريقتين ... اما تنتظر 24 ساعة الى ان يقوم كودي بتحديث البرنامج ... واما ان تقوم انت بتحديث الاضافة بنفسك ... هناك فيديوهات كثيرة في اليوتيوب وفي جوجل تشرح كيفية تحديث اضافات كودي

المواقع التي موجودة الان في البرنامج جميعها تعمل ... اما المواقع التي غير موجودة فلا اظن اني سوف ارجعها

 اما اضافة افلام ... فانا لا اضيف اي فيديوهات الى برنامجي ... انا فقط اضيف مواقع ... وهذا معناه أن الذي تحصل عليه من برنامجي هو فقط الذي موجود في المواقع الاصلية

**Comment by ellyraf** [comment]
الف شكر الك مرة ثانية
رجع عندي اكوام شغال تمام التمام
رح اشوف ع اليوتيوب شلون التحديث
ممكن سؤال اخر اخي العزيز
هل بالامكان بالمستقبل اضافة موقع ( شاهد نت) ؟
وشكراً جزيلاً

**Comment by emadmahdi** [comment]
ابعث لي رابط الموقع لكي افحصه

**Comment by ellyraf** [comment]
اي حاضر
ويوجد تطبيق شاهد ايضاً بإشتراك شهري
https://shahid.mbc.net/ar/

**Comment by emadmahdi** [comment]
شكرا لك
اضفت هذا الموقع الى قائمة التحديثات
ولكن للأسف لا اظن اني سوف اضيفه قريبا

**Comment by ellyraf** [comment]
عاشت ايدك
شكراً جزيلاً وعلى راحتك
اصلاً اكوام يُغني عن كل المواقع

**Comment by emadmahdi** [comment]
الشكر لله
اهلا وسهلا بك
مع السلامة

**Comment by ellyraf** [comment]
السلام عليكم اخي
اعتذر لانه رجعت ثاني
بس موقع اكوام رجع لا تشتغل السيرڤرات للأسف

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله
البارحة انا عملت تحديث للبرنامج لحل مشكلة اكوام

جرب الاصدار الجديد
v6.0.4

**Comment by ellyraf** [comment]
شكراً جزيلاً
نعم المشكلة انحلت🌷

**Comment by ellyraf** [comment]
السلام عليكم اخي
مشكلة عدم اشتغال السيرڤرات رجعت من يوم امس.
وشكراً لتعاونكم

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله
موقع اكوام تغير التصميم وبرنامجي لا يعرف التصميم الجديد ولا اظن اني سوف اضيف التصميم الجديد الى برنامجي

**Comment by ellyraf** [comment]
الاصدار الاخير عندي
(6.0.8)
كيف اعمل تحديث فضلاً لا امراً؟

**Comment by emadmahdi** [comment]
الاصدار الاخير هو الذي عندك 6.0.8 ... ولا اظن اني سوف اصلح موقع اكوام لانه بحاجة الى برمجة من الصفر

**Comment by ellyraf** [comment]
شكراً جزيلاً
كلها ما تشتغل وليس اكوام فقط
الف شكر الكم

**Comment by emadmahdi** [comment]
طريقة كلامك  عن البرنامج تجعلني افكر ادمر واحطم برنامجي لان حسب قولك كل المواقع لا تعمل

ادخل الى برنامجي وبعدها من القائمة الرئيسية اضغط على تقرير الاستخدام ثم اقرأ بدقة وتركيز الكتابة التي سوف تظهر لك

اذا فعلا عندك مشكلة فاذن هي منك وليست من البرنامج

واذا انت مصر ان المشكلة من برنامجي فاذن ابعث لي الموقع واسم الفيلم  واسم السيرفر الذي لم يعمل ... وافعل هذا مع جميع مواقع برنامجي ... يعني ابعث لي 13 فيلم انت فحصته ولم يعمل

واذا بعثت لي اقل من 13 فيلم من 13 موقع فاذن سوف اهمل كلامك واتجاوزه واعتبر هذا اعتراف منك ان المشكلة منك وليست من البرنامج

**Comment by ellyraf** [comment]
على كيفك اخي
شنو هالمبالغة بالكلام ما يحتاج لا تدمير برنامج ولا اي شي من هالقبيل
اي نعم احتمال الخلل مني والبرنامج تبعك اكثر من رائع والمواقع الان شغاله
اعتذر منك
و مع هذا اهمل رسالتي براحتك لو انزعجت
شكراً جزيلاً🌹

**Comment by emadmahdi** [comment]
اخي العزيز

كل شخص يعمل شي مجاني هو يعمله ليس لارضاء فلان او علان وانما لكي يشعر في داخله بشعور ايجابي ... ولكن عندما يهجم عليه شخص ويقول له ان عمله كله لا يعمل فهذا يدمر المعنويات ويحطمها فيكون الجواب 
 لهذا الشخص من نفس النوع هجوم سلبي و جواب سلبي وتصرف سلبي

مثلا ... اليوم بعد قراءة رسالتك ... انا قررت ان انسى موقع اكوام الجديد وأتوقف عن تحديث المواقع الباقية عدا التي انا استخدمها ... ولكن بعد ساعتين او ثلاثة وبالصدفة تراسل مع شخص بالفيسبوك وتكلم معي كلام لطيف وجعلني افكر بتغيير رأيي وفوق هذا انا وعدته اني سوف احاول اضافة موقع اكوام الجديد

هذا هو الفرق بين التصرف الايجابي والتصرف السلبي

فهل ترى كلامك يشجعني لكي انتج اكثر ام يشجعني لاهرب أكثر ؟

ثم لو كانت عندك سيارة فيها خلل في الباب او فيها خلل في الموتور او خلل في الإطارات فهل تقول ان السيارة كلها لا تعمل ام تقول فقط هذا الجزء فيه مشكلة ؟

هل تعتقد اني مجنون لكي افحص البرنامج كله وافحص جميع المواقع فقط لأنك قلت كل شيء لا يعمل ... بالعكس عندما استلم هكذا رسائل فأنا بكل بساطة أهملها ... وفوق هذا افكر بطريقة لكي امنع هؤلاء الاشخاص السلبيين من استخدام برنامجي حتى لا يهاجموني بصورة تحطم معنوياتي وتحطم الشعور الإيجابي

**Comment by ellyraf** [comment]
ول ول ول
كل هذا سويت برسالتي الك
يا اخي الفاضل العزيز
اعتذر عن ما بدر مني من خطأ غير مقصود
ويمكن لم احسن التعبير
كنت اقصد عندما فتحت موقع اكوام فقط ولا غير بعض المسلسلات لم تعمل ولمدة كم
ساعة فقط لا غير و بعدها اشتغلت بشكل جداً جميل .
اريد اضيف شغله ايضاً
اقسم بالله العلي العظيم انا لا افتح الا موقعك فقط وفقط ومعتمدة عليه في كل
الافلام والبرامج والمسلسلات العربية والاجنبية
مع انه انا مشتركة في تطبيق قنوات
لكنني لاحظت موقعكم افضل بمراحل كثيرة عن قنوات ( الغير مجانية طبعاً)
وكل شيء جديد اجده عندكم لهذا قررت عندما اكمل اشتراكي لا اجدد الاشتراك معهم
لانه لم انتفع من قنواتهم ولا اشغلها ابداً
بالمختصر المفيد الظاهر صار عندي خوف من فقدان موقعكم الجميل لهذا تسرعت
بالكتابه لكم خوفاً من فقدانها للأبد
وكان يجب ان اتريث حتى اعرف مصدر العطل .
قسماً بالله ثانياً اعتمد بكل مشاهداتي على موقعكم لا غير لهذا ارسلت لكم
و لهذا  ارجو تقبل اعتذاري
والمرات القادمة سوف لن ارسل لكم لسبب بسيط و هو انك بإستمرار تحدًث المواقع
وكل جديد اجده عندكم
اعتذر مجدداً
ولكم مني فائق الاحترام والتقدير والاعتذار

**Comment by emadmahdi** [comment]
شكرا جزيلا

انا احب التواصل وخاصة اذا كان هناك مشكلة بحاجة الى اصلاح

ولكن المشكلة يجب ان تكون محددة ومعروفة واستطيع تجربتها بنفسي لانها الطريقة الوحيدة لكي اعرف وافهم 
ما هي المشكلة بالضبط ... اما قولك ان كل شيء لا يعمل فهذه لا استطيع حلها ولا فهمها لاني لا اعرف الغيب

وللعلم متابعة وتصليح وفحص 15 موقع ليس بالشيء البسيط أو السهل واحتاج وقت كثير لمتابعة الاعطال والمشاكل ولهذا انا ارحب بالشكاوي وارحب بالتواصل معي ولكن بطريقة ايجابية

وانا اسف اذا كنت ازعجتك او اسأت فهمك ... ومرة اخرى اقول شكرا لك على التواصل

**Comment by ellyraf** [comment]
اخي العزيز
والله من شدة تمسكي بموقعكم لهذا اعتقد اخطأت التعبير لأنني واكرر اعتمد
موقعكم فقط لمشاهدة كل مااحتاج من قنوات وبرامج وافلام حتى انني ابلغت كل
معارفي بهذا الموقع تبعكم خاصة ونحن في الاغتراب نحتاج لقنواتكم
هذا تلفزيوني و تطبيقكم الاول لأنه الوحيد الذي نستعمله ولو تلاحظ جنبه تطبيق
قنوات و جنبه تطبيق ماك اكستريم
قسماً بالله لا نستعملهم لانهم لا شيء مقارنة بموقعكم و لدى موقعكم كل جديد
بإستمرار
عكس باقي التطبيقات اللتي لا تهتم بالتحديث واضافة الجديد
لكن للاسف تعرفت على موقعكم مصادفة بعد اشتراكي السنوي لتلك التطبيقات لهذا لا
تزال موجودة على تلفزيوني وبالقريب العاجل ان شلء الله بعد انتهاء الاشتراك
سوف لا اجدد معهم
لهذا احسست بالقلق عندما عطلت عندي اكوام لمدة قصيرة والسبب يعود لي ولجهازي
وليس منكم ولكني تسرعت بالرساله ولجهلي بهذه الامور التكنولوجيه
والان عندي سؤال اذا ممكن اعرف صفحتكم المباركة على الفيس اعتقد يكون افضل اذا
امكن لأنه يوجد اشعار بالتلفزيون عندي يقول من الافضل تغيير الـ skin تبع
الموقع
ولا اعرف كيف
وال شكر وتقدير لكم ولجهودكم القيمة🌹

**Comment by emadmahdi** [comment]
هذه صفحتي على الفيسبوك
https://www.facebook.com/emad.mahdi1

أما الاشتراك المدفوع الذي عندك فانك تستطيع استخدامه في برنامجي وسوف يعطيك تصنيفات وعرض للقنوات والافلام والمسلسلات بصورة اجمل واسهل وأوضح واظن هو نفسه ال
IPTV

انا شخصيا عندي اشتراك مدفوع ولكني استخدم برنامجي لتشغيل القنوات والأفلام والمسلسلات واذا تحتاج مساعدة في تحويل الاكستريم الى رابط 
IPTV
فأذن راسلني على الفيسبوك  لان ال
GitHub
يستطيع كل الناس قراءتها

اما موضوع ال
skin
فهذا هي واجهة لكودي حيث تحصل على شكل للبرنامج يختلف بحسب  ال
skin
الذي تستخدمه وانا اصح باستخدام الواجهة الت انا عملتها وهي
MetropolisEMAD17
MetropolisEMAD18
رقم 18 لكودي 18 ورقم 17 لكودي 17 أو أقل وهناك فيديوهات وشروحات كثيرة على الانترنت تتكلم كيف ممكن ان تغير واجهة كودي علما ان هذه الواجهات موجودة في مخزن عماد وممكن تنزيلها بسهولة من قسم اضافات كودي
addons

**Comment by ellyraf** [comment]
رح اعمل لك follow لانه اريد اتعلم هوايه شغلات
الف شكر الك🌹

**Comment by emadmahdi** [comment]
اهلا وسلا بك
