### ISSUE TITLE
سؤال

### ISSUE THREAD

**Issue by abnhalab** [emadmahdi/KODI#25]
السلام عليكم ورحمة الله وبركاته

يعطيك العافيه اخي عماد من أفضل الإضافات في كودي هو برنامجك سؤالي هو موقع سيما كلوب هل من الممكن أضافته في البرنامج وشكرا.

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله وبركاته
شكرا و الله يعافيك

ابعث لي رابط الموقع لكي افحصه

**Comment by abnhalab** [comment]
مشاء الله رد سريع منك استاذ عماد الغالي هاد هو رابط الموقع 
https://m.cimaclub.com/

واخي عماد سؤال تاني الي حابب يتواصل معك كيف؟

**Comment by emadmahdi** [comment]
الموقع الذي انا وانت نتراسل فيه الان ... هو الافضل بالنسبة لي.

والبديل بالدرجة الثانية هو الفيسبوك
https://www.facebook.com/emad.mahdi1

**Comment by abnhalab** [comment]
تمام اخي عماد الغالي ويعطيك العافيه وما قصرت ولله مبدع كالعاده مشاء الله عليك 
واخر شي فحصت الموقع استاذنا الغالي ؟ يعني في امل يتم اضافة الموقع؟ وشكرا لتعبك وجهودك

**Comment by emadmahdi** [comment]
لا اعرف متى سوف اتفرغ لكي اضيف مواقع جديدة للبرنامج.
