### ISSUE TITLE
هذا فديو للكبار لا يعمل هنا😔

### ISSUE THREAD

**Issue by laith565** [emadmahdi/KODI#27]
**اخي العزيز
شكرا لك ع مجهودك الجميل والجبار المشكلة كثير من الافلام ليست افلام سكس لكن دائما تظهر هذة الرسالة هذا الفديو للكبار هناك افلام في Box Office مصنفة جريمة او غموض لكن لا تعمل .لست اعرف ماهو القياس بين فلم واخر لكن ارجوا حل اذا امكن وشكرا.**

**Comment by emadmahdi** [comment]
برنامجي لا يقوم بتصنيف الفيديوهات ... الموقع الاصلي هو الذي يقوم بتصنيف هذه الفيديوهات

**Comment by laith565** [comment]
شكراً جزيلاً أخي.

**Comment by emadmahdi** [comment]
الشكر لله ... اهلا وسهلا بك
