### ISSUE TITLE
اخي عماد ارجو الرد 

### ISSUE THREAD

**Issue by alepoo** [emadmahdi/KODI#29]
السلام عليكم https://github.com/emadmahdi/KODI/issues/28#issue-571863041
اخي  عماد أنا صار معي نفس المشكلة تجمد الكودي عندي ومحيت البرنامج وهم نزل الاضافة وقت بكبس ع اللينكك تبع التثبيت بجمد الكودي كلو ويرجع بطفي البرنامج وبيرجع بيشغل والاضافة ما بتصير عامل ان الكودي عندي 18.5 ومابغرف شو أعمل

**Comment by alepoo** [comment]
@

**Comment by emadmahdi** [comment]
#28

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله

لكي اعرف ما هي المشكلة .وافهم الذي يحصل عندك ... احتاج منك هذين الملفين
kodi.log
kodi.old.log

اذا عندك كودي ويندوز فتجد الملفين هنا
%APPDATA%/kodi

واذا عندك اندرويد فتجدها هنا
/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp

برنامجي يرسل لي فقط ملف واحد وهو الملف الذي حاليا انت تستخدمه ولكن عندك عندما تعمل تحديث فان الكودي يعلق ولهذا لن تستطيع ان ترسل الملف لي ... والشيء الثاني هو اذا انت بعد التعليق ارسلت لي الملف فاذن سوف يكون الملف فارغ والملف القديم اصبح اسمه مختلف ولهذا انا احتاج منك الملفين الحالي والقديم

**Comment by emadmahdi** [comment]
تلفوني الاندرويد ايضا فيه نفس المشكلة ولهذا مؤقتا لا احتاج ملفات منكم

ان شاء الله سوف احل المشكلة في الاصدار الجديد بعد ان اجد المشكلة

**Comment by emadmahdi** [comment]
من جهتي تم حل المشكلة

أما من جهتك فانت تحتاج تحديث مخزن عماد الى الاصدار الاخير 4.0.2
emad.repository  ( EMAD Repository )  [ v4.0.2 ]

واذا لم تستطع او لم يعمل معك فأذن قم بتحديث المخزن بنفسك وذلك بتنزيل هذا الملف وتنصيبه على كودي
https://github.com/emadmahdi/KODI/raw/master/INSTALL/repository.emad-4.0.2.zip

واذا واجهتك أي مشكلة فجرب ان تراسلني مرة اخرى

**Comment by emadmahdi** [comment]
تم حل المشكلة  وعليه قم بمراجعة مشكلة رقم #28 لمزيد من التفاصيل

**Comment by alepoo** [comment]
اخي نفس المشكلة نزلت النسخة 4.-0-2ونفس الشي

في الجمعة، ٦ مارس ٢٠٢٠ ٠٥:١٠ emadmahdi <notifications@github.com> كتب:

**Comment by emadmahdi** [comment]
تحديث مخزن كودي يحتاج عمليتين

الاولى هي تحديث الاضافة التي اسمها مخزن عماد الى اخر اصدار وهو 4.0.2 وهذه انت عملتها

والثانية هي تحديث محتويات المخزن وهذه تحتاج اما 24 ساعة او اطفاء الجهاز واعادة تشغيله او تمسح اضافة مخزن عماد من كودي وتعيد تنصيبها او تذهب بنفسك الى المخزن في قسم الاضافات وتعمل
check for updates

**Comment by emadmahdi** [comment]
اخر تحديث انا عملته هو ... تحديث اضافة الفيديوهات العربية إلى إصدار رقم 6.0.8  ... فإذا كان عندك اي رقم مختلف ... فاذن انت تحتاج تحديث محتويات مخزن عماد
