### ISSUE TITLE
My donation

### ISSUE THREAD

**Issue by hamer8** [emadmahdi/KODI#3]
I already donated yesterday 14th Nov. for 3 months 9$CAD . But so far the program not yet activated on my device android .and keep on asking for new donations,
Please activate to start re using your  emad program on Kodi.
My email 
hamer8@gmail.com

**Comment by emadmahdi** [comment]
You did not follow the activation procedure ,, when you donated you received a message asking you to send me a message from my program writing in it your email address .. but you did not do that.

To fix this .. send me a message from my program .. and make sure to include your email address to the message.

The below website is the official website for my program

https://arabicvideos2018.fws.store
