### ISSUE TITLE
موضوع افلام للكبار فقط عامل لنا مشكلة وايجي بيست يظهر رسالة خطأ

### ISSUE THREAD

**Issue by hussapril7** [emadmahdi/KODI#3]
السلام عليكم اخ عماد، انا فرحت من شفت اضفت موقع جديد ايجي بيست، ولكن للاسف فرحه ماتمت
دشيت على كذا فلم يعطيني خطأ باسم الدخول وكلمة السر!!!

وايضا دخلت فلم يقول للكبار فقط!!!

اخ عماد ياريت تشيل موضوع للكبار فقط 
لان اغلب الافلام هي بعضها رعب او اكشن فا طبيعي ينحط لها لعمر معين 
كذا موقع بالاضافه مالتك ادش على فلم مايدخل بسبب للكبار فقط
بهالطريقه ماراح اقدر اشوف اي فلم
لان اغلب الافلام تنحط تحت مسمى للكبار فقط لان يكون اكشن او رعب فا طبيعي ينحط تحت تصنيف الكبار
وللاسف هذا الشي مايخليني اقدر اشوف شي بالموقع او الاضافه بشكل عام

فا ياريت تشيل موضوع للكبار فقط لان الافلام تصنيفاتها وايد 
وبعدين انا رجال كبير عمري 28 سنه
يعني احس ماكو فايده اذا كل فلم ادشه يعطيني خطأ للكبار فقط!! يعني ما اقدر اشغل شي وماكو فايده من اضافة الموقع
يا اذا تسمح ياريت تشيل مشكلة للكبار فقط او تحط اختيار انه الفلم للكبار واحنا بوقتها نقرر نوافق نشوفه او نرفض
يعني حط اختياري لنا 
اما جذي مايشتغل شي ولا اقدر اشوف شي لان اغلب الافلام يقول للكبار فقط

انا راح ارفق لك صورتين عن الخطأين
وترا اخ عماد والله فرحت برسالتك وعلى طول رحت شغلت الكودي عشان احدث واشوف شنو ضفت
بس تحبطت من صارت هالاخطاء

عموما اتمنى وضحت الفكره وان شاءالله تشوف حل لها

الصورتين تحت
.
.
![20181101_225731](https://user-images.githubusercontent.com/44403403/47877001-dac36a80-de2b-11e8-96be-85ec77fd2333.jpg)

![20181101_225711](https://user-images.githubusercontent.com/44403403/47877026-ec0c7700-de2b-11e8-97f3-7c10707b0840.jpg)

**Comment by hussapril7** [comment]
صباح الخير، اخ عماد موضوع للكبار فقط مقلل من قوة برنامجك او الموقع بشكل خاص، يعني تخيل اغلب او اكثر الافلام كله تحت تصنيف للكبار فقط!!
يعني جذي ماراح اقدر اشوف شي
يعني اطالع افلام اطفال انيميشن ولا افلام عاديه!! يعني مو منطق
وبعدين هي ليست افلام اباحيه عشان تكون للكبار فقط
ولكن افلام اكشن او رعب طبيعي تكون للكبار بس المستخدم هو له حرية الاختيار اما يشاهد ام لا 
اخ عماد هالشي يقلل من قوة برنامجك كثيرا يعني جد جذي ماراح اقدر اشوف شي بالموقع
ليس فقط بموقع ايجي بيست، اذكر حتى في موقع هلال يوتيوب او هلا سينما لا اذكر بالتحديد ايضا نفس مشكلة للكبار فقط

انا مادري اشلون اوضح لك اكثر
ترا بهالوقت الكل واعي والتكنولوجيا حتى الطفل يعرف فيها ماكو شي صعب 
يعني اضافتك ماراح تخلي الطفل مايشوف شي 
لان بهالوقت كل شي متوفر للاطفال هواتف محمووله يدخلون اي موقع  واي مكان
وحتى الالعاب التي يلعبونها في البلايستيشن وغيرها كلها العاب عنف وحرب
يعني الاضافه هذي ماراح تمنع الطفل من مشاهده اي شي حوله
لان كل شي متوفر ومتاح

انا بنظري موضوع للكبار فقط قلل من جودة الاضافه لان اكثر الافلام التي اريد ان اشاهدها لاتشتغل بسبة هذا الخطأ
وقد اشاهد افلامي من المواقع الرسميه او من الاضافات الاخرى عالكودي 

عموما اخ عماد انا وضحت لك الفكره ولك حرية الاختيار 
ولكن صدقني هذي الطريقه قللت من قوة برنامجك

**Comment by emadmahdi** [comment]
هل لديك مشكلة اخرى قبل ان اغلق هذه الشكوى

**Comment by evanovan** [comment]
please fix this issue . 

to say its for older people but not give away to verify if you are old or not means "NO BODY" old or young will be able to watch movies

**Comment by emadmahdi** [comment]
https://github.com/emadmahdi/KODI/issues/40
