### ISSUE TITLE
الاضافة تعمل بشكل جيد 👍

### ISSUE THREAD

**Issue by hussapril7** [emadmahdi/KODI#30]
شكرا شكرا شكرا اخ عماد 
عادت اضافتك تشتغل من جديد
ولكن لاحظت موقع موفيز لاند ليس موجود لا أعلم السبب!!

عموما حبيب قلبي عندي اقتراح موقعين اشوفهم ممتازين واتمنى تراجعهم
بما انه بعض المواقع في برنامجك ازلتها لعدم اشتغالها

الموقع الاول 
https://alfajertv.com/
هذا الموقع اتوقع فلسطيني يبث خلاله محتوى افلام ومسلسلات عربيه واجنبيه
وايضا يحتوي على بث حي لقنوات بث مباشر خاص بهم
والجميل بالبث انهم يعرضون مبارايات مباشره من دوري الاسباني والانجليزي والاسباني 
تبث المبارايات في توقيت المبارايات

والموقع الثاني 
https://www.mvs4u.tv/
حدثتك عنه سابقا ولكن هالمره الموقع تطور بشكل ممتاز 
حيث اصبح يدعم الموقع سيرفرات خاصه به مثل موقع اكوام
ودائما هذا الموقع يعجبني عند تشغيل الافلام او المسلسلات سريع بشكل ممتاز حتى عندما يكون النت لدي ضعيف

بس تسلم يالحبيب وشكرا لك دائما وابدا 🌹

**Comment by emadmahdi** [comment]
الشكر لله
