### ISSUE TITLE
رابط موقع أكوام تغير

### ISSUE THREAD

**Issue by hedibekir** [emadmahdi/KODI#31]
https://akwam.net أخ عماد لقد تم تغيير موقع أكوام إلى الرابط هذه الأيام و لذلك روابط الأفلام التابعة لأكوام لم تعد تشتغل

**Comment by emadmahdi** [comment]
موقع اكوام عملوا تصميم جديد لموقعهم وبرنامجي يفهم فقط التصميم القديم

علما ان التصميم القديم لا زال يعمل ولكن ليس مع جميع الافلام

سوف احاول ان اضيف التصميم الجديد لبرنامجي

انتظر التحديث القادم

**Comment by emadmahdi** [comment]
موقع اكوام قاموا بتغيير كامل لتصميم وشكل موقعهم ... وهذا يحتاج مني برمجة كاملة لموقع اكوام من الصفر ... ولا اظن اني سوف اقوم بهذا قريبا
