### ISSUE TITLE
السلام عليكم اخي عماد الغالي

### ISSUE THREAD

**Issue by abnhalab** [emadmahdi/KODI#32]
اخي عماد الغالي عندي مشكله في موقع اكوام عندما أحاول فتحه يأتيني رسالة كالإتي هذا الموقع فيه نوع من الحجب ضد كودي مصدره الانترنت الخاص بك ورقم الخطاء 503  انا في دولة السويد هل هناك حل وشكرا لتعبك وجهودك

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله

موقع اكوام تقريبا انتهى لانهم غيروا تصميم موقعهم بالكامل ... واظن انهم قريبا سوف يوقفون عمل الموقع القديم

موقع اكوام الجديد يحتاج مني اعادة برمجة من الصفر لموقعهم بالكامل ... ولا اظن اني سوف اقوم بهذا العمل قريبا
