### ISSUE TITLE
Error: URLRESOLVER Resolver failed

### ISSUE THREAD

**Issue by mufeed99** [emadmahdi/KODI#33]
After the update this error starting 
![IMG_20200320_201229](https://user-images.githubusercontent.com/62440642/77188560-3eb10680-6ae7-11ea-822c-297cb1ec5b4d.jpg)

**Comment by emadmahdi** [comment]
هذه الرسالة معناها ان الفيديو المطلوب اما غير موجود واماالرابط خطأ ... وعادة تكون من الموقع الاصلي وليست من برنامجي

جرب ان تشغل الفيلم الذي يعطيك هذه الرسالة عن طريق المتصفح  ... واذا عمل الفيديو على التصفح ولم يعمل على برنامجي فاذن اخبرني لكي اصلح المشكلة ... اما اذا كانت المشكلة موجودة في المتصفح فانا لا استطيع عمل شيء لان المشكلة من الموقع الاصلي وليست من برنامجي

**Comment by mufeed99** [comment]
شاكر لك اول شي على اجمل واروع ادد اون فعلا انتا رائع ومبدع 

جربته يا صديقي وشغال على الوب براوسر اعتقد الموديل تبع اليورل ريسولفر لما انعمل ابدين ل الكودي الجديد صار فيه مشكله 
بعطيك الف صحه وشكرا لك ولهاهتمامك تابع العمل الرائع

**Comment by emadmahdi** [comment]
انا جربته من جهتي ويشتغل معي بدون مشكلة ... اظن انك اما تحاول ان تفتح فيديو جديد أو تحتول ان تفتح فيديو تم سمحه من السيرفرات العامة أو جهازك يحتاج ان يحدث اضافة اسمها
URLResolver

جرب ابحث عن فيلم قديم ... وحاول ان تشغله في جميع مواقع برنامجي ... فاذا اشتغل معك على اي موقع من 
 مواقع برنامجي فاذن الاضافة وايضا برنامجي يشتغلون معك والمشكلة من خارج برنامجي

ابعث لي اسم الفيديو واسم الموقع واسم السيرفر الذي اشتغل معك على البراوسر ولم يشتغل على برنامجي
