### ISSUE TITLE
TVADDONS is suspicious

### ISSUE THREAD

**Issue by Sovilor** [emadmahdi/KODI#34]
Hello, it's just an honest advise because i like your Addon.
Having ATVADDON.CO as one of the dependencies of your addon is a very suspicious thing and it's enough reason for a lot of users to remove your addon of their Kodi, because of the very vad reputation that Tvaddon.co has.
One more thing, i hope that you use ResolveURL instead of URLResolver. No trustful Addon using it anymore.
I hope you do that later, keep your addon away of tvaddon.co and anything related to them or you will be effected by their bad reputation of hacking and mining.

Thanks.

**Comment by emadmahdi** [comment]
Hello, I appreciate your advice but i would like to know the reason behind the changes you requested.

1. Why you think that TVADDONS is suspicious ?!

2. Why you think i should use ResolveURL ?!

**Comment by Sovilor** [comment]
@emadmahdi Hello, 
The story of Tvaddon scandals of hacking and mining is long, i will make it short and you do some searching for all the details.

Since the lawsuit in Canada 2018 against Tvaddon.co, they announced Bankrupt, then started to play a dirty game by forcing install their repo and some of their addons in Kodi and later they started to fork dead popular addons to force install their repo and their addons, just to become popular again to make money of advertising on their website. And here the hate against them from Kodi users started, then a scandal of hacking and mining showed up, at that poilnt they lost the trust of all Kodi users.
That's why it's really a very bad idea to have their repo as one of dependencies in your Addon.

Now about the URLResolver, it's fine to keep it in dependencies, that can be understandable, but the problem is URLResolver update will force install indigo and that is something all users hate and considered suspicious.
That's why it's better to use ResolveURL + OpenScrapers like all the good reputation Addons do.

I am in some Kodi Addon groups but i can't recommend your Addon to any user looking for Arabic content just because your Addon will install tvaddon.co repo, all the advanced user will attack me if i did.

Keep Up The Good Work.

**Comment by emadmahdi** [comment]
Thanks for the details.

I already moved to ResolveURL but i have a question ... I can see their is two github repositories for ResolveURL ... both being updated lately and they both working ... but one is v5.0.38 and the other v6.4.97 ... do you know which one i should use in my addons ... they both claim they belongs to jsergio ?!

v6.4.97 - have few extra resolvers
https://github.com/fanfilm/repository.fanfilm/tree/master/zips/script.module.resolveurl

v5.0.38
https://github.com/jsergio123/zips/tree/master/script.module.resolveurl

**Comment by emadmahdi** [comment]
Update:
I contacted "jsergio" and asked him about his "ResolveURL" addon and he confirmed that his addon is the one in his repo v5.0.38

**Comment by Sovilor** [comment]
Very good news, thank you. 
You’re doing a great job.

**Comment by emadmahdi** [comment]
As i know TVADDONS have two repositories:

TVADDONS.CO Resolvers Repository
TVADDONS.CO Add-on Repository

In my addon i was using only the second one because it does not force "Indigo" installation.

Question ... Is it harmful to keep the repository installed on users machines ... I am thinking of offering a deletion of the repository "TVADDONS.CO Add-on Repository" but i don't really think it worths the work nor the worry.

**Comment by Sovilor** [comment]
You are right, No worries, I'm sure, most of users already removed it.

**Comment by emadmahdi** [comment]
Hi @Sovilor ,
Do you know any url resolver that can do these websites:
.
vidshare
vidhd
vidfast
videobin
vidbm
jawcloud

**Comment by Sovilor** [comment]
Update from jsergio on transfer of resolvurl:

Gujal has officially took over resolveurl with my consent. Anyone with a repo can include his resolveurl repo with theirs to distribute updates automatically to their users.

Twitter annoucment
https://twitter.com/jsergio123/status/1243039935269146624?s=20

gujal Github location
https://github.com/Gujal00/smrzips

**Comment by Sovilor** [comment]
@emadmahdi sorry no, but you can open an issue on openscrapers project (check it out) to ask a question or to make a suggestion. And your skills can be useful for them too.
There are very humble developers in there, like Tikipeter (Fen) and 123Venom (Venom) and reddit-reaper.

**Comment by emadmahdi** [comment]
ok, thank you @Sovilor 
I will check with the new developper ... I was thinking to move to "youtube-dl" but it looks so slow compared to other addons.

**Comment by emadmahdi** [comment]
as for "OpenScrapers" it is almost empty if compared to resolveurl & urlresolvers.
