### ISSUE TITLE
Shahid4u Issue

### ISSUE THREAD

**Issue by m7mdcc** [emadmahdi/KODI#36]
السلام عليكم 

كيفك اخوي عماد 

في عندي مشكله اشوف الناس يواجهوها كمان اللي هي 
resolveurl failed 

مثال عندك الرابط هذا

https://ww.shahid4u.net/watch/%D9%81%D9%8A%D9%84%D9%85-bloodshot-2020-%D9%85%D8%AA%D8%B1%D8%AC%D9%85-%D8%A7%D9%88%D9%86-%D9%84%D8%A7%D9%8A%D9%86-5

كل السيرفرات شغاله على الموقع

لكن بالبرنامج ولا سيرفر شغال

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله

سوف افحص المشكلة وارجع لك

**Comment by m7mdcc** [comment]
ما ادري ليش صار الرابط غلط لكن هو فيلم 
bloodshot 
https://ww.shahid4u.net/search?s=bloodshot

**Comment by emadmahdi** [comment]
المشكلة ليست من برنامجي ... انا استخدم برنامج شخص ثاني وظيفته أن يقوم بترجمة بعض روابط الفيديوهات 
 الخارجية وهذا البرنامج للأسف يحتاج الى تحديث من صاحبه الأصلي

سوف ابحث عن بدائل لهذا البرنامج ولكن للاسف الخيارات عندي قليلة ... علما ان المشكلة تخص فقط بعض الروابط الخارجية وليس جميع الروابط ... وانا اتوقع ان صاحب البرنامج سوف يعالج المشكلة قريبا ولكني لا اعرف متى سوف يحدث هذا سوف احاول ان اراسله عسى ولعل يستعجل بايجاد الحل المناسب

انا اشكرك كثيرا على التنبيه لهذه المشكلة

**Comment by m7mdcc** [comment]
اتوقع حسب اللي اعرفه اغلب الاددونز بيستخدمو 
urlresolver or resolveurl 
https://github.com/jsergio123/script.module.resolveurl
شفتك ذكرت هذا السكربت بأحد المشاكل

نحن من نشكرك على هالعمل الرائع 

اذكر لما صارت مشكله اكوام شفتك رديت انه ما حيكون عندك وقت تعدل  للموقع الجديد لكن ماشاء الله ايام  وكان التحديث موجود 

اسمحلي اطلب منك طلب تحط رابط دعم لك , وهذا اقل شي ممكن نقدمه لك

**Comment by emadmahdi** [comment]
صحيح المشكلة هي في 
resolvers
انا جربت الاثنين التي انت ذكرتها والاثنين لا تعمل ... سوف احاول البحث عن برامج اخرى تقوم بنفس الوظيفة ... واذا انت تعرف بعضها فارسل لي اسمها او الرابط لها لكي اجربها

**Comment by m7mdcc** [comment]
انا خبرتي بالبايثون قليله . بس جربت هذا مثلا 
https://github.com/ytdl-org/youtube-dl ؟
هذا يعمل على كثير من المواقع

**Comment by emadmahdi** [comment]
هذا من اسمه خاص باليوتيوب ... وانا صنعت لليوتيوب واحد في داخل برنامجي افضل من هذا بكثير

**Comment by m7mdcc** [comment]
> هذا من اسمه خاص باليوتيوب ... وانا صنعت لليوتيوب واحد في داخل برنامجي افضل من هذا بكثير

هو اسمه 
Youtube-dl

لكن يحمل من مواقع كثيره 



؟اول مره تسمع عنه

**Comment by emadmahdi** [comment]
انا يهمني ان يكون قادر على ان يجلب روابط السيرفرات التي تستخدمها مواقع برنامجي مثل هذه:
.
vidshare
vidhd
vidfast
videobin
vidbm
jawcloud

**Comment by m7mdcc** [comment]
انا شايف التحديث الاخير ما صار يشغل ولا اي شي :(

**Comment by emadmahdi** [comment]
كيف عرفت ان
youtube-dl
يستطيع ان يشغل هذه المواقع

**Comment by emadmahdi** [comment]
واضيف ايضا ... لكي تتأكد ان ال
external resolver
يعمل في برنامجي ... ادخل على شاهد فوريو وشغل الفيلم
StarDog and TurboCat 2019
ثم جرب السيرفر 
ok
اذا لم يعمل فاذن عندك مشكلة في
resolveurl
حاول ان تمسحه وتنصبه من جديد او امسح الاعدادت الخاصة ب
resolveurl
تجدها في مجلد اسمه
userdata\addon_data\script.module.resolvurl

**Comment by emadmahdi** [comment]
اما قولك التحديث لا يشغل اي شي ... اذا تكرر منك هذا القول فاني لن اجيبك نهائيا لانك تحبطني وتجعلني اكرهك واكره ان اقوم باي تحديث وايضا اقول لك اذا برنامجي لا يعمل معك فاذن اتركه وابحث عن غيره ... انا غير مستعد ان اساعد شخص يقول ان برنامجي كله لا يعمل ... وقد ايضا اقوم بمنعك ان تشستخدم برنامجي نهائيا

المرة القادة حدد بالضبط ما هي المشكلة ... حددها بالتفصيل الممل 
اسم الموقع
نوع الفيديو
اسم الفيديو
اسم السيرفر
من اين شغلته

وللعلم التحديث الذي بطل يشتغل هو ليس من برنامجي ... لان
resolveurl  وايضا   urlresovers
الاثنين قاموا بالتحديث البارحة الثلاثاء 24 اذار مارس

وللعلم فان المبرمج ل
resolveurl
بدأ فعلا ببرمجة المواقع التي انا ارسلتها له

وكما قلت لك اذا برنامجي لا يكفيك فاذن امسحه وابحث عن غيره

**Comment by emadmahdi** [comment]
انت ضيعت وقتي واذيتني لان
youtube-dl
ما يقدر يفتح المواقع التي انت قلت عنها .. فقط يفتح واحد منها وهذا الرابط حتى تتأكد بنفسك
http://ytdl-org.github.io/youtube-dl/supportedsites.html

**Comment by m7mdcc** [comment]
حقك علي إذا ضايقتك او ضيعت وقتك ، وبالعكس ما كان قصدي تحطيمك او ايذاءك 

بالفعل شيكت الان على youtube-dl

ما يشغل الا واحد من المواقع المذكوره

انا اعتذر لما بدر مني من اخطاء السموحه منك

لكن ارجو مراجعه نبره وطريقه تواصلك مع الاخرين لا اعلم 
 ماهي  ظروفك او مدى انشغالك ممكن ان تكون السبب لهذا الشيء
اعتذر مره أخرى

**Comment by emadmahdi** [comment]
انا لا اتحمل كلمة ... كل شي لا يشتغل ... فعلا انا ردة فعلي عنيفة تجاه هذه الكلمة ... وهذا من حقي

انا اقضي وقت كثير احاول ان اوصل البرنامج الى مستوى اعلى وخدمة أفضل ومشاكل اقل ... وبس يجي شخص يقول لي ان عملي كله ووقتي وجهدي نتائجها صفر ... فمن حقي ان اثور وان ارد بعنف ... لان برنامجي فيه 15 موقع وانا استخدمه لنفسي ولا يهمنهي كثيرا اذا موقع او خمسة مواقع لا تعمل لان باقي عندي عشرة تعمل بدون مشاكل ... وفوق كل هذا ياتي شخص وبكل بساطة يحطم معنوياتي والمضحك انه يتوقع اني سوف اصلح البرنامج بعد ان يضايقني ويحبطني بكلامه ويجعلني اكره نشر اي شيء ... انا استطيع ببساطة ان اوقف نشر التحديثات واعملها لنفسي فقط.

اما
youtube-dl
فانا البارحة ضيعت عليه 5 ساعات تجربة وفحص وتحديث وحل مشاكل لكي استطيع استخدامه في برنامجي وبعد هذا اكتشفت ان كلامك غير صحيح رغم اني أستطت ان اضيف اليه 3 مواقع إضافية ومع الاول اصبح المجموع 4 مواقع تعمل بهذا البرنامج من مجموع 6 مواقع في شاهد فوريو ... ولكن هذا معناه ان اوفر نسخة خاصة من 
youtube-dl
واكون انا مسؤول عن تحديثها ... يعني شغل وبرمجة ومسؤولية انا غير مستعد لها ... وفوق هذا هو بطيء جدا مقارنة ب
urlresolver  او   resolveurl

وبعد كل هذا التعب والساعات وتضييع الوقت اكتشفت ان كلامك غير صحيح وان 
youtube-dl
 ينفع لفتح موقع واحد من ال 6 مواقع التي فيها مشاكل في شاهد فوريو

**Comment by emadmahdi** [comment]
السلام عليكم

جرب الاصدار الاخير
v6.3.0
اضفت اليه ثلاثة
resolvers
وجميعها تعمل مع بعض ... مع ملاحظة ان بعض السيرفرات قد تتأخر ولكن على الاقل أكثرها سوف يشتغل

**Comment by emadmahdi** [comment]
السلام عليكم

جرب الاصدار الاخير
v6.3.0
اضفت اليه ثلاثة
resolvers
وجميعها تعمل مع بعض ... مع ملاحظة أن بعض السيرفرات قد تتأخر ولكن على الأقل أكثرها سوف يشتغل

اذا لسه فيها مشكلة اذن اخبرني بالتفصيل بدون ان تقول كل شيء لا يعمل لاني قضيت على إصلاحه تقريبا عشرة ساعات ... والمفروض اني اشعر شعور ايجابي وافرح بأعمالي ... أما الإحباط فأنا من النوع الذي يهرب من كل شيء عندما اواجه احباط يعني ممكن ببساطة أتوقف اعمل تحديثات واعملها فقط لنفسي بدون نشرها على الانترنت

**Comment by badisking18** [comment]
السلام عليكم
اولا اوجه شكري الخاص للاخ عماد مهدي لكل ما يقدمه 

ثانيا اود ان اسألك عند محاولة تشغيلي للضافة تخرجلي 

السيرفر لم يعمل
جرب سيرفر غيره
Error :EXTERNAL_RESOLVER_1 Failad
Error :EXTERNAL_RESOLVER_3 Failad

ممكن حل الاخ عماد؟؟؟

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله

اخي الشكر لله ... وانت مشكور على تشجيعك لي

هناك كثير روابط كثيرة لا تعمل ... وعادة المشكلة من الموقع الاصلي وليست من برنامجي ... واذا اردت ان تتاكد اكثر فاذن حاول ان تشغل نفس الفيلم ولكن باستخدام المتصفح بدلا من استخدام برنامجي ... واكون ممنون لك اذا وجدت افلام تشتغل في الموقع الاصلي ولا تشتغل في برنامجي

نعم في بعض الحالات تكون هناك فعلا مشكلة وهي انك ترى ان برنامجي لا يستطيع فتح جميع انواع السيرفرات ولهذا بعضها تفشل ... وهذه ايضا ليست بسبب برنامجي ... ولا استطيع عمل اي شيء لها ... لانها وظيفة برامج اخرى يستخدمها برنامجي ... وهذه البرامج مشكلتها انها أيضا لا تفتح جميع السيرفرات الموجودة في العالم

**Comment by badisking18** [comment]
تحية لك الاخ عماد شكرا جزيلا أخي
ممكن نصائح تقدمهم لي 
لدي استفسار أخر بما انه لدية خبرة في المجال 
هل من طريقة لعمل real debrid اتوماتيكيا
انا استعمل إضافة gaia
ودائما يظهر هذا الاشعار 
Your real debrid premium statut has expired
هل من حلول أخي 
تقبل تحياتي

**Comment by badisking18** [comment]
او تنصحني بإضافة torrentتجلب المسلسلات والافلام بجودة عالية تشتغل بدون مشاكل

**Comment by emadmahdi** [comment]
السلام عليكم @badisking18 
انا لا اعرف شيء عن هذه الاضافة ولا اعرف شيء عن ال
real debrid
ولا استخدمها في برنامحي

اما الخطأ الذي انت كتبته ... انا افهم منه ان اشتراكك في هذه الخدمة انتهت وتحتاج الى تمديد اشتراكك ... او تحتاج ان تغير اسم الدخول وكلمة السر
