### ISSUE TITLE
موقع اكوام الجديد

### ISSUE THREAD

**Issue by palfal** [emadmahdi/KODI#37]
مسلسلات مصنفة لا تعمل في موقع اكوام الجديد

**Comment by emadmahdi** [comment]
السلام عليكم
انا وجدت مشكلة في التنقل بين الصفحات وتم حل المشكلة في الاصدار الجديد

اما اذا لم تكن هذه هي المشكلة فأذن ابعث لي تفاصيل اكثر عن المشكلة

**Comment by emadmahdi** [comment]
وشكرا على التنبيه

**Comment by palfal** [comment]
وعليكم السلام والرحمة

 شكرا على حل المشكلة

تحياتي

**Comment by emadmahdi** [comment]
تم نشر الاصدار الجديد
