### ISSUE TITLE
مشكله روابط لا تعمل 

### ISSUE THREAD

**Issue by aloneme003** [emadmahdi/KODI#38]
سلام عليكم

استاذ عماد مهدي اشكرك على الاضافه الجميله

عندي مشكله في روابط اكوام قبل يومين كانت تشتغل والان تعطي رساله خطا 

ممكن تفيدني 

شكرا لك

**Comment by emadmahdi** [comment]
شكرا لك ... لقد وجدت مشكلة فعلا في موقع اكوام القديم ... عند تشغيل فيلم باستخدام سيرفر خاص اكوام ... فان الفيلم لا يعمل ... وتم اصلاح المشكلة وانتظر مني الاصدار الجديد للبرنامج قريبا

اذا كانت مشكلتك مختلفة فاذن ابعث لي تفاصيل اكثر مثلا ابعث لي
اسم الموقع
واسم الفيلم
واسم السيرفر
واسم القائمة التي اوصلتك للفيلم الذي فيه المشكلة

أو ابعث لي رسالة "مشكلة" من قائمة خدمات البرنامج مع ارسال سجل الاستخدام والاخطاء ... ولا تنسى ان تكتب تفاصيل المشكلة

**Comment by aloneme003** [comment]
مساء الخير ..
شكرا لك استاذي على الرد .. بالنسبه للمشكله
الموقع / اكوام القديم
اسم المسلسل باب الحارة الجزء الخامس
اسم القائمه / المسلسلات العربية - ارشيف المسلسلات العربية - الصفحة رقم 6

شكرا لك

في أربعاء، 1 أبريل، 2020 في 3:17 ص، كتب emadmahdi <notifications@github.com

**Comment by emadmahdi** [comment]
تم اصلاح المشكلة وانتظر مني الاصدار الجديد للبرنامج قريبا

**Comment by aloneme003** [comment]
مساء الخير ..
للاسف المشكله لازالت مستمرة ):

**Comment by emadmahdi** [comment]
انا لم انشر الاصدار الجديد ... انا قلت انتظر مني قريبا

**Comment by emadmahdi** [comment]
تم نشر الاصدار الجديد 6.3.1 ... جربه الان

**Comment by aloneme003** [comment]
سلام عليكم استاذي الفاضل
اسف على الاطاله واذا ازعجتك

هذا الاصدار حاولت احدثه من خلال المستودع الخاص فيك ولكن لم يتوفر للتحديث لا
اعلم ماهي المشكله ..!

في جمعة، 3 أبريل، 2020 في 12:00 ص، كتب emadmahdi <notifications@github.com>:

**Comment by emadmahdi** [comment]
في قسم الاضافات حاول ان تجد مخزن عماد او اي مخزن ثاني ثم اضغط عليه بالماوس ونفذ
Check for updates
واذا لم تجدها فاذن حاول ان تضغط الماوس او الاسهم الى جهة اليسار لكي تجد وتنفذ
Check for updates
ثم اصبر قليلا ثم حاول ان تحدث برنامجي

أو اغلق كودي او اطفي الجهاز ثم شغله مرة اخرى ... ثم اصبر قليلا ثم حاول ان تحدث برنامجي

او انتظر 24 ساعة وسوف يقوم المخزن بتحديث نفسه ... ثم اصبر قليلا ثم حاول ان تحدث برنامجي

**Comment by emadmahdi** [comment]
المخزن بلغة كودي اسمه
Repository

**Comment by aloneme003** [comment]
سلام عليكم استاذي الفاضل شكرا لك المجهود واسفين ع الازعاج ..

الاضافه اشتغلت ..

في جمعة، 3 أبريل، 2020 في 12:36 ص، كتب emadmahdi <notifications@github.com>:
