### ISSUE TITLE
توقف التثبيت

### ISSUE THREAD

**Issue by Allaeddine30** [emadmahdi/KODI#39]
اخ عماد واجهت مشكلة اثناء تثبيت اللاضافة بحيث عند 40% وبالضبط اثناء تثبيت YouTube-dl control يفشل في تثبيته ويتوقف التثبيت كليا ارجو حل هذي المشكلة وشكرا

**Comment by emadmahdi** [comment]
انا لا اعرف ماذا يجري معك بالضبط ... ولكني أظن ان كودي يستخدم برنامجي ولهذا لا يستطيع ان يغير ملفات برنامجي ... ولهذا اطلب منك ان تجرب تغلق كودي تماما ... ثم تشغل كودي وابدأ بتثبيت جديد بدون ان تستخدم برنامجي نهائيا

وهناك طريقة اخرى وهي ان تمسح ملفات برنامجي بالكامل من كودي بالذهاب الى الملفات ومسحها ثم تحاول ان تقوم بتثبيت جديد لبرنامجي

وهناك طريقة ثالثة وهي ان تمسح الاضافة من قسم الاضافات وترجع تنصب الاضافة مرة اخرى

اذا استمرت المشكلة حاول ان تقرأ سجل الاستخدام وترى ما هي المشكلة بالضبط

واذا كل هذه المحاولات فشلت فاستخدم برنامجي واذهب الى قائمة الخدمات وابعث لي سجل الاستخدام ولكن بعد ان تحصل المشكلة وليس بعد ان تشغل كودي

**Comment by emadmahdi** [comment]
جرب الان الاصدار الجديد 6.3.1 عسى ولعل ان تنتهي مشكلتك بهذا الاصدار الجديد

**Comment by emadmahdi** [comment]
هل انتهت مشكلتك ؟
