### ISSUE TITLE
Egybest problem

### ISSUE THREAD

**Issue by firasville** [emadmahdi/KODI#4]
أخ عماد ظهرت مشكلة مؤخراً في اضافتك
خاصة بموقع egybest
حيث يطلب وضع اليوزر و اباسوورد بشكل صحيح على الرغم اني مدخلهم بشكل صحيح
و قد ذهبت للموقع و ادخلتهم و لم اجد مشكلة

ربما قاموا بنوع من التشفير فهل للمشكلة حل؟؟

**Comment by emadmahdi** [comment]
vشكرا للتنبيه ... تم حل المشكلة في الاصدار الاخير 3.6.2

**Comment by firasville** [comment]
شكراً على مجهودك عزيزي عماد

**Comment by emadmahdi** [comment]
الشكر لله
