### ISSUE TITLE
هذا فديو للكبار وأنا منعته

### ISSUE THREAD

**Issue by evanovan** [emadmahdi/KODI#40]
Hi, 

I think this add-on is awesome . you guys are doing a great job, 

I get this message recently (didnt have it  before) that the movie is for old people and i banned it . 
the issue is these movies are not sexual or pornographic . its just horror or action movies. 

example movie : a new movie called " the invisible man" . this one get banned. 

how we can insert our age so we can watch regular action or horror movies ?

this is for Akwam section.   Akwam site itself doesnt have this restriction . 

much respect to you for the great work

**Comment by emadmahdi** [comment]
my program does not give any rating for any video ... I only use what the original website rate their videos.

until now i did find any way to distinguish who is adult and who is not ... if you have any way to do that then let me know ... may be their is a website that do this function !!

as for Akwam website ... I only banned around 20% of the movies not 80% ... I consider 20% acceptable percentage and even 30% it still ok with me ... you can verify that percentage by using my addon to play movies of any specific year  without using any filter nor using sorting and definitely not using any categorization.

my addon is for families not for adults only ... I took that decision since day 1 and i will try my best to keep this decision as is unless in situations where the videos either rated wrong or more that 50% of their videos are banned.

**Comment by evanovan** [comment]
thanks for the reply. I get your point. 

You said this is been there since day one ? i only start having this issue when the "new akwam site" opened and added to your list of sites.  

Are you sure its the same issue ?

this issue ban every single horror movie , every movie related to zombies, every movie that has violence or shooting ( action movies) .  the only thing watchable is Disney movies and few family movies. 

I only say this because Akwam always have the best quality and direct good links. 

can you tell me more about their rating system ?  does it say : " violence"    / " horror" / "pornographic"  ?

**Comment by evanovan** [comment]
is there a way to make banning optional ? for example for people with families who want family related movies they can enable / disable a knob for parental control .

parental control option is what all streaming sites do to solve this issue .

**Comment by emadmahdi** [comment]
two days ago ... I checked 30 movies from akwam website and the banned movies were only 6 movies ... I suggest you count them yourself before sending my wrong statements ... help yourself by counting the percentage yourself.

as for the old akoam ... yes their website did not have rating ... but when they added it ... i simply started using it in my program.

please do not message me before you count the banned movies and count the percentage.

**Comment by evanovan** [comment]
maybe we are not seeing the same thing,

ok .. go to akwam new site , choose horror english movies  , just PAGE 1
start from the 4th one . all this list says "only for mature  people and i banned it 

Haunt
Abigail
luz
vivarium
the orchard
doll house
the hunt
the invisible man
the thing
nefarious
the grudge
swallow
the dare

please  just confirm that these movies dont work for you as well . so i know we are talking about the same thing . 

I apologize for the inconvenience

**Comment by emadmahdi** [comment]
i told you not to use any kind of categorization ... you count the bad movies in category called bad movies !!!!!!!!!! !!!!!!!!! !!!!!! !!!!!!!!!!! !!!!!!! !!!!!!!

**Comment by emadmahdi** [comment]
I am trying not to laugh but i could not.

**Comment by evanovan** [comment]
let the users decide whats good or bad . people have different tastes . some of these movies are top box office movies with bug budgets. 

Thanks for your help anyways . appreciate your time

**Comment by emadmahdi** [comment]
imagine you go to a porn website and then you complain that 90% of them are banned !!

you should count a generic list that includes all categories of movies not just a specific categorized list.

**Comment by evanovan** [comment]
can you add a parental control option so people can enable or disable ?

**Comment by emadmahdi** [comment]
i made this program for myself but then i decided to share it as is ... so if someone does not like my decision then simply i advice them to delete my program and find another program that suits their tastes ... or simply i can stop updating the program and it will die automatically ... I don't care if people use it or not ... I make it for myself.

**Comment by evanovan** [comment]
understood , i wasn't aware you made it for yourself . 

thanks . i will close this issue .
