### ISSUE TITLE
please upload UFC fights . many fans here like to watch them 

### ISSUE THREAD

**Issue by evanovan** [emadmahdi/KODI#41]
please upload a section for UFC fights. it would be a great addition

**Comment by emadmahdi** [comment]
what is ufc fights ?

personally ... I hate wrestling/football/soccer if this is what you mean ... and i will never add a whole website for these kind of videos ... but if these videos comes inside another regular movies/serieses website then yes i can try to make it available if it does not need any extra programing/efforts from me.

**Comment by evanovan** [comment]
its like boxing , martial arts . very popular . 

most of streaming sites have them . 


[https://ibb.co/sHB1dyp](url)

**Comment by emadmahdi** [comment]
i do not support these kind of videos ... for me they are for adults only and should be banned from my program ... i think the world have enough violence and does not need me to spread more violence.

**Comment by evanovan** [comment]
i respect your opinion . thanks for looking into the subject
