### ISSUE TITLE
مشكل في مسلسلات 

### ISSUE THREAD

**Issue by ikhlefamine** [emadmahdi/KODI#42]
السلام عليكم هناك مشكل في موقع اكوام الجديد في المسلسلات شكرا

**Comment by palfal** [comment]
عندي شغال اخي الكريم

**Comment by ikhlefamine** [comment]
اخي موقع اكوام  الجديد لايشتغل قمت باعادة تشغيل نفس المشكل

**Comment by emadmahdi** [comment]
شكرا للتنبيه ... تم حل المشكلة ... جرب الاصدار الجديد رقم
v6.3.3

**Comment by ikhlefamine** [comment]
اخي مشكور على المجهودات تم حل المشكل
