### ISSUE TITLE
مشكلة في تصفح القائمة

### ISSUE THREAD

**Issue by palfal** [emadmahdi/KODI#43]
السلام عليكم اخي عماد

يوجد مشكلة في تصفح القائمة في عرب ليونز

قسم الافلام او المسلسات

 موقع عرب ليونز -> مسلسلات
 موقع عرب ليونز -> افلام

error 502: bad gateway

لكم جزيل الشكر والتقدير

**Comment by emadmahdi** [comment]
شكرا للتنبيه ... تم حل المشكلة ... جرب الاصدار الجديد رقم
v6.3.3

**Comment by palfal** [comment]
مشكور الان يعمل بشكل ممتاز

تحياتي

**Comment by emadmahdi** [comment]
الشكر لله

اهلا وسهلا بك
