### ISSUE TITLE
موقع اكوام الجديد لا يعمل

### ISSUE THREAD

**Issue by ikhlefamine** [emadmahdi/KODI#44]
السلام عليكم اخي موقع اكوام الجديد لا يعمل

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله
شكرا على التنبيه
انتظر مني الاصدار الجديد قريبا جدا

**Comment by ikhlefamine** [comment]
شكرا اخي على المجهودات

**Comment by emadmahdi** [comment]
الشكر لله ... جرب الاصدار الجديد
v6.4.0

**Comment by ikhlefamine** [comment]
شكرا اخي على المجهودات

**Comment by ikhlefamine** [comment]
تم حل المشكل

**Comment by emadmahdi** [comment]
الشكر لله ... اهلا وسهلا بك
