### ISSUE TITLE
عادت المشكله من جديد

### ISSUE THREAD

**Issue by aloneme003** [emadmahdi/KODI#45]

**Comment by emadmahdi** [comment]
لم افهمك ... اي مشكلة تقصد ؟

**Comment by aloneme003** [comment]
سلام عليكم

اسف استاذي الاضافه اشتغلت بعد فترة وحاولت احذف للموضوع بس ماقدرت ..


في اثنين، 6 أبريل، 2020 في 9:53 م، كتب emadmahdi <notifications@github.com>:

**Comment by emadmahdi** [comment]
اهلا وسهلا بك

**Comment by aloneme003** [comment]
سلام عليكم مساء الخير استاذ عماد
هل في الاضافه مشكله !!

لما ادخل اضافه اكوام القديم واختار مسلسل باب الحارة يعطي رساله خطا في
الروابط !!

في ثلاثاء، 7 أبريل، 2020 في 8:07 ص، كتب emadmahdi <notifications@github.com

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله وبركاته

ممكن اعرف اي جزء من باب الحارة ورقم الحلقة ؟

انا جربت الحلقة الاولى من الجزء العاشر ولم ارى المشكلة ولا اعرف هل التعديلات التي انا عملتها حلت مشكلتك ام ما تزال موجودة ؟

**Comment by aloneme003** [comment]
الجزء الرابع كامل عندي تقريبا جميع الاجزاء

في أحد، 7 يونيو، 2020 في 10:31 م، كتب emadmahdi <notifications@github.com>:

**Comment by emadmahdi** [comment]
الجزء الرابع
الحلقة 1 والحلقة 23 عندي تعمل الان

**Comment by aloneme003** [comment]
جربت الان للاسف لم يعمل عندي .. ):

في أحد، 7 يونيو، 2020 في 10:39 م، كتب emadmahdi <notifications@github.com>:

**Comment by emadmahdi** [comment]
اذن انتظر الاصدار الجديد قريبا

**Comment by aloneme003** [comment]
شكرا لك الروابط تعمل 🌹

في أحد، 7 يونيو، 2020 في 10:50 م، كتب emadmahdi <notifications@github.com>:

**Comment by emadmahdi** [comment]
الشكر لله

في المرات القادمة حاول ان تفتح موضوع جديد بدلا من التعليق على الموضوع القديم لكي لا اضطر ان اقرأ 
 الموضوع بأكمله من البداية ... بالنسبة لك قد ترى المشكلة نفسها تكررت ولكن عادة تكون مشكلة جديدة ولا علاقة لها بالمشكلة الاولى

اهلا وسهلا بك
