### ISSUE TITLE
دعم الإضافة بمواقع أخرى تتوفر على سيرف خاص

### ISSUE THREAD

**Issue by potogo** [emadmahdi/KODI#46]
السلام عليكم شكرا على الإضافة الرائعة 
كما تعلم أخي أغلب المواقع المعروفة بدأت في الإعتماد على سيرفر متعدد الجودات خاص بها لتفادي التوقف المتكرر لروابط 
السيرفرات التقليدية وحاليا موقع
akwam
   هو الوحيد في الإضافة الذي يتوفر على سيرفر متعدد الجودات خاص به
هل ممكن دعم الإضافة بمواقع أخرى تتوفر على سيرف متعدد الجودات خاص بها مثل
egybest , faselhd , mvs4u , cimaclub , arabseed , mycimatv , cimanow , show.alfajertv , ar.arbcinema , imovie-time , movizland , shahidanime , anime2001 
  لك الإختيار وشكرا

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله

تقريبا جميع المواقع التي انت ذكرتها انا قمت بفحصها سابقا ... انا اعمل حاليا على اضافة موقع عرب سييد اما بقية المواقع فانا اضيف فقط المواقع التي فيها عربي وانكليزي وسيرفرات خاصة او عامة وخاصة

اما عن المواقع في برنامجي التي تستخدم سيرفرات خاصة وجودات مختلفة فهي ليست فقط موقع اكوام الجديد ... جرب بقية المواقع مثل كل العرب وبانيت وايجي فوربيست وغيرها

**Comment by potogo** [comment]
كل الشكر اخي
Egybest , mycima , cimaclub , cimanow , imovie-time , fajer.show , movizland
هاته المواقع كلها فيها عربي و إنجليزي وكلها تتوفر على سيرفرات خاصة وعامة

**Comment by emadmahdi** [comment]
اظن مع الاصدار الجيجد والتصليحات فإنه لا توجد حاجة لمواقع أكثر لانها لن تزيد البرنامج في شيء ... ومع هذا سوف افحص المواقع التي انت كتبتها

**Comment by emadmahdi** [comment]
المواقع التي انت بعثتها جيدة وممكن ان اضيفها ... ولكن احتاج اعرف ما هو الشيء المميز فيها وغير موجود الان في برنامجي

**Comment by emadmahdi** [comment]
انا اتكلم فقط عن هذه المواقع
mycima.co
cima-now.com
imovie-time.co
fajer.show
cimaclub.com
