### ISSUE TITLE
كيفية التحديث بارك الله فيك

### ISSUE THREAD

**Issue by nissfcb** [emadmahdi/KODI#48]

**Comment by emadmahdi** [comment]
في قسم الاضافات حاول ان تجد مخزن عماد او اي مخزن ثاني ثم اضغط عليه بالماوس ونفذ
Check for updates
واذا لم تجدها فاذن حاول ان تضغط الماوس او الاسهم الى جهة اليسار لكي تجد وتنفذ
Check for updates
ثم اصبر قليلا ثم حاول ان تحدث برنامجي

أو اغلق كودي او اطفي الجهاز ثم شغله مرة اخرى ... ثم اصبر قليلا ثم حاول ان تحدث برنامجي

او انتظر 24 ساعة وسوف يقوم المخزن بتحديث نفسه ... ثم اصبر قليلا ثم حاول ان تحدث برنامجي

**Comment by nissfcb** [comment]
لم ينجح الا

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by nissfcb** [comment]
السلام عليكم لم ينجح الأمر أخي في التحديث هل من فيديو توضيحي ان أمكن

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by emadmahdi** [comment]
جرب اذهب الى قسم الاضافات وامسح الاضافة التي اسمها مخزن عماد
"EMAD Repository"
ثم قم بتنصيب مخزن عماد مرة اخرى على جهازك

هذا الرابط هو لصفحة كودي الخاصة بي ... فيها روابط لطريقة التنصيب بالصور ومفصلة ... وفيها ايضا روابط لفيديوهات تشرح طريقة التنصيب ... وايضا تجد فيها ملفات واضافات كودي الخاصة بي
https://github.com/emadmahdi/KODI

**Comment by emadmahdi** [comment]
وإذا لم تنتهي مشكلتك فاذن جرب ان تمسح برنامجي
ِArabic Videos
من قسم الاضافات في كودي وتعيد تنصيبه مرة اخرى
