### ISSUE TITLE
 خلل في مشاهدة مسلسات في موقع عرب ليونز

### ISSUE THREAD

**Issue by palfal** [emadmahdi/KODI#49]
السلام عليكم اخي عماد

اولا اشكرك على مشهودك الجبار

تانيا لاحظت مشكلة في مشاهدة المسلسلات في عرب ليونز

مسلسل Home land
الموسم الاول
الحلقة الاولى

مع ملاحظة الحلقة تعمل من خلال الموقع الرئيسي

تقبلو فائق الشكر والتقدير

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله ... سوف أفحص المشكلة ... شكرا للتنبيه

**Comment by emadmahdi** [comment]
تم اصلاح المشكلة ... انتظر مني الاصدار الجديد للبرنامج قريبا

**Comment by palfal** [comment]
جزاك الله خيرا
