### ISSUE TITLE
Real debrid

### ISSUE THREAD

**Issue by mufeed99** [emadmahdi/KODI#50]
مسا الورد يا مبدع 
في مجال تعمل تحديث لليورل ريسولفر تصير تقبل ادخال حسابات الريل ديبريد والبريتورايز مي لانه جربت اعمل كنفجريشن من يرل ريسولفر نازله ببرنامج ثاني لاكن ما بتاخد منها

**Comment by mufeed99** [comment]
لقيت طريقه من عند الدبندنس خلص ما في داعي اغلبك

**Comment by emadmahdi** [comment]
مساء الخير

انا استخدم في برنامجي
resolveurl
وليس
urlresolver

وتستطيع ببساطة أن تعمل
configuration
في قسم الاضافات

**Comment by emadmahdi** [comment]
سوف اضيف
configuration
في الاصدار الجديد قريبا

سوف تجده في قائمة خدمات البرنامج

**Comment by emadmahdi** [comment]
ممكن تشرح لي ما هي فائدة
real debrid
,وكيف تستخدمها في برنامجي

**Comment by mufeed99** [comment]
بكل بساطة
السايتات اللي تشغل الافلام تستعمل هوستات عشان تعمل هوست للفايلز عليها
معظم الهوستات بفلوس عشان هيك اللنك ما تشتغل او تشتغل ببطئ او تحكيلك انتظر
٣٠ او ٦٠ ثانيه على حسب

لما يكون عندك حساب على الريل دبريد او alldebrid الهوست بفتح بطريقه على طول
وبلغي وقت الانتظار وبشتغل على طول  و بفل كوالتي
برنامجك صديقي رائع جدا .. ارجوك تابع و فعلا امتعتنا وانا وكل شخص بستعمله
شاكر لك

**Comment by emadmahdi** [comment]
الشكر لله
