### ISSUE TITLE
Arabic videos not working after update to 6.5.0

### ISSUE THREAD

**Issue by zacrizk** [emadmahdi/KODI#54]
Hi,
The add-on was working great at 6.4.3, but today it updated to 6.5.0 and now no sites appear in the list.

Thanks

**Comment by zacrizk** [comment]
> Hi,
> The add-on was working great at 6.4.3, but today it updated to 6.5.0 and now no sites appear in the list.
> 
> Thanks

Apologies. Just the menus restructured. 
Thanks for the great add-on:)

**Comment by emadmahdi** [comment]
you welcome
