### ISSUE TITLE
مشكلة في قائمة اكوام الجديد

### ISSUE THREAD

**Issue by palfal** [emadmahdi/KODI#55]
السلام عليكم اخي عماد

تحية طيبة 

لاحظت مشكلة في قائمة اكوام الجديد حيث انه لا يتم سرد الافلام او المسلسلات بالقائمة بغض النظر عن الاختيار

افلام مصنفة تم اخيار الجميع في جميع القوائم التالية

هذا للعلم والتنبيه

تقبلو فائق الشكر والتقدير لهذا العمل والمجهود الرائع

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله

قائمة افلام مصنفة ... هي لزيادة التصنيفات والفلتر ... ولكي ترى قائمة الافلام فانت تحتاج ان تتجاوز جميع التصنيفات لكي تصل الى قائمة الافلام التي تطابق اختياراتك ... واذا كانت القائمة الاخيرة فارغة فهذا معناه انها غير موجودة على سيرفر اكوام او ان موقع اكوام لم يفهم اختياراتك

للتأكد من المشكلة ... قم باختيار كلمة "الجميع" في القوائم المصنفة كلها واذا كانت القائمة الاخيرة فارغة فاذن ارجوك ارجع هنا واخبرني

**Comment by palfal** [comment]
هذا ما حصل بالظبط

اخترت الجميع وكانت القائمة فارغة

**Comment by emadmahdi** [comment]
ابعث لي سجل الاخطاء من قائمة الخدمات

**Comment by emadmahdi** [comment]
قم بتجربة الدخول مرة اخرى الى التصنيفات  ثم ابعث لي سجل الأخطاء من قائمة الخدمات

**Comment by palfal** [comment]
تم الارسال

**Comment by emadmahdi** [comment]
لم اجد اي مشكلة خاصة بك في موقع اكوام ... ولكني نشرت قبل قليل اصدار جديد ... هل ممكن ان تجربه وتخبرني بالنتيجة ... وايضا حاول ان تمسح الكاش من قائمة خدمات البرنامج وبعدها افحص موقع اكوام مرة اخرى وايضا اخبرني بالنتيجة

**Comment by T0mS4wy3r** [comment]
السلام عليكم أخي عماد،

بارك الله فيك على الفيكس. المشكل لم يعد مطروحاً مع النسخة 6.5.1

تحياتي
السلام عليكم

**Comment by palfal** [comment]
جزاك الله الف خير 

لا مشكلة بعد الاصدار الجديد

تحياتي
