### ISSUE TITLE
للكبار

### ISSUE THREAD

**Issue by uae5506** [emadmahdi/KODI#56]
السلامة عليكم ورحمة الله وبركاته 
يعطيك العافيه على مجهودك الصراحه الاضافه رهيبه جدا 
عندي سؤال اذا سمحت لي كيف اقدر اغير العمر بعض الافلام تظهر لي للكبار فقط وانا الحمدلله عمري 43 
هل من الممكن اغير ولا ما اقدر 
وشكرا لك مره ثانيه بالفعل اضافه لا مثيل لها

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله وبركاته
الله يعافيك

للاسف لا توجد عندي طريقة لكي اتأكد من العمر ... ولهذا السبب لا يوجد طريقة في البرنامج لتشغيل فيديوهات "للكبار فقط" ا
