### ISSUE TITLE
موقع فاصل اتش دي Faselhd.live

### ISSUE THREAD

**Issue by Ali202012** [emadmahdi/KODI#57]
السلام عليكم ورحمة الله اخي العزيز 
اولاً اشكرك من كل قلبي على مجهودك الجبار والرائع في هذه الإضافة المتميزه وفي الحقيقه اعجز عن شكرك لانها سهلت علينا الكثير ، 
ما اردت ان اطلبه منك راجياً منك المساعده هو انت تضيف موقع Faselhd
 الى هذه الإضافة المميزه   فهذا الموقع متميز بتوفر الدقه العاليه في اكثر الافلام والمسلسلات ، دقه FHD 
1080p
اعلم اني اطلب الكثير ولاكن اتمنى منك ان تنظر في هذه الفكره وساكون لك من الشاكرين

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله وبركاته ... هذا الموقع فيه ثلاثة مشاكل

اولا: يستخدم لغة جافا سكربت وكودي يستخدم بايثون

ثانيا: يحتاج اشتراك للحصول على الدقة العالية

ثلاثة: لا توجد فيه فيديوهات عربية
