### ISSUE TITLE
Adding shiavouce.com

### ISSUE THREAD

**Issue by rfdslx** [emadmahdi/KODI#58]
This web page is full video/audio library. It is not currently covered in any kodi addon. Thanks

**Comment by emadmahdi** [comment]
لقد قمت باضافة موقع صوت الشيعة والسبب هو لأنه كان السبب في إضافة "مواقع يوتيوب" والتي وصل عددها الى الان 330 موقع مقسمة الى 46 نوع ... والباب مفتوح لإضافة مواقع جديدة وأنواع جديدة

انتظر مني الاصدار الجديد رقم
7.1.0
قريبا

**Comment by emadmahdi** [comment]
تم نشر الاصدار الجديد رقم
7.1.0

إذا لديك أي مشكلة فارجوا منك ابلاغي بفتح
issue
جديد

وشكرا لك لأنك كنت السبب في اعطائي افكار جديدة قمت بإضافتها لبرنامجي

**Comment by rfdslx** [comment]
يعمل شكرا على جهودكم

**Comment by emadmahdi** [comment]
الشكر لله
