### ISSUE TITLE
Can you please cimaclub and cima4u 

### ISSUE THREAD

**Issue by alikachef** [emadmahdi/KODI#59]
Can you please cimaclub and cima4u on the koddi add on they have lots of titles from every where there library is massive

**Comment by emadmahdi** [comment]
الموقعين لا توجد فيهما سيرفرات خاصة ... يعني مشاكلهم كثيرة

**Comment by emadmahdi** [comment]
اريد موقع للمسلسلات بحيث استطيع اختيار البلد ... مثلا اختار مسلسلات مصرية ... او اختار مسلسلات خليجية ... او اختار مسلسلات سورية

المواقع التي انا اعرفها فقط يكتبون مسلسلات عربية بدون تحديد اسم البلد

**Comment by zombiB** [comment]
يوجد موقع بانيت و العرب تحوي سرفرات خاصة

**Comment by emadmahdi** [comment]
@zombiB 
موقع بانيت موجود في برنامجي ويعمل بدون مشاكل منذ سنة 2018 ... وموقع العرب ... اذا كنت تقصد موقع كل العرب فهو ايضا موجود في برنامجي منذ 2018  ... اما اذا كان العرب هو موقع مختلف فاذن رجاء ابعث لي رابط الموقع لكي افحصه
