### ISSUE TITLE
موقع ايجي بيست لا يعمل

### ISSUE THREAD

**Issue by hussapril7** [emadmahdi/KODI#6]
اخ عماد كيف حالك اتمنى تكون بخير وصحة 
حبيب قلبي الاضافة دخلت عليها امس للاسف فيها مشكله
دخلت جميييع المواقع فيها كله من اختار فلم لايشتغل ولا تظهر روابط او سيرفرات الافلام 
في كل المواقع اللي ضايفهم

وخصوصا موقع ايجي بيست لايشتغل شيء نهائيا

اتمنى ان تحل المشكله 
لان والله غبت فتره وجيت بطالع مايشتغل شي وتحبطت
كنت ماسح جميع الاضافات عشان اوفر مساحه بجهازي 
وخليت بس اضافتك لان بالنسبه لي كانت شامله
بس امس تحبطت من لقيت الاضافه ماتشتغل 

اضطريت اروح المواقع الرسميه من المتصفح /:

عموما اتمنى تكون بتمام الصحه والعافيه
وبانتظار ردك....

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله
حسب علمي فقط الايجي بيست لا يعمل والسبب من الموقع الاصلي لانهم قاموا بتغيير طريقة الدخول للموقع ...وقد عالجت المشكلة في التحديث الجديد ولكني لم اقم بنشره الى الان

**Comment by hussapril7** [comment]
مادري والله، انا جربت كذا موقع مثل شاهد فور يوو، وهلا سينما، وهلال يوتيوب، وجدت ايضا نفس المشكله لايشتغل شيء

عموما بخصوص موقع ايجي بيست بانتظار التحديث وان شاءالله يكون شغال بامتياز
بس اتمنى ان تتاكد من باقي المواقع في حال هناك بعص الاخطاء بالأضافه

وانت مايحتاج اكيد راح تفحص المواقع في برنامجك بعد التحديث

عموما مشكور اخ عماد وبانتظارك

**Comment by firasville** [comment]
السلام عليكم أخ عماد
جميع الاضافات تعمل عدا اضافة ايجي بيست
انصح الاخ بإعادة حذف الاضافة و تنزيلها مجدداً بعد تشغيل  في بي ان vpn
لأن اضافة الاخ عماد تنزل معها اضافات اخرى ربما تكون محجوبة في بعض الدول

اتمنى يا أخ عماد بعد التحديث فتح افلام ايجي بست كلها ليتم الاستفادة من الاضافة بشكل كامل معظم الافلام لا تعمل بسبب وجود لقطات اقل من عادية في بعض الاحيان

**Comment by emadmahdi** [comment]
تم اصلاح ايجي بيست

**Comment by firasville** [comment]
شكراً جزيلاً يا عماد ..جاري التجربة

**Comment by firasville** [comment]
شكراً لك اخي عماد الاضافة تعمل .. و لكن
أرجو حل مسألة افلام للكبار فقط
انت بهذا تحرمنا من مشاهدة افلام رائعة بجودة ايجي بيست الممتازة
مثال
Hunter Killer (2018)
فيلم لا يوجد به اي مشاهد عاطفية 
فقط مشاهد دموية ..لماذا تحرمنا من مشاهدته
و هناك العديد من الامثلة التي لا حصر لها
أرجو منك فتح الافلام لتكون اداتك وسيلة معتمدة حقاً لمشاهدة الافلام المترجمة
لك وافر المحبة

**Comment by hussapril7** [comment]
اخ عماد شكرا لك ايجي بيست شغال بامتياز الان

ولكن موقع هلال يوتويب هناك حطأ في الدخول لا اعلم ارجوا ان تتأكد 

وبالنسبه للاخ اللي فوقي اضم صوتي لصوتك بخصوص بعض الافلام لايمكننا مشاهده بسبب للكبار فقط!! رغم لاعيب فيها وتكون مشاهد طبيعيه وعاديه وليست اباحيه

ولكن سبق وتكلمت مع الاخ عماد في هذا الشيء ولكن للاسف رافض

ولكن اتمنى ان يعطي الاضافه حقها في التميز بازاله هذي المشكله

لان فعلا ننحرم من مشاهده افلام كثيره بسبب هذا الشي

**Comment by emadmahdi** [comment]
برنامجي للعوائل وليس للكبار فقط ... ولهذا لا استطيع السماح بافلام الكبار مثل افلام العنف والوحشية والرعب والاباحية وما شابه
