### ISSUE TITLE
أفضل أفلام تم منعها

### ISSUE THREAD

**Issue by ikhlefamine** [emadmahdi/KODI#60]
السلام عليكم لماذا افضل افلام يتم منعها

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله

لم أفهم سؤالك ... ممكن توضح لي ؟

**Comment by ikhlefamine** [comment]
اخي شكرا على الرد 
  يكتب منع من المبرمجtenet مشكل مثل فيلم

**Comment by emadmahdi** [comment]
الشكر لله

ممكن تبعث لي سجل الاخطاء من قائمة خدمات برنامجي

او تكتب لي جميع التفاصيل مثل اسم الموقع والروابط التي احتاجها للوصول الى الى الفيلم الذي تتكلم انت عنه وايضا احتاج اعرف رسالة الخطأ كاملة

وتذكر انا لا اعلم الغيب
