### ISSUE TITLE
الفيديو للكبار فقط و انا منعته !؟

### ISSUE THREAD

**Issue by one6666** [emadmahdi/KODI#61]
اولا شكرا على addon 
لكن اغلب افلام الأكشن هي ١٨+ 
فهل هنالك طريقه او حل لهذي المشكله 
واعيد الشكر لمجهودك الجبار

**Comment by emadmahdi** [comment]
حاليا لا توجد طريقة لمعرفة العمر الحقيقي ... ولا يوجد حل لهذه المشكلة ... برنامجي فيه مواقع كثيرة ... جرب موقع مختلف

الطريقة الوحيدة لالغاء فحص افلام الكبار هي فقط اذا ثبت لي ان الافلام الممنوعة عددها اكثر من عدد الافلام المسموحة ... اخر مرة فحصت العدد كانت النسبة 30 بالمئة ممنوعة و 70 بالمئة مسموحة
