### ISSUE TITLE
مشكلة في معظم المواقع

### ISSUE THREAD

**Issue by mohammedftouhi** [emadmahdi/KODI#62]
السلام عليكم ورحمة الله وبركاته
اخ عماد انا مقيم في السعودية ومنذ قرابة الشهر توقفت معظم المواقع عن العمل لدي في برنامج كودي
المواقع التي كانت تعمل هي موقع اكوام القديم فقط
قبل يومين عاد موقع هلال تيوب للعمل
وباقي المواقع لا تعمل
تظهر رسالة الخطأ التالية
فشل في سحب الصفحة من الانترنتهل تريد معرفة الاسباب والحلول؟ 
Error -1: Connection aborted.

هل يوجد حل حاليا ام لا
وشكرا لجهودك

**Comment by one6666** [comment]
نفس المشكله الحل هو استخدام vpn 
 لكن موقع إكوام الجديد شغال من عير vpn

**Comment by emadmahdi** [comment]
@mohammedftouhi 
وعليكم السلام ورحمة الله وبركاته

في شهر 10 سنة 2020 ... لدي 90 جهاز في السعودية استخدموا برنامجي وقاموا بتشغيل 832 فيديو

للاسف بدون سجل الاخطاء لا توجد عندي طريقة لكي اعرف ماذا يجري عندك ... لكي ترسل السجل لي ... افتح برنامجي واذهب الى قسم الخدمات ثم اذهب الى ارسال سجل الاخطاء ثم ارسل سجل الاخطاء لكي اعرف ما هي المشكلة بالضبط

=====================

@one6666  @mohammedftouhi 
اذا كان الحل هو باستخدام
VPN
فاذن لا يوجد عندي حل لهذه المشكلة

**Comment by mohammedftouhi** [comment]
اخ عماد اسف على الاطالة 
انا مستخدم قديم لبرنامجك واشكرك جزيل الشكر على مجهودك المبذول
حاولت ارسلك سجل الاخطاء ما يرسل من البرنامج
لذلك صورته وارسلته لك هنا على شكل صور
هل يوجد برنامج بروكسي معين تنصحني فيه او هل اذا اعدت تثبيت البرنامج او اعدت تثبيت الاضافة تشتغل عندي 
شكر مكرر لك




Sent from myMail for iOS


Tuesday, 20 October 2020, 10:24 PM +0300 from notifications@github.com  <notifications@github.com>:

**Comment by emadmahdi** [comment]
انا بانتظار الصور ... لم يصلني منك شيء

**Comment by mohammedftouhi** [comment]
Sent from myMail for iOS


Wednesday, 21 October 2020, 2:53 AM +0300 from notifications@github.com  <notifications@github.com>:

**Comment by mohammedftouhi** [comment]
![Uploading 4C1D919C-6F89-40F7-B710-686DCE37B137.jpeg…]()

**Comment by mohammedftouhi** [comment]
![079A89C2-52E6-4895-BFEE-59F35BBDAF8C](https://user-images.githubusercontent.com/73190517/96656658-f2fa6000-1348-11eb-8b20-a7ab4afae18f.jpeg)
![F0C1F304-83B2-4AAB-8968-E9F817224746](https://user-images.githubusercontent.com/73190517/96656661-f42b8d00-1348-11eb-84c4-f54f00ec8b1f.jpeg)
![BB75BE64-D0D1-4CEE-A65C-F998AD30A7F4](https://user-images.githubusercontent.com/73190517/96656663-f4c42380-1348-11eb-959c-d06513a1e715.jpeg)

**Comment by emadmahdi** [comment]
اشكرك على الصور ... سوف اقوم بفحصها لاحقا وارجع لك ان شاء الله في اقرب وقت

**Comment by emadmahdi** [comment]
سؤال ... لو  دخلت على المواقع التي فيها مشكلة ولكن باستخدام المتصفح ... هل تعمل معك المواقع ام ايضا تظهر لك مشكلة او رسالة خطأ ... جرب مثلا هذه الروابط

https://shahid4u.com
http://arablionz.com
https://arabseed.net
https://cima-now.com
https://4helal.me
https://akwam.net
https://akoam.net

**Comment by mohammedftouhi** [comment]
جربت ودخلت المواقع كلها ما اشتغلت
ما عدا موقع هلال تيوب اشتغل
يبدو ان المشكلة في الانترنت عندي
يوم شغلت البروكسي اشتغلت المواقع على المتصفح وعلى برنامج اكوام
هل فيه برنامج بروكسي كويس ما يخفض سرعة الانترنت او اعدادات معينة اقدر اسويها ويشتغل عندي البرنامج والمواقع بدون برنامج vpn

**Comment by emadmahdi** [comment]
للأسف لا اعرف حل لهذه المشكلة سوى 
proxy   أو   vpn

**Comment by emadmahdi** [comment]
ممكن تجرب لي هذا الرابط على المتصفح

http://emadmahdi.pythonanywhere.com

**Comment by mohammedftouhi** [comment]
جربت وطلعتلي هذي الصفحة
![DF387AE0-1DD0-4689-8EBE-80F919CF7BAA](https://user-images.githubusercontent.com/73190517/96783859-48407b00-13f6-11eb-8a9a-63f28230e51c.jpeg)

**Comment by emadmahdi** [comment]
جيد جدا ... هذا معناه ان حكومتكم قررت منع جميع مواقع الفيديو ... وهذا المنع ليس خاص ببرنامجي

**Comment by emadmahdi** [comment]
في الاردن منعوا موقع برنامجي ولم يمنعون مواقع الفيديو

**Comment by mohammedftouhi** [comment]
وجدت حل مؤقت يفيد
اول شي بشغل تطبيق vpn وبروح على تطبيق كودي وبشغل الفيديو او الفيديوهات اللي حاب اني اشوفها وبطلع من التطبيق
وبعدها برجع بطفي الvpn وبروح على نفس الفيديوهات في كودي ويشتغلو تمام
اعتقد انه حل جيد في الوقت الحالي

تعبتك معي
شكرا لك

**Comment by emadmahdi** [comment]
ممكن تدخل الى هذا الموقع وترسل لي الارقام ... هذا الفحص احتاجه لكي  اعرف اذا كان الحجب عندك سببه الارقام مثل الكويت ام سببه مختلف ... اذا كان الارقام فاذن الحل عندي موجود وسهل

https://dnschecker.org/all-dns-records-of-domain.php?query=akwam.co

هذا الرابط سوف يفتح لك صفحة فيها 3 ارقام صغيرة في قسم
A
وثلاثة ارقام اخرى في قسم
AAAA


انا احتاج هذه ال 6 ارقام

**Comment by mohammedftouhi** [comment]
![Uploading FAC3B172-3B97-4DEC-8772-A631F305B2AA.jpeg…]()

**Comment by mohammedftouhi** [comment]
![150680F5-2681-4D1F-A956-CF8078020468](https://user-images.githubusercontent.com/73190517/96789094-32828400-13fd-11eb-83fc-04475cd489e8.jpeg)
![EBA1B416-9CE1-4499-8BFB-61B2D284BACE](https://user-images.githubusercontent.com/73190517/96789103-344c4780-13fd-11eb-853e-b6c63f09bfdb.jpeg)

**Comment by emadmahdi** [comment]
للأسف الارقام عندك كلها صحيحة

الحل المؤقت عندك يعمل بسبب شي في برنامجي اسمه الكاش ... عندما تقوم انت بتشغيل ال في بي ان يقوم برنامجي بتخزين 
الصفحة في قاعدة بيانات ... وانت عندما تطفي ال في بي ان يقوم برنامجي بسحب الصفحة القديمة من الكاش وليس من الانترنيت ... هذه الطريقة تنفع لمعرفة السيرفرات ولكن لا تنفع لفتح الصفحات من الانترنيت ... لان السيرفرات تستخدم اسماء للمواقع مختلفة عن اسم الموقع الذي عليه حجب ... علما ان كل صفحة في الكاش لها فترة محددة وتختفي من الكاش

**Comment by emadmahdi** [comment]
![image](https://user-images.githubusercontent.com/7454511/96799924-26cd9800-13d2-11eb-9beb-c62b0021159a.png)

**Comment by emadmahdi** [comment]
اللون الازرق هو للناس فقط في السعودية الذين استخدموا برنامجي فقط في السبعة ايام الماضية ... اللون الازرق الغامق معناه كثير ناس واللون الازرق الفاتح معناه قليل ناس

**Comment by No-WaY-SA** [comment]
> سؤال ... لو دخلت على المواقع التي فيها مشكلة ولكن باستخدام المتصفح ... هل تعمل معك المواقع ام ايضا تظهر لك مشكلة او رسالة خطأ ... جرب مثلا هذه الروابط واخبرني بالنتيجة
> 
> https://shahid4u.com
> http://arablionz.com
> https://arabseed.net
> https://cima-now.com
> https://4helal.me
> https://akwam.net
> https://akoam.net

السلام عليكم
استاذ عما اواجه نفس مشكلة الاخ في معظم المواقع
مع العلم اني استخدم اخر نسخه من موقعك 
وجميع مواقع الافلام تفتح على المتصفح

فهل من حل؟

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله
ارسل لي سجل الاخطاء من قائمة الخدمات في برنامجي

**Comment by No-WaY-SA** [comment]
تم ارسالها بمسمى
akwam not woking

**Comment by emadmahdi** [comment]
جرب الدخول الى هذا الموقع باستخدام المتصفح ... واخبرني ماذا سوف يحدث معك بالضبط ... اريد ان اعرف هل تظهر لك صفحة باللغة الانجليزية قبل فتح الصفحة الرئيسية للموقع

http://shoofvod.com

**Comment by No-WaY-SA** [comment]
> جرب الدخول الى هذا الموقع باستخدام المتصفح ... واخبرني ماذا سوف يحدث معك بالضبط ... اريد ان اعرف هل تظهر لك صفحة باللغة الانجليزية قبل فتح الصفحة الرئيسية للموقع
> 
> http://shoofvod.com

الموقع محجوب

**Comment by emadmahdi** [comment]
اذن المشكلة من حكومة السعودية الارهابية وليست من برنامجي
