### ISSUE TITLE
akoam

### ISSUE THREAD

**Issue by mbatrawi** [emadmahdi/KODI#64]
akoam site not working
may be url address changed
please update
thanks

**Comment by emadmahdi** [comment]
ابعث لي سجل الاخطاء

**Comment by mbatrawi** [comment]
sent

**Comment by emadmahdi** [comment]
received
will check later

**Comment by mbatrawi** [comment]
akoam problem not solved till date

**Comment by emadmahdi** [comment]
لديك في برنامجي مواقع بديلة ... انا غير مضطر ان انشر التحديث ارضاء لك او لاي شخص اخر ... اذا كنت مستعجل فاذن ابحث عن برامج اخرى ترضيك وترضي طموحك

**Comment by emadmahdi** [comment]
انا اعمل بحسب طاقتي وبحسب امكانياتي وبحسب وقتي ... واذا كنت مستعجل وترى اني مقصر ... فاذن تعلم البرمجة وتعال ساعدني لكي يستمر هذا البرنامج بدلا من محاسبتي والاعتراض والقول ان التحديث تأخر

**Comment by emadmahdi** [comment]
قبل دقائق قمت بنشر الاصدار الجديد
