### ISSUE TITLE
وش حل الاداة في كودي

### ISSUE THREAD

**Issue by zaabal3** [emadmahdi/KODI#65]
مرفق لكم الخطا على جميع المواقع على نسختك الي على الموقع 😔😔
![503CD11F-5ECF-4B40-9B67-B54B77574B35](https://user-images.githubusercontent.com/74320630/98849169-da6ef880-2463-11eb-8a46-655da7801114.jpeg)
![Uploading A15D7695-285F-4566-9125-20F16656701B.jpeg…]()

**Comment by zaabal3** [comment]
![Uploading 654EFAB3-51A0-41FC-A5B7-E1827CBACE15.jpeg…]()

**Comment by emadmahdi** [comment]
في اي بلد انت ؟

**Comment by zaabal3** [comment]
السعودية

**Comment by emadmahdi** [comment]
استخدم
vpn

**Comment by emadmahdi** [comment]
حاول ان تبعث لي سجل الاخطاء من قائمة الخدمات في برنامجي لكي اعرف ما هي بالضبط المشكلة في السعودية لكي احاول ان اجد لها حل في الاصدارات القادمة

**Comment by zaabal3** [comment]
شغلت vpn نفس المشكله علما موقع اكوام عندنا شغال بدون vpn عادي بس غريبه مع التحديث الجديد معك لا يعمل ان شاء الله تنحل عن طريقك

**Comment by emadmahdi** [comment]
بعض شركات الانترنيت في السعودية فيها حجب ضد مواقع الفيديو ... وبرنامجي لا يستطيع ان يتجاوز هذا الحجب ... ولهذا انا قمت باضافة شغلة اسمها بروكسي وعملها مشابه لمبدأ ال
vpn
ولكن واضح ان البروكسي لا يعمل عندك ... وللعلم فانت تستطيع من قائمة خدمات برنامجي ان توقف أو تشغل البروكسي

اما موقع اكوام فالظاهر انه لا يوجد عليه حجب ... ولكن مع هذا وصلتني رسائل تقول ان بعض صفحات اكوام لا تعمل

لكي تتأكد من الحجب بنفسك ... استخدم المتصفح وحاول ان تدخل على مواقع برنامجي وسوف تجدها لا تعمل ... او تجدها تظهر لك شاشة تأخير 5 ثواني ... في الحالتين معناه هناك حجب

**Comment by emadmahdi** [comment]
ارسل لي سجل الاخطاء لكي افهم لماذا لا يعمل البروكسي عندكم

**Comment by zaabal3** [comment]
![Uploading 99150319...]

**Comment by zaabal3** [comment]
سجل الاخطاء اكثر من صوره

**Comment by zaabal3** [comment]
سجل الاخطاء اكثر من صوره

**Comment by zaabal3** [comment]
طلبت ارسال الاخطاء على البريد

**Comment by emadmahdi** [comment]
اظن انك دخلت على قراءة السجل وليس على ارسال السجل

**Comment by zaabal3** [comment]
![image](https://user-images.githubusercontent.com/74320630/99187587-89634b00-2768-11eb-9615-4ed2b14f7efc.jpeg)![image](https://user-images.githubusercontent.com/74320630/99187588-89634b00-2768-11eb-8e20-8ca3d4abee0f.jpeg)
![image](https://user-images.githubusercontent.com/74320630/99187589-8d8f6880-2768-11eb-91d4-5c2509cbc8eb.jpeg)

![image](https://user-images.githubusercontent.com/74320630/99187590-9122ef80-2768-11eb-871e-b277d1758083.jpeg)

![image](https://user-images.githubusercontent.com/74320630/99187593-93854980-2768-11eb-8131-d0d9fa037a3c.jpeg)![image](https://user-images.githubusercontent.com/74320630/99187597-96803a00-2768-11eb-8fc9-c72441a385fc.jpeg)

**Comment by emadmahdi** [comment]
وصلتني منك رسالتين فيها سجلات اثنين
انتظر من الاصدار الجديد
ولا اعرف متى بالضبط

**Comment by emadmahdi** [comment]
قبل دقائق قمت بنشر الاصدار الجديد

**Comment by zaabal3** [comment]
سوف اقوم بتحميله وتثبيته مره اخرى لتاكد شكرا لك

**Comment by emadmahdi** [comment]
انا قمت في هذا الاصدار باضافة سيرفرات بروكسي وسيرفرات اسماء والمفروض انها تحل مشكلتكم في السعودية ... ولكن احتاج ان اعرف منك اذا الاصدار الجديد يشتغل بالكامل ام لسه فيه مشاكل ؟

**Comment by zaabal3** [comment]
![image](https://user-images.githubusercontent.com/74320630/100533189-9117fa80-3212-11eb-820d-d60abaee6c6a.jpeg)

عند البحث يترقف عنا لا يعمل لا يوجد خطا واضح عدا هذه الصوره

![image](https://user-images.githubusercontent.com/74320630/100533194-a1c87080-3212-11eb-9e9c-5766082c2b6c.jpeg)


![image](https://user-images.githubusercontent.com/74320630/100533201-aee55f80-3212-11eb-8a91-3fbb7b187cba.jpeg)

علما يتم تفعيل vpn لكن بدون فايده حسب موضح لديكم

**Comment by emadmahdi** [comment]
حسب الصورة التي سوف ابعثها لك ... لديكم في السعودية حجب لكثير من المواقع ولا اعرف ما هو الحل لهذا الحجب ... ولكن الحجب في العالم كله له ثلاثة حلول وهي
vpn     proxy     dns
 وعليك انت ان تكتشف ما هو الحل المناسب لك في بلدك وفي جهازك وفي شركة الانترنيت التي تاخذ انت منهم الانترنيت

اما رسالة الخطا فهي ببساطة تقول انه تم قطع الاتصال ... ثم انا لا اعرف لماذا لم تجرب مواقع البرنامج على المتصفح الذي في جهازك لكي تتأكد ان الحجب من الانترنيت الخاصة بك

برنامجي ببساطو قادر ان يوفر لك بروكسي وايضا سيرفر الاسم ولكن
vpn
لا استطيع اضافته لانه ليس متوفر مجاني وايضا لانه يغير الانترنيت في جميع الجهاز وليس فقط في برنامجي

هذه هو الرابط الاصلي لموقع اكوما الجديد ... استخدم المتصفح وادخ عليه لكي تتأكد ان المشكلة من الانرتنيت الخاصة بك

http://akwam.net

**Comment by emadmahdi** [comment]
![saudia blocking 1](https://user-images.githubusercontent.com/7454511/100534015-c3a50180-31d8-11eb-95fc-5efd84db444f.jpg)

![saudia blocking 2](https://user-images.githubusercontent.com/7454511/100534016-c4d62e80-31d8-11eb-935b-4906b789a2ee.jpg)

**Comment by zaabal3** [comment]
هذا يعمل لدينا

https://akwam.co

**Comment by zaabal3** [comment]
وهذا الشكل القديم يعمل لدينا

https://old.akwam.co

**Comment by emadmahdi** [comment]
هل اكوام تعمل عندك في المتصفح بعد 5 ثواني ام فورا

وايضا ما هي رسالة الخطأ التي تظهر لك عند دخولك الى موقع اكوام في برنامجي

وايضا ايعث لي سجل الاخطاء بعد ان تجرب موقع اكوام القديم وموقع اكوام الجديد وايضا جميع مواقع برنامجي

انتم في السعودية لا تريدون ان تعترفوا بجريمة الحجب التي فعلها الصهاينة ال سعود ... انا مقتنع ان برنامجي سليم تماما ويعمل في جميع دول العالم الا في مملكة كفار ال سعود لعنة الله عليهم

هذه الصورتين الخاصة بالحجب انا بنفسي دخلت الى انترنيت مملكة ال سعود وعرفت بمسألة الحجب ... لو كان هناك ادب واخلاق ... كان المفروض انتم السعوديين تخبروني بموضوع الحجب بدلا من ان تقولون ان جميع المواقع لا تعمل في برنامجي ... وبدلا من ان تقولون ان المشكلة هي في برنامجي

**Comment by emadmahdi** [comment]
للعلم ... هذه ارقام يوم البارحة (يوم امس) السبت ... عدد الفيدوهات التي اشتغلت في جميع دول العالم هي

اكوام الجديد 482 فيديو

اكوام القديم 397 فيديو

**Comment by zaabal3** [comment]
حسبي الله ونعم الوكيل فيك
طز فيك وفي برنامجك وفي بلدك انقلع
انت وبرنامج 
يجب عليك اولا تحترم جميع الناس بعيد عن الدول والحكومه لكسب محبة الناس لكن طز فيك

السعودية اشرف منك ومن بلدك وال سعود اشرف منك ومن بلدك يا خاين

**Comment by emadmahdi** [comment]
يكفيك خزي وعار انت وبلدك وارضك واهلك مجرد املاك تابعة الى الصهاينة ال سعود ... بدليل ان اسم بلدك كله مسجل بأسم عائلة واحدة عائلة اليهود ال سعود لعنة الله عليهم وعلى كل شخص يرضى بجرائمهم ضد الاسلام وجرائمهم ضد المسلمين وجرائمهم ضد اطفال اليمن وجرائمهم ضد الرسول وجرائمهم الارهابية في جميع دول العالم

 بلد الوهابية والارهاب والارهابيين ودين الارهاب 

الحمد لله والشكر لله مليون مرة ... لان ربكم ال سعود منعكم ان تستخدموا برنامجي
