### ISSUE TITLE
حاج عماد عندي مشكلة في التشغيل

### ISSUE THREAD

**Issue by mohamedAhmed2234** [emadmahdi/KODI#66]
حاج عماد حضرتك انا عندي مشكلة في الكودي لما بفتح اي حلقة مسلسل او فيلم من موقع اكوام الجديد بتظهر ليا الرسالة دي

**Comment by mohamedAhmed2234** [comment]
![ED61E30F-8C50-465A-92B5-DA48C122CCC2](https://user-images.githubusercontent.com/74451952/99146248-fc909280-267e-11eb-95ed-436618d3593a.jpeg)
![Uploading 4F314135-16EA-4112-AFC3-E12AA6A0AD4F.jpeg…]()

**Comment by mohamedAhmed2234** [comment]
![Uploading 4EF191D8-44CF-435D-8AD4-9E930CEC0B3C.jpeg…]()

**Comment by mohamedAhmed2234** [comment]
![Uploading 608473F8-A4A6-42FB-99C1-CB3696085B58.jpeg…]()

**Comment by emadmahdi** [comment]
وصلني سجل الاخطاء
انتظر مني الاصدار الجديد
لا اعرف متى بالضبط

**Comment by emadmahdi** [comment]
قبل دقائق قمت بنشر الاصدار الجديد
