### ISSUE TITLE
kodi on android

### ISSUE THREAD

**Issue by YasBak** [emadmahdi/KODI#67]
السلام عليكم
البرنامج لا يعمل اذا تم تثبيته من خلال كودي على أجهزة اندرويد )installation failed 
هل هناك اي طريقة ؟

**Comment by emadmahdi** [comment]
وعليكم السلام
أسف للتاخير ... انا قبل دقائق رايت رسالتك

تم تحديث التطبيق قبل فترة قصيرة
حمل الملفات من هذا الموقع
http://tiny.cc/kodiemad

للاندرويد هناك ملفين ... احدهما للاندرويد الحديث والاخر للقديم

جرب الملفات واخبرني بالنتيجة
