### ISSUE TITLE
Issue to install Emad Arabic videos 

### ISSUE THREAD

**Issue by chadi16** [emadmahdi/KODI#68]
Hi emad
There is a problem to install  Emad Arabic videos and kodi says : [the dependency on script.mpdule.kodi-six version 0.0.0 could not be satisfied ]
Can you  please  fix it 
هل مشكل من كودي أو من حاجة  أخرى؟؟؟
شكرا

**Comment by chadi16** [comment]
Nice job Emad

**Comment by emadmahdi** [comment]
What is the speed of your internet ?!

**Comment by emadmahdi** [comment]
I think your internet is slow .. But I did some changes that suppose to fix your problem ... Try the install now and let me know if you get more problems !!

**Comment by chadi16** [comment]
Thanks for responding,  I have a good  internet connection but I think
there is a problem  for all kodi addons because  it gives the same problem
when I try to  install  git browser

**Comment by emadmahdi** [comment]
I don't understand ... do you still have the problem now or it is fixed now ... I am talking about my KODIEMAD only.

**Comment by emadmahdi** [comment]
I don't understand ... do you still have the problem now or it is fixed now ... I am talking about my app "KODIEMAD" only.

I am not worried or responsible about other addons ... I am asking only about these:
KODI
MetropolisEMAD Skin
Arabic Videos

**Comment by chadi16** [comment]
Thanks Emad, I really appreciate your help,  it's working now and been
installed

**Comment by chadi16** [comment]
Awesome, thanks!

**Comment by emadmahdi** [comment]
To install git browser ... you need either a repository that have this addon ... or a zip file that contain this addon

Kodi repository and Emad repositories ... both does not have this addon.

**Comment by chadi16** [comment]
Thanks a lot. I already  install  your addon and it's  working fine . I
really  like  your job

**Comment by emadmahdi** [comment]
you welcome
