### ISSUE TITLE
موقع اكوام توقف

### ISSUE THREAD

**Issue by potogo** [emadmahdi/KODI#69]
السلام عليكم 
موقع اكوام أصبح يعتمد على حماية google recaptcha
على سيرفرات المشاهدة و التحميل
هل يوجد لها حل ام لا
وشكرا

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله

للأسف لا يوجد عندي حل لها ... واذا استمرت المشكلة فسوف اقوم بمسح الموقع من قائمة البرنامج عند نشر الاصدار الجديد
