### ISSUE TITLE
Egybest mp4 links not working

### ISSUE THREAD

**Issue by ahmdgawad** [emadmahdi/KODI#7]
السلام عليكم عماد
بعد اخر تحديث ملفات
MP4
لا تعمل علي موقع ايجي بست

**Comment by emadmahdi** [comment]
وعليكم السلام
المشكلة ما زالت موجودة وانا احاول حلها

**Comment by emadmahdi** [comment]
حاليا الموقع يعمل بالكامل ولكني اتوقع حدوث خلل قريبا
ولهذا حاليا لا احتاج عمل تحديث للبرنامج
وشكرا على التبيه
