### ISSUE TITLE
عمل رائع

### ISSUE THREAD

**Issue by abnhalab** [emadmahdi/KODI#70]
اتمنى يتوفر تطبيقك في الايفون عن قريب ولو بالمال تستحق كل التقدير
 هل تستطيع اضافة موقع www.faselhd.pro 
ويعطيك العافيه اخي عماد على العمل الجميل

**Comment by emadmahdi** [comment]
الشكر لله اخي واهلا وسهلا بك

مسألة تطبيق الاي فون متوقفة بسبب عدم توفر جهاز ابل لفحص التطبيق .. اما موقع فاصل فهم يستخدمون لغة البرمجة جافا سكربت وللأسف كودي لا يفهم هذه اللغة
