### ISSUE TITLE
اضافة الكودي لا تعمل على اجهزة شاومي

### ISSUE THREAD

**Issue by palfal** [emadmahdi/KODI#71]
السلام عليكم و رحمة الله و بركاته

اخي عماد .. لاحظت ان اضافة الكودي لا تعمل على اجهزة شاومي .. جربت على جهازين ولم يعمل

الرابط اللوج من الكودي

https://paste.kodi.tv/iromuxatef

وتقبلو فائق الشكر والتقدير لجهودكم العظيمة

تحياتي

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله وبركاته

شكرا على التبيه ... الحقيقية وجدت المشكلة من البرنامج وعلى جميع الاجهزة وليس فقط جهاز شاومي ... قبل قليل قمت بنشر اصدار جديد ... جربه وان شاء الله يعمل بدون مشاكل ... وارجوك اخبرني بالنتيجة ... احب ان اعرف ماذا سوف يحصل معك

**Comment by palfal** [comment]
الان يعمل بعد التحديث 

جزاك الله الف خير

**Comment by emadmahdi** [comment]
الشكر لله ... اهلا وسهلا بك
