### ISSUE TITLE
مشكلة تحميل الملفات. لا توجد مساحة. 

### ISSUE THREAD

**Issue by mellsaid** [emadmahdi/KODI#72]
في مشكلة في تنزيل الملفات علي اندرويد tv.

 عدلت المسار للتنزيل في ال sd.
الجهاز في مساحة 2 GB.
El sd card 120 GB

أي ملف يطلع error إن المساحة 100 mb. لا تكفي.

**Comment by emadmahdi** [comment]
ارسل لي سجل الاخطاء

**Comment by emadmahdi** [comment]
في نهاية القائمة الرئيسية لبرنامجي .. ادخل على قائمة الخدمات  ... ثم ادخل على ارسال مشكلة
