### ISSUE TITLE
مايتثبت معاي في كودي

### ISSUE THREAD

**Issue by aseel0o** [emadmahdi/KODI#73]
السلام عليكم ورحمه الله وبركاته 
اخوي عماد في مشكله في تثبيت التطبيق 
![Screenshot_٢٠٢١٠٢٢٥-٢٣٢٦٣٠_Kodi](https://user-images.githubusercontent.com/79666779/109233692-586cca80-77db-11eb-90b3-feff7ec289b7.jpg)

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله وبركاته

هل تستخدم كودي اصدار رقم 19 ام 18 ؟

البرنامج لا يعمل على كودي 19

هل جربت مخازن عماد الاخرى ؟

ليس شرط ان تعمل عندك جميع المخازن .. واحد منها يكفي

انا انصح بمسح كودي بالكامل وتحميل تطبيق عماد الذي فيه كودي رقم 18.9 ومدمج معه برنامجي ومدمج معه مخازن عماد وايضا الجلد

http://tiny.cc/kodiemad

**Comment by emadmahdi** [comment]
اذا برنامجي يعمل معك .. فاذن من قائمة خدمات البرنامج في القائمة الرئيسية لبرنامجي ... ارسل لي سجل الاخطاء

واذا برنامجي لا يعمل فاذن جرب اضافات كودي الاخرى التي ممكن تستخدمها لكي ترسل لي سجل الاخطاء

**Comment by aseel0o** [comment]
يعطيك العافية اخ عماد على مجهودك حليت المشكله ايوه تحديث ١٩ سيء خرب الاضافات علي رجعت لتحديث ١٨ 
![Screenshot_٢٠٢١٠٢٢٦-٠٣٥٠٤٦_Kodi](https://user-images.githubusercontent.com/79666779/109239251-185f1500-77e6-11eb-8fd7-f91741a44dff.jpg)

**Comment by aseel0o** [comment]
حملت هذي الإضافة على طول اشتغلت اما الطريقة القديمة ماضبطت معاي وشكرا لك
![Screenshot_٢٠٢١٠٢٢٦-٠٣٥١٢٧_Chrome](https://user-images.githubusercontent.com/79666779/109239318-3dec1e80-77e6-11eb-9325-11c245b16307.jpg)

**Comment by emadmahdi** [comment]
لم افهم ماذا تعني بالطريقة القديمة ؟؟
وايضا هل جربت هذا الموقع ولم يعمل معك ؟؟

http://tiny.cc/kodiemad

.

**Comment by emadmahdi** [comment]
تم اصلاح المخزن الذي كان فيه مشكلة ... وانتظر منك ان تخبرني اذا طريقة تطبيق عماد عملت معك ام لا ؟؟

**Comment by aseel0o** [comment]
نعم طريقة تطبيق عماد يشتغل بس يغير سكن كودي فما يناسبني واشتغل مخزن عماد 👍
