### ISSUE TITLE
البرنامج رائع

### ISSUE THREAD

**Issue by mbatrawi** [emadmahdi/KODI#74]
شكرا على المجهود العظيم والمتابعة المستمرة والتحديث والتطوير
البرنامج أكثر من رائع ويعمل بكل كفاءة بدون مشاكل
شكرا جزيلا لكم

**Comment by emadmahdi** [comment]
الشكر لله اخي

وشكرا لك على التشجيع الذي يدفعنا الى الاستمرار في العطاء

**Comment by noweir** [comment]
ممكن تحدث رابط arabseed
https://arabseed.onl/

عرب لايونز
https://arblionz.net/

**Comment by noweir** [comment]
و اذا امكن تضيف الموقع ده
http://www.cartoon3rbi.net/index.html

**Comment by emadmahdi** [comment]
@noweir 
بالنسبة لموقعي عرب سييد وعرب لاينز تم تحديث الروابط في الاصدار الجديد ... ولا اعرف متى سوف انشر الاصدار الجديد

اما بالنسبة لموقع كارتون فيوجد كثير كارتون في برناامجي ومع هذا فسوف ادرس الموقع وارى اذا كان يستحق الاضافة
