### ISSUE TITLE
 Xcode

### ISSUE THREAD

**Issue by mbatrawi** [emadmahdi/KODI#75]
I have Xcode Mac Apple TV

**Comment by emadmahdi** [comment]
Do you know how to sign and notarize apple apps ?!

I did not do it before ... but i found lots of web pages describing the process of creating apple app and i can help you doing it step by step.

please let me know what is your apple development experience ... so i can found the proper method for creating an apple app ?1

**Comment by emadmahdi** [comment]
what i need to do is so simple ... I have apple dmg file and i want to ... add some files to it ... and change some other files in it ... and then sign and notarize the file again.

**Comment by mbatrawi** [comment]
Yes I can sign the app but only for one week as I am not developer
Also I can edit the files  
There is site sign kodi for Apple TV one year against $25

**Comment by mbatrawi** [comment]
I can not create apple applications 
Only I sign Aps created by developer

**Comment by emadmahdi** [comment]
is there any reason stopping you from creating a developer account ?! 

to my knowledge it is free account ... i am not sure but i think you cannot use apple device without having Apple ID account .. which is the same account used for apple developers !!

**Comment by mbatrawi** [comment]
Yes it’s free and I have free account which I can sign apps for one week only for personal use and back up at iCloud .
To sign apps for one year I should pay $99 per year to upload for others to use.
I.e developer account is free for personal use and paid for general use.

**Comment by emadmahdi** [comment]
what will happen after the 7 days ... the app will not install or will not work or what exactly ?!!

the below page is the procedure that kodi team are using to sign the kodi app for building MacOS kodi app ... I don't think you need to use your account to do it ... will you please check it and let me know ...

https://github.com/xbmc/xbmc/blob/master/docs/README.macOS.md

.

**Comment by mbatrawi** [comment]
The program will not work and you should sign again to work. When you click program it will not open until you re-sign .
This link how to install kodi on Apple TV
https://kodi.wiki/view/HOW-TO:Install_Kodi_on_Apple_TV_4_and_5_(HD_and_4K)

**Comment by emadmahdi** [comment]
so basically i cannot sign any apple app file without paying ... otherwise i need someone who have a paid developer account to do it for me .. right ?!

**Comment by mbatrawi** [comment]
Yes you are right (for general use or to be used by other person) -paid.
No you you are not right ( for using by yourself) which I am doing for myself each weak and any one else can do for himself -free .

**Comment by emadmahdi** [comment]
i don't need any of this for myself ... I am just trying to help people who have apple devices to get Arabic Kodi running without any technical experience ... i am not ready to pay for anything that i do not need/use

i spent lots of time and energy to develop my addon "Arabic Videos" ... hence i did more than any other person did for Arabic users .... I don't have apple devices and never used them in my whole life and i have no plans to use them in the future.

I will wait until i found a person who is ready either to pay for signing or can do the signing for arabic kodi apple installer.

Thank you.

**Comment by mbatrawi** [comment]
People can purchase kodi signed against $25 for one year and there is video on site showing how to install at Apple TV then they can install your addons.
 This the link https://www.koditvbox.tv/
Or they can sign for themselves each weak
Or they install on computer and use mirror for screen to TV which available at windows and Mac

**Comment by emadmahdi** [comment]
i guess this website is cheaper:

https://www.udidregistrations.com/buy?r=iosappsigner

**Comment by mbatrawi** [comment]
yes you are right

**Comment by emadmahdi** [comment]
can we use one of those certificates to sign apple app ?!
can you try ?

https://www.apple.com/certificateauthority

**Comment by emadmahdi** [comment]
the $25 website you sent to me .. it do signing of kodi installation file but to one device only ... the installation file works only one one device (one UDID) ... so it is completely useless ... I need the whole world to be able to install my kodi app.

**Comment by mbatrawi** [comment]
keep in your mind the developer of kodi  not able to upload it freely to apple store as I have mentioned above which is left to users to sign it individually. the same issue for popcorn time and many applications which are not available in apple store.

**Comment by mbatrawi** [comment]
you can download macos on virtual machine if you want 
https://www.wikigain.com/install-macos-catalina-on-virtualbox-on-windows/

**Comment by emadmahdi** [comment]
how about registering as a team member of a paid apple developer account for teams/businesses/groups/companies (i mean not a personal account)

yesterday i installed "macos big sur v11.0.1" as a virtual machine but it is slow ... and i don't think it can sign apps because the hardware udid is the same for all people who installed this virtual machine.

**Comment by emadmahdi** [comment]
there is lots of websites that do udid registration to join their development team ... but i don't know if the signed app can be installed only on the registered device or on all apple devices ?!

**Comment by mbatrawi** [comment]
> how about registering as a team member of a paid apple developer account for teams/businesses/groups/companies (i mean not a personal account)
Yes you can
> yesterday i installed "macos big sur v11.0.1" as a virtual machine but it is slow ... and i don't think it can sign apps because the hardware udid is the same for all people who installed this virtual machine.
Big Sur is heavy and its latest one also you can increase memory and number of processor for virtual machine.

Better install Mojave or Catalina.

**Comment by mbatrawi** [comment]
If would like to install real Mac check this
https://www.tonymacx86.com/threads/unibeast-install-macos-catalina-on-any-supported-intel-based-pc.285366/

**Comment by emadmahdi** [comment]
something weird happened ... the dmg file that i sent to you is installing now on my macOS virtual machine !!

I don't know what happened ... I tested the same file yesterday and it was not installable at all !!

I did not register or did anything .. I don't even know what is my udid ... and i still did not install xcode ?!!

**Comment by emadmahdi** [comment]
> If would like to install real Mac check this
> https://www.tonymacx86.com/threads/unibeast-install-macos-catalina-on-any-supported-intel-based-pc.285366/

i did not do this method for many reasons:
1. it needs empty usb flash stick
2. it needs a mac machine to prepare the macos installation files
3. it needs empty big hard disk partition
4. it needs uefi software
5. it need to enlarge the windows uefi disk partition

**Comment by emadmahdi** [comment]
try this link:
https://drive.google.com/file/d/1R5Tk1xVAHZ8cOW-5xTCoCkkuK4r8U1UX/view?usp=sharing
