### ISSUE TITLE
Emad arabic video kodi addon error

### ISSUE THREAD

**Issue by zkdura** [emadmahdi/KODI#77]
When I try to open it I get a sql3 data base read error

**Comment by emadmahdi** [comment]
ما هو رقم الاصدار الذي انت تستخدمه ... هل لديك الاصدار الاخير رقم
8.1.1

**Comment by zkdura** [comment]
رقم الإصدار 8.1.0The latest one on githubSent from my Galaxy
-------- Original message --------From: emadmahdi ***@***.***> Date: 2021-04-16  2:01 a.m.  (GMT-05:00) To: emadmahdi/KODI ***@***.***> Cc: zkdura ***@***.***>, Author ***@***.***> Subject: Re: [emadmahdi/KODI] Emad arabic video kodi addon error (#77) 

ما هو رقم الاصدار الذي انت تستخدمه ... هل لديك الاصدار الاخير رقم

8.1.1

**Comment by emadmahdi** [comment]
لم افهم رسالتك ... هل اختفت المشكلة عندك ام لا ؟

**Comment by zkdura** [comment]
المشكله لم تختفي... الإصدار الحالي 8.0.1 وهذا آخر إصدار متوفر على موقع gitHubSent from my Galaxy
-------- Original message --------From: emadmahdi ***@***.***> Date: 2021-04-16  3:39 p.m.  (GMT-05:00) To: emadmahdi/KODI ***@***.***> Cc: zkdura ***@***.***>, Author ***@***.***> Subject: Re: [emadmahdi/KODI] Emad arabic video kodi addon error (#77) 

لم افهم رسالتك ... هل اختفت المشكلة عندك ام لا ؟

**Comment by emadmahdi** [comment]
8.0.1 الاصدار 
جدا  قديم
الجديد هو 8.1.2

اذا انت لا تعرف كيف تقوم بالتحديث ... وبرنامجي لا يعمل عندك ... فاذن امسح كودي باكمله ثم قم بتثبيته مرة اخرى من هذا الموقع

http://tiny.cc/kodiemad
.
