### ISSUE TITLE
Is your addon  been haked by pop up messages with Shia-Sunna hate questions. Please fix it immediately. Thanks.

### ISSUE THREAD

**Issue by rfdslx** [emadmahdi/KODI#78]

**Comment by emadmahdi** [comment]
My messages are general information ... Send me the message that you think it is "Shia-Sunna hate" message !!
.

**Comment by rfdslx** [comment]
![Uploading 115082781...]

**Comment by rfdslx** [comment]
![image](https://user-images.githubusercontent.com/7109197/115082809-5827ac00-9ebb-11eb-8f60-708ae69b928b.jpeg)

**Comment by rfdslx** [comment]
![image](https://user-images.githubusercontent.com/7109197/115082831-637ad780-9ebb-11eb-835c-deaf56ff8b86.jpeg)

**Comment by rfdslx** [comment]
And others still pop ups!

**Comment by emadmahdi** [comment]
انا لا اجد مشكلة في الصورتين التي انت ارسلتها ... بالعكس هذه معلومات عامة عن نبي الاسلام ... معلومات عامة عن كيف قام اهل سنة الصحابة بمحاربة سمعة ودين واخلاق وطهارة رسول الاسلام محمد عليه وعلى اله الصلاة والسلام

اذا انت لم تكن تعرف هذه المعلومات عن نبي السنة فاذن الخطأ منك وليس من برنامجي ... الخطأ انك ترفض التعلم وترفض نشر العلم وفوق هذا تريد مني ان اتوقف عن نشر العلم ... من انت لكي تعلمني ماذا افعل وماذا لا افعل ... اهتم بامورك واترك بقية خلق الله يهتمون بامورهم

**Comment by emadmahdi** [comment]
انا فقط اسمح لك بالتعليق على عملي اذا كانت هذه الرسائل فيها خطأ وليست صحيحة

**Comment by rfdslx** [comment]
Your addon is deleted!

**Comment by emadmahdi** [comment]
great i appreciate your honesty

I know i will lose 80% of users ... but at least 2000 users will still benefit from my addon

**Comment by emadmahdi** [comment]
انا قضيت سنيتن ونصف اصنع هذا البرنامج ... وبعد كل هذا التعب تأتي انت لكي تعترض على عملي .. وتريد مني ان امسح رسالة صغيرة في برنامجي وهي مجرد معلومات عامة ... انا سعيد جدا اني اخسر امثالك لانك لا تحترم تعب خلق الله وتفكر فقط في نفسك ... وامثالك انا لا اريدهم ان يستفيدوا من برنامجي ومن تعبي لانك ببساطة ... اما ارهابي داعشي ... واما لا تعرف ال محمد ... واما سني جاهل ولا تفكر ... واما تعبد الصحابة ... واما تعبد كتب الصحاح ...  واما تكره شيعة ال محمد الى درجة الجنون ... وكل هؤلاء لا يستحقون ان يستفيدوا من برنامجي وتعبي وعملي
