### ISSUE TITLE
التحديث الاخير

### ISSUE THREAD

**Issue by express1900** [emadmahdi/KODI#79]
السلام عليكم،، والله انصدمت ب لبرنامجك،، عندما اقحمت رسول الله والخلاف بين السنه والشيعه، إذا كان ذلك عن قصد فهذا عيب عليك تقحم اشرف الخلق لإثبات من الصح السنه ولا الشيعه،،... اخي العزيز ارجوا حذف ذلك ورجأ عدم اقحام الدين... لك ما تؤمن وهذا حريه شخصيه لك... لاتفرضها على الغير.. وخصوصا ان هناك غير مسلمين يستخدمون برنامجك... تحياتي

**Comment by zombiB** [comment]
أتفق تماما مع الأخ،كما أرجو أن تقوم بحذف اضافتي ماتريكس من الربوزيتوري خاصتك ، لا أريد أن يرتبط عملي بهذا النزاع و هذه الإساءة للسنة و شكرا

**Comment by emadmahdi** [comment]
من حقي ان ادافع عن نفسي ضد الافكار القذرة التي تدور في رؤوس الكثير من الحمقى الذين لا يعرفون شيء عني

**Comment by emadmahdi** [comment]
من حقي ان ادافع عن نفسي ضد الافكار القذرة التي تدور في رؤوس الكثير من الحمقى الذين لا يعرفون شيء عني

اما كلمة اساءة فارجوك ارسل لي الرسالة التي فيها اساءة لكي امسحها ... الا اذا كنت تقصد ان الحقيقة مؤلمة جدا وموجعة جدا

اما اضافة ماتركس فانا لم اضيفها لبرنامجي ولن اضيفها لبرنامجي ... انا اضفت فقط المخزن

اما غير المسلمين فانا نعم اريدهم ان يعرفوا ان النبي محمد اطهر بكثير من الاشاعات والافتراءات والاكاذيب التي ينشرها اهل سنة الصحابة ضد اطهر انسان في الكون وهو الرسول محمد عليه وعلى اله الصلاة والسلام

**Comment by emadmahdi** [comment]
من حقي ان ادافع عن نفسي ضد الافكار القذرة التي تدور في رؤوس الكثير من الحمقى الذين لا يعرفون شيء عني ... وايضا من حقي ان ادافع عن نبي الله وحبيبه ورسوله ضد الاكاذيب التي ينشرها اهل سنة الصحابة ضد رسول الله

اما كلمة اساءة فارجوك ارسل لي الرسالة التي فيها اساءة لكي امسحها ... الا اذا كنت تقصد ان الحقيقة مؤلمة جدا وموجعة جدا

اما غير المسلمين فانا نعم اريدهم ان يعرفوا ان النبي محمد اطهر بكثير من الاشاعات والافتراءات والاكاذيب التي ينشرها اهل سنة الصحابة ضد الرسول محمد عليه وعلى اله الصلاة والسلام ... خذ مثلا جريمة زواج الرسول من طفلة عمرها 6 سنوات ... ماذا تعتقد رأي الكفار في هذه الكذبة الحقيرة ... لعنة الله على من اخترع هذه الكذبة ضد اشرف واطهر انسان خلقه الله

اما اضافة ماتركس فانا لم اضيفها لبرنامجي ولن اضيفها لبرنامجي ... انا اضفت فقط المخزن ... ويسعدني جدا ان امسح مخزنك من مخازن عماد ... وقد تم المسح وتم نشر اصدار جديد رقم 6.2.0

**Comment by emadmahdi** [comment]
انا فقط اسمح لك بالتعليق على عملي اذا كانت هذه الرسائل فيها خطأ وليست صحيحة

**Comment by express1900** [comment]
أخي الكريم،، احنا مو ضد ان تنشر أفكارك كما تريد،،، لكن هذا ليس المكان او الأسلوب المناسب. انا لو كنت مكانك لكنت عملتها بالصفحه الخاصه بك وعلى صفحتك على الفيس بوك.. وانا كمسلم لا أقبل اي احد ان يمس لا عقيدتي ولا نبي... حريه العقيده مكفوله للجميع... بس العرض غير موفق... انت حر بأن تكتب على برنامجك ماتريد،،، ولكن الا ترى ان من الأفضل الجمع بين المسلمين بدل من الفرقه... تحياتي

**Comment by emadmahdi** [comment]
انا قضيت سنيتن ونصف اصنع هذا البرنامج ... وبعد كل هذا التعب تأتي انت لكي تعترض على عملي .. وتريد مني ان امسح رسالة صغيرة في برنامجي وهي مجرد معلومات عامة ... انا سعيد جدا اني اخسر امثالك لانك لا تحترم تعب خلق الله وتفكر فقط في نفسك ... وامثالك انا لا اريدهم ان يستفيدوا من برنامجي ومن تعبي لانك ببساطة ... اما ارهابي داعشي ... واما لا تعرف ال محمد ... واما ترى نفسك ملاك ... واما سني جاهل ولا تفكر ... واما تعبد الصحابة ... واما تعبد كتب الصحاح ... واما تكره شيعة ال محمد الى درجة الجنون ... وكل هؤلاء لا يستحقون ان يستفيدوا من برنامجي وتعبي وعملي

**Comment by express1900** [comment]
انا مقدر جهدك وتعبك،، ولو تقرأ رسالتي لك ترى فيها انا مدا اهاجمك ولا اعترض على شئ،، انا كمسلم دا اوجهك كأخ لك،، وبعدين منو قالك انا سني،، انا داقولك على الطريقه.. كتلك حتى رسائل توجيهه توعي العلم مو تنفرهم... بالاخير ان قبلت بنصيحتي كان بها لم تاخذ بها فأنت حر... وبعدين الناس دا تتكلم معك بكل احترام  انت نازل بيهم ونعتني باهرابي وداعشي لو صدامي لو سني جاهل... الجاهل اخي الكريم هو الي ما يسمع للآخر.. ويتحلي بأخلاق ال البيت صلوات الله عليهم...

**Comment by emadmahdi** [comment]
@express1900 
قبل ايام واجهت شخص كنت اظن انه صديقي وكنت اتكلم معه تقريبا يوميا ولعدة اشهر الى ان جاء ذكر ال محمد عندها عرفت حقيقة هذا الشخص ... وجدت انه يتهم الشيعة بامور من اقذر الاشياء وهو مقتنع انه على حق وان كل الشيعة كفار ... هذا الشخص انا لا اريد امثاله ان يستفيدوا من برنامجي ولم اجد طريقة افضل لكي اعرف صديقي من عدوي الا هذه الرسائل ... انا الى الان اضفت فقط 21 رسالة ولكن عندي منها المئات وكلها من كتب الصحاح والعياذ بالله

**Comment by express1900** [comment]
مثل ما كتلك عماد حطها كوسيله توعيه مثل هل تعلم... كذا وكذا... إلى اخره

**Comment by emadmahdi** [comment]
شخص يتهم الرسول بجريمة عبس وتولى ويتهمه بالزواج من طفلة ... هل تريد ان تقول له انه مخطيء وان الشيعة هم الصح

هكذا شخص لا ينفع معه الا طريقة القوة او طريقة ان تقولها في وجهه صريحة انه مجرم عندما يتهم الرسول بهكذا جرائم

**Comment by express1900** [comment]
اخ عماد. مثل ما نصحتك. أو اقترحت عليك،،، وصل معلوماتك بأسلوب يعكس روح وأخلاق ال البيت

**Comment by emadmahdi** [comment]
ثم انا قاصد ان اقول انه هناك نسختين من الرسول محمد .. نسخة الشيعة ونسخة السنة ... ممكن تخبرني كيف تريد ان تكتب عبارة بهذا المعنى وتكررها كثيرا وتجبر الناس على الاعتراف بها ... وكل هذا في رسالة قصيرة من عدة كلمات وليس جريدة ومقالة كاملة تراعي فيها شعور فلان وعلان .. ونتيجتها في النهاية انهم يتهموك بالتقية ويقولون ان كلامك كله كذب وانك تقول ما لا تؤمن به

كيف تريد ان تحل هكذا معضلة بكلمات قليلة

**Comment by express1900** [comment]
هل تحب اكتبلك الايميل الخاص بي حتى نكمل الموضوع؟

**Comment by emadmahdi** [comment]
https://www.facebook.com/emadmahdi1

**Comment by express1900** [comment]
بعثت لك رساله على الماسنجر

**Comment by kwuw** [comment]
الفتنة نائمة لعن الله من ايقظها

معتقداتك تخصك لكن هذا البرنامج ليس محل لنشرها .. اشك انك مطور برمجيات لان من ابسط اخلاقيات و اداب التطوير (ناهيك عن اداب الاسلام) هى عدم الغش .. انت تستخدم برنامج الغرض المعلن منه مشاهدة محتوى مواقع فيديو (لعب ولهو فى الاغلبية العظمى)  لنشر معتقداتك الشخصية بدون اعلان ذلك أو اعطاء الاختيار للمستخدم فى تفعيل او اغلاق تلك الرسائل المباشرة.

لا شىء يمنعك من تطوير اى برنامج لنشر ما تراه صواب من فكر طائفى .. لكن سوء استغلال المنصة هى المشكلة

ملاحظة .. لو كان التوعية بالدين الهدف فكان من الاولى ان لا تطور برنامج لتشغيل محتوى مسروق .. بدون الدخول فى جدل حول حرمة مشاهدة المحتوى .. انما الغير قابل للنقاش ان وظيفة الاد اون هى الوصول لمحتوى نفسه منشور دون تصريح من المواقع التى من الاصل تنشره دون الحصول على حقوق توزيعه من صاحبه الاصلى

BTW, it's not that hard to undo these recent changes (on a local copy then reinstall the addon) or use an older version of the addon, hope everyone is already doing that, or even refork it into another addon without "divisive messaging", I am not really insulted about your choice just surprised about how immature and tone-deaf it is, esp. in Ramadan.

 ربنا يهديك! ويسامحك على ما سببته من اذى لكثير من الناس دون ادنى سبب

**Comment by emadmahdi** [comment]
@kwuw
ارجوك ان لا تستخدم برنامجي ... لاني لا احب امثالك ان يستفيدوا من عملي وتعبي ... ولهذا لسبب انا وضعت هذه الرسائل ... لكي اكتشف امثالك واطردهم من برنامجي

**Comment by kwuw** [comment]
يا اخى لولا غيرك ما الت اليك..

It's called open source for a reason.

ولكن بنفس الفكر العبثى لما تستفيد  انت من اعمال اهل السنة؟ عدل الاد اون لحذف اى محتوى من دول سنية و اعلنه اد اون شيعى ان استطعت

 قما قلت انت حر فى معتقدك .. ورسائلك لم تضايقنى (كما ان ازالتها من نسخة محلية لم يستغرق اى وقت) .,,, انا فقط اربأ بك عن  السقوط فى بئر الطائفية الكريه 
 
دع عند هذا الخطاب المفرق يا اخى فى الله .. لو كانت لك مشكلة شخصية مع مسلم اخر فهذا ليس ميدان حلها .. انت لا تستطبع منع احد من استخدام او تعديل البرنامج ... كل ما سيحدث هو فض الناس عنك 

اللهم بلغت .. اللهم فاشهد

**Comment by emadmahdi** [comment]
@kwuw
ارجوك ان لا تستخدم برنامجي

**Comment by emadmahdi** [comment]
@kwuw
جيد انك اعترفت انك سارق وانك تسرق تعب الناس وانك تسجلها لصالحك ... تصرف طبيعي تعودت عليه من الذين يعبدون الصحابة

**Comment by mellsaid** [comment]
أرجوك ممكن نخلي الدين بعيدا عن التطوير.
احترم جميع الديانات و المذاهب، و لاكن بنفس الوقت لا أجبر أحد بوجهة نظري. 

الرسالة تجبر مستخدم البرنامج علي رأيك الشخصي لاستخدام البرنامج، وضغط زر الرجوع، بتهزء المستخدم علي وجهة نظره....

الرجاء نخلي الدين و السياسة هيا وجهة نظر شخصية

احب برنامجك، وبدعمه و احترمك شخصيا علي جهدك، لاكن بلاش   جبر محبينك، بأمور شخصية.

**Comment by simoxor** [comment]
السلام عليكم يعني تريدني أن أصدق من يقول بول الأئمة وغائطهم سبب دخول الجنة
ليس في بول الأئمة وغائطهم استخباث ولا نتن ولا قذارة بل هما كالمسك الأذفر، بل من شرب بولهم وغائطهم ودمهم يحرم الله عليه النار واستوجب دخول الجنة) (أنوار الولاية لآية الله الآخوند ملا زين العابدين الكلبايكاني 1409هـ – ص 440)
الكلام أثناء الجماع يورث الخرس
عَنْ عَبْدِ اللَّهِ بْنِ سِنَانٍ قَالَ قَالَ أَبُو عَبْدِ اللَّهِ ع اتَّقُوا الْكَلَامَ عِنْدَ مُلْتَقَى الْخِتَانَيْنِ فَإِنَّهُ يُورِثُ الْخَرَسَ» (الكافي5/498).
الحسن يتكلم سبعين مليون لغة
عن أبي عبد الله أن الحسن قال » إن لله مدينتين، إحداهما بالمشرق والأخرى بالمغرب. وفيها سبعون ألف ألف لغة. يتكلم كل لغة بخلاف لغة صاحبها. وأنا أعرف جميع تلك اللغات (الكافي 1/384-385 كتاب الحجة. باب مولد الحسن بن علي).
المهدي صار ربا

يقول الوحيد الخراساني بصراحة مثيرة :
-" إن إمام العصر صار عبدا ، وعندما صار عبدا صار ربا ، فـ " العبودية جوهرة كنهها الربوبية" فمن ملك هذه الجوهرة تحققت ربوبيته – بالله تعالى لا بالاستقلال – بالنسبة إلى الأشياء الأخرى.
صفحة 52 من كتاب مقتطفات ولائية ، ترجمة عباس بن نخي ، المحاضرة الثالثة تحت عنوان (صبر الحجة) ألقاها في المسجد- الأعظم بقم بتاريخ 13 شعبان 1411
 الموافق 27/2/1991
1-يعتقد علماء الشيعة ان القرآن محرف
2-ودين الشيعة قائم على تاليه البشر و عبادتهم من دون الله
3- وتحول الدين من عبادة الله الي عبادة الائمة و اللطم على الحسين
4-اصبح اللعن من العبادة مثل سب ولعن معاوية ويزيد و الصحابة بل الامة الاسلامية -و اللعن و الشتم عبادة من شروط التوحيد
5هل البراءة ولعن الصحابة من شروط التوحيد
6-يكفر جميع المسلمين لاننا لا نؤمن بولاية 12 امام
7-اباحة دماء واموال اهل السنة
8-اعطاء الولي الفقيه صلاحية الهية كالغاء العبادات و كالصلاة واباحة المحرمات كاباحة اللواط كما افتى المرجع مصباح يزدي ضد المعتقلين في سجون الولي الفقيه ضد الذين استنكروا تزوير انتخابات الرئاسة الايرانية ام تحليل المخدرات كما افتى الخوئي و للمرحع صلاحية التشريع
9- اتهام امهات المؤمنين بالكفر والفاحشة
10- اباجة الكذب و بهت المخالف فتوى الخوئي التقية لاتجوز للنبي وتجوز للامام
11- اسقاط الجهاد حتى ظهور المهدي
12- المسجد الاقصى ليس في فلسطين
13- الامام افضل من الانبياء موسى و عيسي و ابراهيم و نوح
14- الامام له ولاية تكوينية
15- كسرى يدخل الجنة و النبي يدخل النار
16- الشيعة من قتلوا الحسين و علي
17- الائمة يبغضون الشيعة
18-الاشتر اغضب علي
19- الشيعي شمر قتل الحسين و الشيعي ابن ملجم قتل الحسن
20- الولاية شرط في قبول الشهادتين
21-المرجع يشرع
22- اباحة اللواط ونذكر في فتوى المرجع الشيعي مصباح يزدي الذي افتى الي اباحة اللواط في الرجال واغتصاب النساء في سجون الولي الفقيه ضد الذين استنكروا تزوير انتخابات الرئاسة الايرانية 
و قول الشيخ عباس الخوئي ان طلاب الحوازات يلاط بهم ثم يصبحوا مراجع
و من ثمار الشيعة الاثناعشرية تعرفونهم ظهور الحركة السلوكية المهدوية التي تبيح اللواط و تبادل الزوجات و التقل و الاجرام 
لغرض تعجيل ظهور المهدي وراينا مخازي مشايخ الشعية من امثال الشيخ مناف الناجي وكيل السيستاني الذي انتهك عرض النساء التي يدرسن في الحوزة التي يشرف عليها وصورهم و هو يلحس فروجهم

و حتى نعرف ان الشيعة الاثناعشرية لهم دين غير دين الاسلام 
انهم يدفنون موتاهم في مقابر خاصة مثل النصارى واليهود

كما اعترف الشيخ نعمة الله الجزائري
يقول السيد نعمة الله الجزائري في كتاب الانوار النعمانية : ــ

((إننا لم نجتمع معهم – أي مع أهل السنة – لاعلى إله و لا على نبي و لا على إمام ، و ذلك أنهم يقولون : إن ربهم هو الذي كان محمداً نبيه ، و خليفته بعده أبو بكر ، ونحن – أي الرافضة – لا نؤمن بهذا الرب و لا بذلك النبي ، إن الرب الذي خليفة نبيه أبو بكر ، ليس ربنا و لا ذلك النبي نبينا )).
وإذا أردت أتيك بالمزيد من كتبكم فهل تستطيع أن تظع شيئ من هدا كرسالة في برنامجك أشك

**Comment by emadmahdi** [comment]
@simoxor 
يسعدني جدا ان تمسح برنامجي بالكامل من اجهزتك كلها ... لاني لا احب المنافقين والجهلة امثالك

**Comment by mellsaid** [comment]
> أرجوك ممكن نخلي الدين بعيدا عن التطوير.
> احترم جميع الديانات و المذاهب، و لاكن بنفس الوقت لا أجبر أحد بوجهة نظري.
> 
> الرسالة تجبر مستخدم البرنامج علي رأيك الشخصي لاستخدام البرنامج، وضغط زر الرجوع، بتهزء المستخدم علي وجهة نظره....
> 
> الرجاء نخلي الدين و السياسة هيا وجهة نظر شخصية
> 
> احب برنامجك، وبدعمه و احترمك شخصيا علي جهدك، لاكن بلاش جبر محبينك، بأمور شخصية.

..

**Comment by simoxor** [comment]
كل ماقلته في تعليقي من كتب علمائكم وأرى أنك صدمت مما قرأت لأنك تجهل دينك دين الشيعة والله لو علمت بما يقوله معمميكم لأنكرت هدا الدين الباطل المبتدع
