### ISSUE TITLE
مشكلة في المواقع التي تستخدم سيرفرات خارجية

### ISSUE THREAD

**Issue by hussapril7** [emadmahdi/KODI#8]
كيف حالك اخ عماد، اتمنى تكون بكل خير

حبيب قلبي اليوم حدثت الاضافه لاخر تحديث 
3.9.3

ولكن للاسف ثلاث مواقع ماتشتغل 
-شاهد فور يوو
-هلا سيما
-هلال يوتيوب

دخلت على فلم وكل الروابط لاتشتغل في هذي المواقع

موقع ايجي بيست شغال 100% بس المواقع الاخرى المذكوره فوق لاتشتغل 

بعدها رحت لصفحتك هذي على القيت هب
قلت بنزل الاضافة بالاصدار القديم
3.9.2

بس للاسف لم اجد الملف الخاص بالاصدارات السابقه في صفحتك

اتمنى اخ عماد ترجع ملف الاصدارات السابقه
في حال واجهتنا مشاكل بالتحديثات نلجأ لاصدارات سابقه 
لين يتم حل مشاكل التحديثات

**Comment by emadmahdi** [comment]
وعليكم السلام

المواقع الثلاثة التي انت ذكرتها لم يجري عليها اي تحديث من فترة طويلة

الشيء المشترك في هذه المواقع الثلاثة هو انها تستخدم سيرفرات خارجية وهذه السيرفرات الكثير منها لا يعمل بسبب 
 حقوق الطبع وحقوق الالفية الرقمية ... ولا توجد طريقة لاصلاح المشكلة الا ان يقوم الموقع الاصلي بتنظيف قائمة السيرفرات وايضا مسح السيرفرات التي لا تعمل

**Comment by emadmahdi** [comment]
جرب سيرفرات اخرى ... انا فحصت الان المواقع الثلاثة وكلها تعمل بصورة صحيحة ولكن السيرفرات كما قلت لك الكثير منها لا يعمل

**Comment by hussapril7** [comment]
اوك اخ عماد مشكور على التوضيح، بس اذا سمحت ممكن ترد قسم الاصدارات السابقه في حسابك على القت هب ؟؟
