### ISSUE TITLE
 لا للعنصرية

### ISSUE THREAD

**Issue by sarbast1985** [emadmahdi/KODI#80]
كنت استخدم البرنامج بس بعد ما تم اضافة السؤال في البداية عن النبي (ص) و بصراحة فاجئت منك و ابد ما كنت متخيل اشوف عقلية صغيرة مثل عقليتك.
بصراحة انت شخص مريض نفسيا و بحاجة الى معالجة و الافضل قبل تطوير البرنامج ان تعالج نفسك من هذه العقلية المريضة و لا يوجد اي نبي شيعي و نبينا هو محمد (ص) لكل المسلمين و نحن ابدا ما نقول للسنة او للشيعة للكل !!! بس مع الاسف ما دام يوجد اشخاص من امثالك سيبقى المشاكل التي نواجهها يوميا في دول المسلمين.

**Comment by emadmahdi** [comment]
رسالة جدا صغيرة في مصلحة الشيعة ازعجتك ... الحمد لله انك فضحت نفسك

ارجوك لا تستخدم برنامجي وامسحه بالكامل

**Comment by emadmahdi** [comment]
لو عندك ذرة عقل كان وقفت معي لكي نحمي رسول الله من القاذورات التي اخترعها اهل سنة الصحابة ضد حبيب الله

**Comment by sarbast1985** [comment]
طائفي رخيص
