### ISSUE TITLE
انا لا استخدم البرنامج

### ISSUE THREAD

**Issue by sarbast1985** [emadmahdi/KODI#81]
و انت فضحت الشيعة كلهم لانك تريد دعم الشيعة مثل ما تقول 
باكذب الكذب و اي شيء مبني على الكذب باطل ... اعتقد فهمت و اذا ما فهمت بعد المعالجة راح تفهم
يا بلا عقل
 و راح اهاجمك في كل المنصات و راح افضحك

**Comment by sarbast1985** [comment]
انا من اهل السنة و انا ضد هذه العقلية الي من امثالك

**Comment by sarbast1985** [comment]
و انا لا اسمح ان تهاجم اي من الصحابة ابو بكر و عمر و عثمان و علي

**Comment by HayderHamza** [comment]
الحجي يمكن عنده معلومات باقي المسلمين اللي اكثر من مليار انسان  ما يعرفوها، منو نبي الشيعة ؟ زين منو نبي السنة؟
زين محمد بن عبدالله نبي منو ؟

**Comment by sarbast1985** [comment]
صح 100%100
و ارجوا من كل مسلم ان يمسح البرنامج حتى يتم ازالة الرسالة 
الطائفية
بلنسبة لي انا لا استخدم البرنامج من وقت ما نزل تحديث الكودي 19 و البارحة شفت التحديث و جربت بس من شفت الرسالة مسحت البرنامج بلكامل.
يوجد بديل احسن انا استخدم على الموبايل و اندرويد تي في بوكس و هي عبارة عن تطبيق خفيف يحتوي على قنوات و افلام و مسلسلات و بجودة عالية و كل هذا مجانا
اسم التطبيق اسطورة 
فقط اكتب بلكوكل ostora

**Comment by sarbast1985** [comment]
من السؤال تعرف مدى عقلية و الطائفية هذا الشخص

**Comment by HayderHamza** [comment]
كلام صحيح جدا و عاشت ايدك على المعلومة البرنامج راح احذفة وانزل البرنامج اللي وصيت بيه
