### ISSUE TITLE
موقع هلا سيما لا يعمل

### ISSUE THREAD

**Issue by hussapril7** [emadmahdi/KODI#9]
اهلا فيك اخ عماد شكرا على تحديثاتك وماشاءالله مره عن مره الاضافه في تطور وبشكل مرتب وسهل
فا شكرا على جهدك ووقتك وبارك الله فيك 

بس في مشكله بسيطه وهو موقع هلا سيما لايدخل نهائي 

اما باقي المواقع جمعيها شغاله بشكل جيد
 فا ارجوا ان تعرف ماهي المشكله وان يتم اصلاحها 

وشي آخر اذا سمحت

انا في الرساله السابقه ذكرت لك انه ملف الاصدارات السابقه لبرنامج كان موجود على حسابك بالقت هب
وقلت لك اريد ان تسترجع هذا الملف 

لان في حال واجهتنا مشاكل في اي تحديث نلجأ لاصدارات سابقه لحين حل مشاكل اي تحديث جديد
هذي كانت وجهة نظري لان كنت اطبقها في السابق 

فا اتمنى منك اخ عماد ان ترجع ملف الاصدارات السابقه كا احتياط 

وشكرا لك

**Comment by emadmahdi** [comment]
وعليكم السلام ورحمة الله

الاصدارات القديمة لا حاجة لها ولا تنفع في اي شيء ... المشاكل التي تحدث لا علاقة لها بالتحديثات التي انا اصدرها ... عادة جميع المشاكل سببها تغيرات يقوم بها الموقع الاصلي ... مثلا المشكلة الحالية في موقع الهلا سيما هي انهم اضافوا طبقة من الحماية على السيرفر الخاص بهم وهذا معناه يجب علي ان اقوم بتغيير برنامجي لكي يتجاوز طبقة الحماية وقد تم هذا فعلا في الاصدار الجديد الذي سوف اصدره في الساعات القادمة

وشكرا على اخباري بمشلكة الهلا سيما

**Comment by emadmahdi** [comment]
وبالمناسبة لو قمت بتجربة جميع اصدارات برنامجي بداية من اول اصدار 1.0.0 فان موقع هلا سيما لن يعمل الا في الاصدار الجديد الذي سوف اصدره في الساعات القادمة

**Comment by hussapril7** [comment]
والله يا اخ عماد ماشاءالله عليك ربي يزيدك في علمك وفهمك في هذا المجال 

شكرا لك على التوضيح وعلى كل شي تقدمه لنا 

وبانتظار التحديث القادم 👊

**Comment by emadmahdi** [comment]
تم رفع الاصدار 3.9.6 وفيه علاج مشكلة هلا سيما

**Comment by emadmahdi** [comment]
حاليا موقع هلا سيما مغلق ... جرب الاصدار الجديد في وقت اخر

**Comment by hussapril7** [comment]
ان شاءالله 👍
